### ISSUE TITLE
Error is not propagated. Mono hangs when StackOverflowError is thrown in map or flatMap

### ISSUE THREAD

**Issue by 0v1se** [reactor/reactor-core#1118]
### Expected behavior
StackOverFlow should be thrown
### Actual behavior
java.lang.IllegalStateException: Timeout on blocking read for 5000 MILLISECONDS
### Steps to reproduce
run strange method provided:

    private void exception() {
        exception();
    }

    public void strange() {
        CompletableFuture<Integer> future = new CompletableFuture<>();
        future.complete(1);
        Mono<Integer> simple = Mono.fromFuture(future);//Mono.just(1)

        simple.map(r -> {
            exception();
            return r;
        }).block(Duration.ofSeconds(5));
    }
### Reactor Core version
3.1.5.RELEASE
### JVM version (e.g. `java -version`)
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**Comment by smaldini** [comment]
StackOverflowError is considered a fatal error and falls into the general catch-all error from `Hooks.onErrorDropped(consumer)`. We might want to clarify that @simonbasle

**Comment by simonbasle** [comment]
It is expected that a fatal error like `StackOverflowError` isn't propagated as an `onError` signal. However, what is not good in your case is that you don't see any trace of the error.

Looks like the error was swallowed by the `CompletableFuture.whenComplete` method :(

We made it so `Mono.fromFuture` will now explicitly "drop" the error (see the `Hooks.onErrorDropped` consumer). Additionally, the default behaviour of the error drop hook is now to _log the dropped exception_ additionally to bubbling it up.

As a result, what you'd see after the fix is a timeout exception + logs of the stack overflow error.

**Comment by 0v1se** [comment]
Ok. Thanks. 
Where can I get the list of fatal errors? It's not obvious what errors can be swallowed.

Also, such behaviour can be observed not only when CompletableFuture is used. It was only an example
