### ISSUE TITLE
Provide base Metrics story from Scannable

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1123]
Explore : 
 - domain for metrics (look at spring integration and others)
 - Metrics Flux, Mono, ParallelFlux and Scheduler
 - Built from Scannable
 - Export JMX ? Expose Public ?
 - Use operator / hooks / tag feature ?

**Comment by simonbasle** [comment]
- activate by placing `.metrics()` in a Flux chain
 - alternatively activate globally as a hook
 - uses the operator to gather metrics from the immediate upstream, computed from the perceivable events (don't care about the events further up the chain)
 - override to give a tag/name to the metrics specifically?
 - implement as a `InnerOperator` that detects if `Micrometer` is there at runtime
 - fallback to a very dumbed down gather and store method for when there is nothing, a bit like with logging (SL4FJ vs Console)

What to gather:
 - time from subscribe to termination
 - average time between onNext
 - number of `onNext`
 - number of `onError`
 - number of `onComplete`
 - `Scheduler`-related? (eg. number of `publishOn`/`subscribeOn`/execution context switches)?

**Comment by simonbasle** [comment]
This has been mostly fixed by #1183 (commit 425bf5c), we have a follow-up issue for schedulers backed by executor services (#1201) and will open further issues as relevant (eg. for the JMX access and auto conversion of `Scannable`, which I don't think is very relevant as Metrics need to be actively gathered)
