### ISSUE TITLE
CacheWhen Operator?

### ISSUE THREAD

**Issue by chringwer** [reactor/reactor-core#1125]
I am missing an operator to cache a result for some timespan depending on the emitted result. The use case I tried to implement is inspecting cache headers from an HTTP response and then serve the cached resource to every new subscriber until the TTL has elapsed. (which would cause a new request to the source on next subscribe)

```
webClient.get()
         .uri("https://my-costly-resource")
         .exchange()
         .cacheWhen(response -> Mono.just(Duration.ofMillis(ttlAsMillis(response))));
```
Does that make sense or there another way to do this with the current APIs?

**Comment by simonbasle** [comment]
We _could_ do something like this, **but for `Mono` only** (which I think makes sense as it would be confusing to try and generate a TTL out of multiple values).

However, we need to generalize the concept:

 - what should happen if the cached source errors?
 - what should happen if the cached source completes empty?
 - what should happen if the TTL-generating `Function` throws?

Also, do we really need a `Publisher`-based version? a `Function<T, Duration>` could work just as well, with minimal adaptation to the existing operator as a bonus.

I see two main options:

1. take a `Function<Signal<T>, Duration>` (that would need to cover the `onComplete` and `onError` case above as well)
2. take a `Function<T, Duration>`, a `Function<Throwable, Duration>` and a `Supplier<Duration>` (separately tune the valued, errored and empty cases)

**Comment by simonbasle** [comment]
(work in progress in https://github.com/reactor/reactor-core/compare/1125-MonoCacheTimeTTLGenerators, will need to be rebased on top of #1116)

**Comment by chringwer** [comment]
Good point! I think a third option would be a `BiFunction<T, Throwable, Duration>`. Similar to `Mono#doOnSuccessOrError()`?

**Comment by simonbasle** [comment]
PR #1129 takes the following stance:
 - adds a variant with 3 TTL generators: `Function<T,Duration>`, `Function<Throwable,Duration>` and `Supplier<Duration>`
 - if one of the generators throws an `Exception`, which can only happen at a cache miss, that exception is propagated to the subscriber instead of the source value.
   - the original value or error is dropped (`Operators.onNextDropped`/`Operators.onErrorDropped`)
   - However, the cache eviction is immediately triggered, letting subsequent subscribers trigger a cache miss again (aka if the error is transient, it won't be indefinitely replayed to further subscribers)

How does that sound @chringwer ?

**Comment by chringwer** [comment]
Sounds awesome! Thanks for picking this up.
