### ISSUE TITLE
reactor publishing in javafx ui thread

### ISSUE THREAD

**Issue by rebai-halim** [reactor/reactor-core#1143]
hi

i use reactor 3.1.5 , my queston is :

how to publish (using publishOn method) data in javafx ui thread

some exemple (code) to help me

thanks.

**Comment by simonbasle** [comment]
There is currently no `Scheduler` facade over JavaFX `Platform.runLater(Runnable)`, that I know of.

Since submitting a task to the JavaFX UI Thread is already asynchronous, your best bet is probably to skip `publishOn` entirely and trigger UI work using `runLater`:


```java
Flux.interval(Duration.ofMillis(500))
    .map(i -> "tick number " + i)
//alternative to doing it in the subscribe, if you want to continue working with the data
//  .doOnNext(tickMessage -> Platform.runLater(() -> label.setText(tickMessage)))
    .subscribe(tickMessage -> Platform.runLater(() -> label.setText(tickMessage)),
        //in case of error one can also eg. display a non-blocking alert dialog
        error -> Platform.runLater(new Alert(AlertType.ERROR, error.getMessage())::show);
```

In #reactor/reactor-addons repo, we have a `SwingScheduler`, so it could make sense to add a `JavaFX` scheduler for optimization purposes. For RxJava2 there's a JavaFX dedicated project that includes such a `Scheduler` (which would be pretty similar in Reactor):

https://github.com/ReactiveX/RxJavaFX/blob/2.x/src/main/java/io/reactivex/rxjavafx/schedulers/JavaFxScheduler.java

**Comment by rebai-halim** [comment]
thank you and i hope to see scheduler for javafx ui with reactor soon

i have some questions : 

1. what deff between map && concatMap (merge && concat, ....)

2. how to process any error in flux or mono in last process excecution

3. how to reactor organiser execution of operators like : doOnError && onErrorDo 

4. in flux what mean delaySequense

**Comment by simonbasle** [comment]
Most of these questions would find an answer in the [reference documentation](http://projectreactor.io/docs/core/release/reference/docs/index.html), which I encourage you to read first and foremost.

Next best place to ask these questions is on [StackOverflow `[project-reactor]`](https://stackoverflow.com/questions/tagged/project-reactor) (please research first, as these have probably been asked and answered before) or on our [Gitter channel](https://gitter.im/reactor/reactor), rather than in a GitHub issue.

**Comment by rebai-halim** [comment]
thanks

i see docs but in not understand what i asked for, if it possible to explain to me what i asked for 

thanks for your time

**Comment by simonbasle** [comment]
1. what deff between map && concatMap (merge && concat, ....)
`map` is a 1-to-1 transformation. it _could_ transform to a `Publisher` like `concatMap`/`flatMap` (ie take a flatmap-compatible `Function<T, Publisher<R>>`), but it wouldn't know that it needs to do something (subscribe) with the `Publisher`. `concatMap` imposes a transformation to a `Publisher`, which it subscribes to. Whatever the `Publisher` emits, `concatMap` forwards as part of the main sequence. When that publisher is done, `concatMap` generates the next one (from the next source element `T`) and subscribes to it, and so on... Since these `Publishers` can emit multiple elements, you get a 1-to-N transformation for a single source element.

2. how to process any error in flux or mono in last process excecution
See the reference documentation and `onError*` operators.

3. how to reactor organiser execution of operators like : doOnError && onErrorResume, ..... 
I didn't quite understand that question, but operators follow the decorator pattern, so they are applied in the order they are chained together (`.map.filter` -> `map` is executed first and each result of the `map` is passed as input to the `filter`).

4. in flux what mean delaySequense
`delaySequence` introduces a delay before the first element is emitted. For instance, `Flux.just("A", "B")` instantaneously emits A and B, but if you chain `.delaySequence(Duration.ofSeconds(1))`, the resulting `Flux` will do nothing for 1 second _then_ instantaneously emit A and B.

5. scheduler : deff between single vs newSingle (elastic vs newElastic, ....) 
`single()`/`elastic()`/.. are default instances of each flavor of `Scheduler`. Some operators will use these if you don't provide a specific `Scheduler` yourself. Each flavor has a corresponding `newXXX()` method in `Schedulers` that creates a standalone instance that you will own from there on (eg. you'll need to think about disposing it with `.dispose()`)

**Comment by rebai-halim** [comment]
thanks so math

**Comment by rebai-halim** [comment]
for my question 1 & 2 : 

1. can you give some code to explain deff bentween map && concatMap 

2. i process a sequence of integer with flux , if there is some excepetion in element (2) && element (3) , i want to continue processing of sequence and finally (delay exception processing at last) i processing these exceptions, i see there is an operator concatMapDelayError how can use it ??

thanks for all

**Comment by simonbasle** [comment]
your second question is a pretty advanced topic, as in Reactive Streams the first element that triggers an error terminates that particular sequence (the `onError` signal). Operators like `onErrorResume` simply piggyback on said `onError` signal and replace it with a brand new sequence, a fallback. I encourage you to raise that question on the Gitter channel.

Here is a snippet that illustrates the diff between `map` and `concatMap`:

```java
Flux<Integer> source = Flux.range(1, 3);

Flux<?> example1 = source.map(i -> "element #" + i);
Flux<?> example2 = source.map(i -> Flux.just("A" + i, "B" + i));
Flux<?> example3 = source.concatMap(i -> Flux.just("A" + i, "B" + i));
```

What is the correct generic type for the example variables above, and what do they emit when subscribed to? Here:
```java
Flux<String> example1; //emits "element #1", "element #2", "element #3"
Flux<Flux<String>> example2; // emits 3 instances of `Flux`, that by themselves do nothing
Flux<String> example3; //emits "A1", "B1", "A2", "B2", "A3", "B3"
```

**Comment by rebai-halim** [comment]
salut et meri beoucoup Mr Simon Baslé

donc si je comprent bien votre demo, concatMap elle prent un element de flux et Elle transform en flux de maniere asynchrone et prend sa value comme resultat de retour quand ce flux est terminer , est ce que mon raisonement est just ???  

j'ai 2 question c possible : 

a. quelle l'effet de la methode static defer ?? je vois pas la deff entre 'defre' et 'fromSupplier' coté flux  ?? ci possible un demo (simple code) motre l'effet de cette methode et les cas d'utilisation

b.  pendant le traitement (execution des operatuers) du flux , il arrive que des erreur on exception apparaisse , docn ma question est : comme continue l'execution du flux et traiter les erreurs quand ce flux est terminer

merci beucoup de votre patience et pour votre temps

**Comment by simonbasle** [comment]
Can't continuously answer different entry-level questions in GitHub issues, please head out to https://gitter.im/reactor/reactor where the community can also chime in and help you.
