### ISSUE TITLE
There is always a delay at the first signal when using Flux::interval

### ISSUE THREAD

**Issue by stavalfi** [reactor/reactor-core#1153]
There is always a delay at the first signal when using `interval`. No matter how much `Duration.ofMillis` it will be. I understand that no one can guarantee a 100% precision but this delay is too big and happens only at the first signal.

```java
static long start = System.currentTimeMillis();

private static void checkTime() {
    Flux.interval(Duration.ofMillis(100))
            .doOnNext(number -> {
                long now = System.currentTimeMillis();
                long duration = now - start;
                System.out.println(duration);
                start = now;
            }).take(10).subscribe();
}
```

### Expected behavior
```java
100
100
100
100
100
100
100
100
100
100
```
### Actual behavior
```java
239
100
100
100
100
100
100
100
100
100
```
### Reactor Core version
`Bismuth-SR7`
### JVM version (e.g. `java -version`)
`1.8`

**Comment by simonbasle** [comment]
This big delay is because you measure the time between the classloading (static initialization of `start`) and the first emission. What you should strive to measure for the first round is the time between **subscription** to the `Flux` and the first emission.

Such a test could achieve that:

```java
@Test
	public void firstDelay() {
	    final AtomicLong start = new AtomicLong(0);

	    StepVerifier.create(
			    Flux.interval(Duration.ofMillis(100))
			        .doOnSubscribe(sub -> start.set(System.currentTimeMillis()))
			        .map(number -> {
				        long now = System.currentTimeMillis();
				        long duration = now - start.getAndSet(now);
				        return duration;
			        })
			        .take(10)
			        .collectList()
	    )
	                .assertNext(times -> assertThat(times)
			                .hasSize(10)
			                .allSatisfy(l -> assertThat(l)
					                .isCloseTo(100L, Offset.offset(15L))))
	                .verifyComplete();
    }
```

(note that there is still a small delay at the subscription, probably due to the creation of the worker thread for the interval, but it is within 15ms now)
