### ISSUE TITLE
bufferUntil doesn't emit last buffer

### ISSUE THREAD

**Issue by rsltrifork** [reactor/reactor-core#1166]
### Expected behavior
> On completion, if the latest buffer is non-empty and has not been closed it is emitted.

https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#bufferUntil-java.util.function.Predicate-

### Actual behavior
The buffer is never emitted.

### Steps to reproduce
        Flux.
                from(subscriber -> {
                    subscriber.onNext("hello world!");
                    subscriber.onComplete();
                }).
                bufferUntil(String -> false).
                subscribe(System.out::println);

### Reactor Core version
3.1.6

### JVM version (e.g. `java -version`)
openjdk 1.8.0_161

**Comment by OlegDokuka** [comment]
Hi @rsltrifork! Your example is incorrect since the implementation of given`Publusher` violet the [Reactive Stream Specification](https://github.com/reactive-streams/reactive-streams-jvm/#1-publisher-code). Once your publisher has been compliant with Specification, then expected behavior will be achieved. 

in turn, if you try -> 
```java
Flux.just(1)
       .bufferUntil(String -> false)
       .subscribe(System.out::println);
```
you will see that everything is fine

**Comment by rsltrifork** [comment]
Thank you. I found that this also works:

>         Flux.
>                 create(emitter -> {
>                     emitter.next("hello world!");
>                     emitter.complete();
>                 }).
>                 bufferUntil(String -> false).
>                 subscribe(System.out::println);
