### ISSUE TITLE
Question about Share() 

### ISSUE THREAD

**Issue by halimpuckjava** [reactor/reactor-core#1193]
hi, 
1.  Flux<Integer> flux= Flux.just(1,2,3);
flux.subscribe(System.out::println) -> 1,2,3 (first subscribe)
flux.subscribe(System.out::println) -> 1,2,3 (second subscribe)
  Flux<Integer> shareFlux= Flux.just(1,2,3).share();
  shareFlux.subscribe(System.out::println) -> 1,2,3 (first subscribe)
  shareFlux.subscribe(System.out::println) -> 1,2,3 (second subscribe)

the same output for both flux & shareFlux !! so how share() operator work and in wich cases use it and how ???

2. ConnectableFlux<Integer> connectableFlux = Flux.range(1,3).publish();
        connectableFlux.subscribe(System.out::println); -> 1,2,3
        connectableFlux.connect();
        connectableFlux.subscribe(System.out::println); -> not think !!!
but why the second subscribe don't see any thing in output ???

3. how to make publiser open in real-time to add or insert data (so all subscribes to this publisher receive any new data in real-time when updated this publisher)

**Comment by smaldini** [comment]
Your problem here is that it's synchronous pub-sub. `Share()` which is `publish().refcount(1)` will resubscribe when the previous subscription is fully terminated. `RefCount(1)` means to recycle the subscription when at least one subscriber is subscribed.

In your case you have the following happening:
```
//1 flux refCount 0
flux.subscribe(System.out::println) -> 1,2,3 (first subscribe) //new subscription refCount 1 then 0
flux.subscribe(System.out::println) -> 1,2,3 (first subscribe) //new subscription refCount 1 then 0
```

Then to come back to your last question you have multiple options, by [programmatically creating the sequence](http://projectreactor.io/docs/core/snapshot/reference/#producing) or by using a [Processor](http://projectreactor.io/docs/core/snapshot/reference/#processors).

**Comment by smaldini** [comment]
Closing for now but don't hesitate to open a new issue or suggest some documentations change for the javadoc if you thing it can be better 👍
