### ISSUE TITLE
flux share

### ISSUE THREAD

**Issue by azmym** [reactor/reactor-core#1219]
I am building a service using Project Reactor 3.0 and I wanna share the flux across different operation,
I found on documentation share function but not clear hoe can use it 
```
final Flux<Message<String>> share = message.share();

final Flux<Object> branch1 = share.filter(//code).map(//code);
final Flux<Object> branch2 = share.map(//code);

branch1.subscribe();
branch2.subscribe();
```
flux not consume messaging , what is missing to consume the messages and how order the subscription

**Comment by simonbasle** [comment]
1) You need to define what to do with the final form of data by providing at least a value handler to `subscribe(...)`
2) If you call that code from a test, the test could exit before said handler had a chance to be called, since everything is asynchronous... Look into `StepVerifier` from `reactor-test` in that case.
