### ISSUE TITLE
FluxEmpty does not throw NoSuchElementException

### ISSUE THREAD

**Issue by Danny02** [reactor/reactor-core#1226]
### Expected behavior
The JavaDoc of Flux#last states:
> [...] or emit NoSuchElementException error if the source was empty

### Steps to reproduce
    Flux.empty().last().block()

    Flux.fromIterable(List.of()).block()

### Actual behavior
The first line does not throw an Exception and returns `null`. The second example throws a NoSuchElementException.

### Reactor Core version
3.1.6

### JVM version (e.g. `java -version`)
9.0.4

**Comment by simonbasle** [comment]
Thanks, indeed this is due to an overeager optimization that detect the `Flux.empty()` is a form of `Callable` and converts it to a `Mono` in a generic way, forgetting about the `NoSuchElementException`-on-empty aspect.

If you turn it into a `Flux.empty().hide()` it works as expected.

I'll prepare a fix for the 3.2.0 line

**Comment by simonbasle** [comment]
Note: I wonder if we should try to fix it in the 3.1.x line as well, people may have come to rely on this behavior so a fix during a maintenance release is maybe not ideal 🤔

**Comment by smaldini** [comment]
@simonbasle i think it should go to 3.1 too.
