### ISSUE TITLE
Make the predefined `Flux#collect*()` utilities collect into immutable types by default?

### ISSUE THREAD

**Issue by sp00m** [reactor/reactor-core#1297]
I was surprised to see `Flux#collectList()` collecting into a mutable type (unless I misread the code). What was the reason behind this choice?

I would have expected to receive an immutable list by default, that people can make mutable if needed (e.g. `.map(ArrayList::new)`). Currently, I need to explicitly make it immutable instead (e.g. `.map(Collections::unmodifiableList)`).

Modifying the existing `collectList` method isn't probably doable now unfortunately, as it could break backward compatibility, but what about adding `collectImmutableList` instead? This applies to the other collecting predefined methods as well.

### Reactor Core version

3.1.8.RELEASE

### JVM version (e.g. `java -version`)

1.8.0_112

**Comment by simonbasle** [comment]
What makes you think the majority of people have the same expectation of an immutable list by default? Especially in Java where immutable collections are the outliers rather than the norm, this would violate the principle of least surprise for a lot of developers.

Let's spin around your argument to demonstrate how there is no intrinsically incorrect way of doing things:

> I was surprised to see `Flux#collectList()` collecting into an immutable type (unless I misread the code). What was the reason behind this choice?
> 
> I would have expected to receive a mutable list by default, that people can make immutable if needed (e.g. `.map(Collections::unmodifiableList)`). Currently, I need to explicitly make it mutable instead (e.g. `.map(ArrayList::new)`)

Having a mutable list is going to resonate better with the experience of most Java devs with collections and is what the operator needs to progressively add elements into the collection as they become available, with 0 copying of the collection. By definition in a `Flux<T>` elements can come at different times, yet by the specification there will be no concurrency problems since `onNext` MUST not be invoked in parallel.

Furthermore, the list only gets emitted to the user once the sequence has completed, guaranteeing that it won't get further mutate by the operator, and handing over the ownership of the `List` to the user.

**Comment by akarnokd** [comment]
I completely agree with Simon here. Besides, you can always collect into a custom container via [collect](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#collect-java.util.function.Supplier-java.util.function.BiConsumer-).

**Comment by sp00m** [comment]
> This would violate the principle of least surprise for a lot of developers.

That's actually very true, and is a fair explanation of this choice (I would personally have explicitly named it `toMutableList` though). I think I got used to immutable-by-default without noticing that it's a quite opinionated approach, at least in the Java world. And yeah, Java's `List` provides a mutable contract anyway...

Anyway, thanks for the quick answer, keep up the great work!
