### ISSUE TITLE
Why Mono without `public final <V> Mono<V> then(Publisher<V> other)` instance method?

### ISSUE THREAD

**Issue by rj-hwang** [reactor/reactor-core#1312]
Using Kotlin language.

### Expected behavior

    verifySomthing()
      .then { getIt(id) }  // foucus here, now reactor not support
      .subscribe()

### Actual behavior

    verifySomthing()
      // need to wrap get(id) to avoid invoke getIt(id) if verifySomthing() return Mono.error(MyException())
      .then( Mono.just(0).flatMap { getIt(id) } ) 
      .subscribe()

### Reactor Core version

3.1.6.RELEASE

### My Description

I'm confuse why Mono class without `public final <V> Mono<V> then(Publisher<V> other)` instance method? thenEmpty and thenMany method also have it：

    public final Mono<Void> thenEmpty(Publisher<Void> other)
    public final <V> Flux<V> thenMany(Publisher<V> other)

**Comment by simonbasle** [comment]
`Mono` doesn't have a `then(Publisher<V>)` because:
 - `then(...)` has been defined as returning the same type as the caller (ie. `Mono#then` returns a `Mono`, `Flux#then` returns a `Flux`)
 - BUT a `Publisher<V>` is not guaranteed to have `Mono` semantics (it could have more than one element

Thus `Mono#then(Publisher<V>)` couldn't guarantee that the returned publisher be a `Mono`, so it was implemented as `Mono<V> then(Mono<V> other)`

**Comment by simonbasle** [comment]
@rj-hwang use `thenMany` if `getId` returns a `Publisher`, or have it return a `Mono`.
