### ISSUE TITLE
Release dropped elements on collectList cancel/error

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#1342]
The `onDiscard` hook added as part of #999 provides access to dropped data in case of an error or cancel signal but it looks like it doesn't cover cancellation everywhere, e.g. `collectList`.

A specific example of this could be making calls to remote HTTP services through the Spring Framework `WebClient` and zipping the results together. The codecs use `DataBufferUtils#join` which relies on `collectList` to aggregate data in some cases. So if one remote call errors or completes empty, others would be cancelled too potentially with in-flight data dropped. Other related examples could be based on timeout and retry.

**Comment by simonbasle** [comment]
@rstoyanchev most operators supporting the onDiscard hook take the cancellation into account. `collectList` was not part of this set of supporting operators, but can be modified to "discard" the *content* of the accumulated `List` (precisely because the operator's implementation enforces the `List` type). _(editing the issue's title accordingly)_

On a related note, `collectMap` is based on the more generic `collect`, which doesn't enforce anything about the "container", so for both of these operators it would be trickier to implement onDiscard support 😢
