### ISSUE TITLE
StrictSubscriber Context Should Return Errors on Get

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-core#1371]
Per our discussions at SpringOne (breakfast, plane) the current behavior of losing context silently isn't really viable as we start doing more complex things with `SubscriberContext` (security, transactions, tracing).

The current suggestion is that `StrictSubscriber` (`Operators.toCoreSubscriber(Subscriber)`) return an implementation of `Context` (allows most code to continue running without problems) but have that `Context` return an error if any of the getters is called (identifying lost context).

**Comment by simonbasle** [comment]
This will need a change in the RxJava2 adapter in https://github.com/reactor/reactor-addons as well.

**Comment by simonbasle** [comment]
The JDK8 `Flow` adapter should also return such a `Context` when performing `publisherToFlowPublisher`.

**Comment by simonbasle** [comment]
@smaldini @sbuettner do you think this feature should have an opt-out escape hatch in the form of eg. a system property replacing the always throwing `Context.unsupported()` with a `Context.empty()`? To avoid too much disruption in a minor release.

**Comment by nebhale** [comment]
An escape hatch in a micro (3.2.x) release perhaps, but given that Spring and Spring Security are both building significant, application-critical features (authz, transactions) on top of this behavior, I think the next minor (3.3) should have this be a hard failure.  My recommendation would be big ugly warning in the 3.2.x line with an option to make it an error and upgrade to hard error in 3.3 with an option to make it a warning.  And of course, communicate that migration really loudly in the community.

**Comment by simonbasle** [comment]
@nebhale yes sorry I meant escape hatch in the micro-release

**Comment by bsideup** [comment]
After some consideration, given that we have [the context loss detection](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Hooks.html#enableContextLossTracking--) now, we've made a decision to not change the default context returned by `StrictSubscriber` and friends.

The reason is behind the following problem:
If we make it throw in every read operation than a lot of existing code that was using something like `getOrDefault` would start failing (including Reactor's own code like getting the discard hooks). We may throw only from `get`, but then it would fail anyways due to missing value in the empty `Context` returned by `StrictSubscriber`. The error will be misleading a bit, but that's why we have the context loss detection now.
