### ISSUE TITLE
Is it possible to implement your own OverflowStrategy?

### ISSUE THREAD

**Issue by ealexhaywood** [reactor/reactor-core#1391]
Is it possible to implement your own `OverflowStrategy`?  At first glance, this doesn't seem possible.  While it is for a `Subscriber`, it would be really nice to do the same for a `Publisher`.  Any plans to add this capability in a future release?

Basically, I have a scenario where I have a downstream that isn't able to process as fast as the upstream is creating, and I ultimately run out of memory using the `BUFFER` strategy.  And I also can't afford to drop data or error out, as the data is very precious.  We can advise consumers to implement their own back pressure mechanism, but that's something we want to avoid mandating on others if we can help it.

**Comment by simonbasle** [comment]
It is not possible to implement a custom `OverflowStrategy`, but I think this is more a problem of correctly shaping up the subscriber-to-publisher request. Unless your `Publisher` is misbehaving and produces more data that it gets requested for?

Instead of `.onBackpressureBuffer()`, have you tried `limitRate`? something like `limitRate(256)` to only request by "batches" of 256 items from the source?
Or even an explicit `.buffer(256)` combined with a subscriber that requests `List<Item>` one by one and processes them in a more batched way?
