### ISSUE TITLE
TopicProcessor (Critical): onNext makes out of RingBuffer capacity after some time without subscribers

### ISSUE THREAD

**Issue by mayras** [reactor/reactor-core#1422]
Make TopicProcessor with size of RingBuffer equals 1024 and start to call topicProcessor.onNext without subscribers, when RingBuffer will be full try to subscribe to topicProcessor and you will get nothing. It's not normal behaviour, (RingBuffer.Sequence minimum) must follow to cursor of RingBuffer to avoid such situations. Next code of TopicProcessor makes problem (from line 314) when it starts from minimum which is -1 when first subscriber comes:

		//bind eventProcessor sequence to observe the ringBuffer

		//if only active subscriber, replay missed data
		if (incrementSubscribers()) {

			signalProcessor.sequence.set(minimum.getAsLong());
			ringBuffer.addGatingSequence(signalProcessor.sequence);
			//set eventProcessor sequence to minimum index (replay)
		}
 

### Reactor Core version
3.2.2.RELEASE
### JVM version (e.g. `java -version`)
1.8.0_171

**Comment by smaldini** [comment]
Can you open an issue on https://github.com/reactor/reactor-addons/issues if that is still a problem. We are moving to reactor-extra event-loop based TopicProcessor and WorkQueueProcessor.
Separately this needs a rework of the processor API to be notified when data would be dropped (e.g. with a tryOnNext) and behavior change since it means we would be dropping oldest onNext

**Comment by mayras** [comment]
opened
