### ISSUE TITLE
Need reactor.core.publisher.Hooks documentation clarification

### ISSUE THREAD

**Issue by nikita-clearscale** [reactor/reactor-core#1439]
There is a class `reactor.core.publisher.Hooks` which is used for cross-cutting behavior on Mono/Flux. But it is very unclear - how this class works.

Here list unclear moments:

1. Everybody telling that there is no `ThreadLocal` on Flux, but `reactor.core.publisher.Hooks` contains **static** methods for Mono/Flux intercepting. Looks very strage. Could you please add explanation how and when hooks from `reactor.core.publisher.Hooks` "transfered" to Mono/Flux method calls?
1. `reactor.core.publisher.Hooks` contains method `onOperatorDebug` which should not be used in production due to performance impact. Is it true for other methods? For example if I add simple do nothing intercepter will it decrease performance as much as `onOperatorDebug` or not?

It would be the best if you provide short anwser here and add full explanation to documentation/javadoc

**Comment by simonbasle** [comment]
hi @nikita-clearscale 

The way hooks are applied depend on each hook, but it boils down to two categories:
 1. hooks applied when the operator is instantiated (these are more or less `Functions`)
 2. hooks applied as part of the operator processing its signals (these are more or less `Consumers`)

For 1., the hooks are applied when calling the `Flux`/`Mono` APIs. For instance, when you call `myFlux.map(a -> a)`, internally `map` calls `onAssembly(new FluxMap(...))`. This `onAssembly` step detects if there have been relevant hooks configured and applies them, wrapping the operator instance, to the effect of injecting custom intermediate operators.

For 2., the hooks are applied by each operator's implementation at the relevant times. For instance, `onNextDropped` is a `Consumer` applied whenever an operator receives an `onNext` AFTER having received an `onComplete/onError` terminal signal (a protocol error). So each Reactor operator checks if the hook is set up whenever that happens, and calls the hook with the extraneous element.

Adding an identity function as a cat 1 hook will NOT decrease performance. `onOperatorDebug()` has a performance impact because:
 - it injects an intermediate step to *every single operator in the app*
 - that intermediate steps consists in instantiating an `Exception` to capture the stack trace, which is used as additional information whenever the wrapped operator fails (it points to where the operator was instantiated rather than where it was subscribed to)

**Comment by nikita-clearscale** [comment]
Many thanks for quick reply!
