### ISSUE TITLE
Converting from RxJava1 Observable to Mono causes doOnTerminate to not trigger

### ISSUE THREAD

**Issue by programmatix** [reactor/reactor-core#1457]
Using reactor-core 3.2.1 and rxjava-reactive-streams 1.2.1, I get this behaviour:

    Observable<Integer> obs = Observable.just(1)
                .doOnTerminate(() -> System.out.println("Observable terminated"));

        // This prints "Observable terminated"
        obs.toBlocking().single();

        Mono<Integer> mono = Mono.from(RxReactiveStreams.toPublisher(obs));

        // This does not
        mono.block();

The Observable has completed successfully and so I'd expect doOnTerminate to trigger in both cases.

The problem seems to be because `MonoNext.NextSubscriber.onNext` calls `s.cancel` before completing it:

    s.cancel();
    actual.onNext(t);
    onComplete();

and cancelling an Observable causes its doOnTerminate to not be called.

**Comment by simonbasle** [comment]
Since a `Publisher` can emit more than one value, `Mono.from(Publisher)` cannot assume anything about the `Publisher` and thus will always cancel it upon receiving a single value.

However, if **you** can safely guarantee that the `Publisher` follows `Mono` semantics (at most one item), then you can remove the safety belt and use `Mono.fromDirect` instead.
