### ISSUE TITLE
Mono<Void>.map is not ran

### ISSUE THREAD

**Issue by blackheaven** [reactor/reactor-core#1467]
### Expected behavior
`Mono<Void>.map` works as any `Mono<A>.map`

### Actual behavior
`Mono<Void>.map` does not apply the given function.

### Steps to reproduce
```
        Mono<Integer> step = Mono.fromFuture(CompletableFuture.completedFuture(42));
        Mono<Void> voidMono = step.then();
        Function<Void, ?> failC = voidValue -> { throw new RuntimeException("I run"); };
        assertThatCode(() -> voidMono.map(failC).block()).doesNotThrowAnyException(); // Should fail
```

### Reactor Core version
3.1.0-RELEASE

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_191"

### Goal
My goal is to execute an other `Mono`, *only if* the first one is not empty (contrary to `then`, which run the second one unconditionally).

**Comment by simonbasle** [comment]
And what would an instance of `Void` be? 🤔

A `Mono<Void>` by essence never emits an `onNext`. `map` transforms an instance passed through `onNext`, so if there are no instance, there is nothing to invoke the mapper on.

What you are after is simply `flatMap` instead of `then().map()`. Same as `map`, it only triggers if there is a value, but it maps into another `Mono` in that case.
