### ISSUE TITLE
Subscriber to multiple publishers

### ISSUE THREAD

**Issue by ofekIsrael** [reactor/reactor-core#1490]
Hi
When I try to subscribe a subscriber to two publisher with same subscriber, I get a cancel. 
I don't understand why it is wrong and I can't do that.
Anyway I expected to get some information about it from the  reference guide to tell me this is forbidden and the reason why.
In addition if the scenario was detected as second subscription why there is no clear message about it with the cancel message ?

I'm using Spring WebFlux with Reactor 3.2.3

**Comment by simonbasle** [comment]
This is done in order to maintain guarantees that a `Subscriber`'s `onNext` method are not called in parallel (which the Reactive Streams specification mandates), without needing external synchronization between multiple producers. This restriction is embodied in rule 2.5 of the [Reactive Streams specification](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.2/README.md#2-subscriber-code).

I'm assuming you're using `BaseSubscriber`? Perhaps the javadoc and/or reference documentation could be improved in that regard... (eg. in the [`BaseSubscriber` section of the reference guide](https://projectreactor.io/docs/core/release/reference/#_alternative_to_lambdas_basesubscriber))

**Comment by simonbasle** [comment]
You should probably make your particular flavor of `BaseSubscriber` as a child class, and then instantiate 2 instances (one for each DB).

It is not possible to provide context as to why a `Subscription` has been cancelled, it simply receives a `cancel()` signal (this is NOT an `Exception`-based mechanism).

**Comment by ofekIsrael** [comment]
> You should probably make your particular flavor of `BaseSubscriber` as a child class, and then instantiate 2 instances (one for each DB).

or doing something like that:
.subscribe(v->original.onNext(v), e->original.onError(e))

or 
create a general wrapper that extends baseSubscriber and contains subscriber 
and forward the message to the original 

.subscribe(new wrapper(original))

**Comment by simonbasle** [comment]
...and now you have a concurrency issue. So you'll need to take care about shared state and thread safety in the `original`/`wrapper` yourself, all guarantees provided by the library are off by then.
