### ISSUE TITLE
Mono/Flux#doOnEach never emits the onSubscribe Signal

### ISSUE THREAD

**Issue by dylmeadows** [reactor/reactor-core#1526]
### Expected behavior
`doOnEach(Consumer<Signal<T>>)` should be accepted with an onSubscribe `Signal<T>` when the subscription occurs for a `Mono`/`Flux`.

### Actual behavior
`doOnEach(Consumer<Signal<T>>)` is never accepted with an onSubscribe `Signal<T>`.

### Steps to reproduce
```
Consumer<Signal<String>> mockConsumer = Mockito.mock(Consumer.class);
Mono<String> monoUnderTest = Mono.just("abc")
    .doOnEach(signal -> {
        if (signal.isOnSubscribe()) {
            mockConsumer.accept(signal);
    }});
StepVerifier.create(monoUnderTest)
    .expectSubscription()
    .expectNext("abc")
    .verifyComplete();
Mockito.verify(mockConsumer, VerificationModeFactory.times(1))
    .accept(ArgumentMatchers.any());
```

### Reactor Core version
3.2.6.RELEASE

### JVM version (e.g. `java -version`)
`java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)`

**Comment by ssko1** [comment]
Is there a decision on whether or when this is going to be fixed? Is this a candidate for open source contribution?

**Comment by simonbasle** [comment]
The problem with this one is that people might currently rely on the fact that only onNext, onComplete and onError are exposed. Take this code:

```java
Mono.just("example")
    .doOnEach(sig -> {
        if (sig.isComplete()) LOGGER.info("completed");
        else if (sig.isError()) LOGGER.error("failed", sig.getThrowable());
        else LOGGER.info("received " + sig.get());
     });
```
With the introduction of `onSubscribe`, the above code would break. Is that feature desirable enough to break such uses?

**Comment by ssko1** [comment]
That makes sense, thank you for the reply.

I was coming from the perspective of logging with a loggable context object stored in the reactor context. 

Suppose that I want to produce logs that surround a service request with some request context (tid, user-agent, etc). Without `isOnSubscribe`, I would have to extract the context and wrap my service call in a `flatMap` so that I have access to the context when I need it. I would also need to add an additional `doOnSubscribe` operator:

```java
Mono.subscriberContext()
    .map(context -> context.get(MyContext.class))
    .flatMap(myContext -> {
        return callService()
            .doOnSubscribe(sub -> log.info("start", myContext))
            .doOnEach(signal -> {
                if(signal.isOnComplete()) {
                    ClientResponse r = signal.get();
                    if(r != null) log.info("end", myContext);
                    else log.info("end", myContext, r.statusCode());
                }
            });
    })
    .subscriberContext(context -> context.put(MyContext.class, createMyContext()))
```

The code above can be cleaner if I used `doOnError` and `doOnNext` operators, but fetching the subscriber context remains the same.

I found that `doOnEach` is the only operator that provides the context, and the code below that uses `isOnSubscribe` is a lot cleaner:
```java
return callService()
    .doOnEach(signal -> {
       MyContext c = signal.getContext().get(MyContext.class);
       if(signal.isOnSubscribe()) log.info("start", c);
       else if(signal.isOnNext()) log.info("end", c);
       else log.info("end");
    })
    .subscriberContext(context -> context.put(MyContext.class, createMyContext()))
```

I am perfectly fine implementing the first example, especially if this could potentially affect a large number of software using `doOnEach`. 

Perhaps this might be an issue with how we obtain the `Context` object. I almost feel *too* restricted when trying to access the context (only three such ways available):

* `Mono#subscriberContext`
* `Mono#deferWithContext`
* `Mono#doOnEach`

It is never there when I need it in the middle of a Mono sequence, but when I do, I have to retroactively add it using one of the static methods. Everywhere I need the context has the multi-nested `map`/`flatMap` sequence as seen in my first example.

Would additional Mono operators that provide access to the context help here? Or does `doOnEach` effectively solve for all context retrieval problems?

**Comment by simonbasle** [comment]
for a while we wondered if a `materializeContext()` operator would make things easier in some cases, but that would only facilitate the `onNext` case (basically, each `onNext` element would be coupled with the `Context` in a `Tuple2<Context, T>` on the data path).

getting the `Context` right at subscription is indeed more involved, ie. the `flatMap` pattern above 🤔

**Comment by simonbasle** [comment]
That said, `deferredWithContext` is probably more adapted here:

```java
return Mono.deferWithContext(ctx -> {
    final MyContext c = signal.getContext().get(MyContext.class);
    //we're already in the "subscribe" phase so we can log directly here
    log.info("start", c);
    return callService()
        .doOnNext(v -> log.info("got " + v, c))
        .doFinally(f -> log.info("end of type " + f, c));
    })
    .subscriberContext(context -> context.put(MyContext.class, createMyContext()));
```

**Comment by ssko1** [comment]
Would `BiConsumer<? super T, Context>` for `do*` methods be beneficial for when users want to easily access the context in the middle of a sequence?

**Comment by simonbasle** [comment]
That would introduce too many overloads in my opinion. maybe adding the `onSubscribe` signal in 3.4.0 (the next major release, since versioning scheme is GEN.MAJOR.MINOR) would be acceptable?

**Comment by ssko1** [comment]
I think that is a pretty good solution. Thank you!

**Comment by simonbasle** [comment]
After further consideration, adding such a method just to make the `Context` accessible is probably not the best course of action.

Instead, `Flux.deferWithContext` and the upcoming `transformWithContext` operator (see #2280) should help achieve the same result in a better way.
