### ISSUE TITLE
Consider allowing pluggable metrics implementations

### ISSUE THREAD

**Issue by mgodave** [reactor/reactor-core#1540]
I'd like to feed my metrics directly into opencensus. It seems that the current mechanism only supports micrometer but that this could be extended to allow for any metrics library (micrometer, dropwizard, opencensus). I will probably try to take a stab at an implementation of this when I can find some time. Curious to get some feedback on the idea.

**Comment by bsideup** [comment]
Hi @mgodave,

MicroMeter is supposed to be a metrics facade and do to metrics what SLF4j is doing to logging.  
Therefore, you should be able to implement a backend for MicroMeter based on opencensus.

Otherwise, we will have to implement our own facade in Reactor to communicate with different metrics libraries, and this is exactly what MicroMeter should provide to us.

**Comment by mgodave** [comment]
@bishop gotcha! Thanks, I hadn't dug in too much but this is some great clarification.
