### ISSUE TITLE
groupBy and then filter by the size of a group is hanging

### ISSUE THREAD

**Issue by newmen** [reactor/reactor-core#1544]
Hello.

I know that my question isn't new, and there are similar issues like #931, #596 or mb #726.
But, I still can't understand how to work with `groupBy`, even after I read the java-doc several times. Maybe it because I have a lot of experience to use `groupBy` in other languages like clojure, ruby, python. And I've tried to use the reactor for this issue too if java8 doesn't provide so useful `groupBy` from the box.

### Expected behavior

My use case is pretty easy:

```java
LocalDate startDate = LocalDate.parse("2019-02-27");
LocalDate newYearDate = LocalDate.parse("2020-01-01");
List<LocalDate> dates = Flux.fromStream(Stream.iterate(0, x -> x + 1))
        .map(x -> x * 2)
        .map(startDate::plusWeeks)
        .takeWhile(newYearDate::isAfter)
        .groupBy(LocalDate::getMonth)
        .filter(group -> group.count().map(n -> n > 2).block())  // hang here in lambda...
        .flatMap(Function.identity())
        .collectList()
        .log()
        .block();

System.out.println(dates);
```

I have a date (`startDate`) and generate a sequence of events every two weeks from this date.
I need to find all three events in one month this year. I've limited the initial sequence of dates by this year to prevent possible infinitive waiting for new data to do `groupBy` and then `block` in the end.

### Actual behavior

The execution is hanging in the filter.

### How I tried to solve it?

I tried to use `.publishOn(Schedulers.single())` before `.groupBy` and before `.flatMap`, to prevent concurrency issues related to other issues linked above. But it doesn't work.

I tried to set the `concurrency` in `.flatMap` as a second argument, but it didn't help too.

I tried to insert some `Duration` to the `.block` in lambda where the execution is hanging, but in this case, I got a timeout exception.

Just one case works fine for me. When I change the `Flux` to java `Stream` by `.toStream`, after `.groupBy`. It looks ugly but works, and I haven't an answer why it doesn't work without `.toStream` when my colleagues ask me.

### Reactor Core version

3.1.0-RELEASE

### JVM version (e.g. `java -version`)

jdk1.8.0_191.jdk

**Comment by simonbasle** [comment]
Although with `groupBy` one of the first things to check is the number of groups that can be opened, here it is not an issue due to your `takeWhile`, as you have 22 weeks, and thus even less groups.

The real issue is the `block()` inside the `filter`. That is a huge code smell. In the present case, none of the operators work on a specific `Scheduler` so they end up all working on the same thread. `block`ing in the middle just locks the thread without hope of progress for `groupBy` (it waits for the group to be closed, but in order to do that the generator must be invoked, which is prevented by the thread being blocked).

2 possible solutions:

1. `publishOn(Schedulers.elastic())` right after the `groupBy`: this ensures the `block` doesn't prevent the source from making progress, but is still ugly
2. use asynchronous filter and caching: 
```java
		    .groupBy(LocalDate::getMonth)
		    .map(Flux::cache)
		    .filterWhen(group -> group.count().map(n -> n > 2))
```

The later manages to get rid of the ugly `block()` inside the reactive chain of operators, but it needs an intermediate `.map(Flux::cache)`. That is because a `FluxGroup` only allows 1 `Subscriber`, and here you have 2: the `filterWhen` and the `flatMap`.
