### ISSUE TITLE
Detect shading and use the common ForkJoinPool in case of

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1655]
To avoid doubling the number of threads when reactor-core is shaded, we could detect it and instead of creating our own pool in `Schedulers.parallel()` we will return a `Scheduler` wrapper around `ForkJoinPool.common()` based on [ForkJoinPoolScheduler from reactor-extra](https://github.com/reactor/reactor-addons/blob/master/reactor-extra/src/main/java/reactor/scheduler/forkjoin/ForkJoinPoolScheduler.java)

**Comment by osi** [comment]
(as full disclosure, i contributed the initial implementation of the FJP-based Scheduler)

I'm in favor of this (for the parallel scheduler) and think the FJP would be a better default too. 

For long-lived flows (ie, event processing systems), the current implementation binds a `Scheduler.Worker` to a single thread. This leads to a "noisy neighbor" style problem where work can be unevenly distributed across the threads in the parallel pool due to no work stealing. 

*if* the default parallel scheduler was utilized the default FJP, then there wouldn't be a need to detect shading at all

**Comment by smaldini** [comment]
The problem in that case is that we lose the opportunity to tag the thread with our custom thread factory (NonBlocking marker. We also lose the naming and isolation of the scheduler threads which might be a good or bad thing. The primary default use of Scheduler is timed operators, so we will see those running in this FJP and they are very sensitive to blocking, we can probably adapt our detection for this case tho in `Schedulers.isInNonBlockingThread()`.
Then if the problem is using a scheduler with publishOn or subscribeOn, its easy for users to pass anything they want (and manage it outside, e.g. as a Spring Bean). I however agree that FJP could be a core option tho via a new factory (and we could deprecate single() to leave some room).

**Comment by simonbasle** [comment]
I'd prefer to offer some guidance to library authors that decide to shade Reactor, in order for them to forward that guidance to their own users. Shading isn't a light decision to make, but at least it doesn't change visibility, so they would still be able to do `shaded.Schedulers.setFactory` that installs custom-written `ShadedSchedulerAdapter`.
