### ISSUE TITLE
add infinite retryWithBackoff variant

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1663]
Currently using Integer.MAX_VALUE as `numRetries` argument doesn't work as it is decremented as any other num retries. We should support this and/or eventually add a a simple retryBackoff(Duration) argument.

**Comment by simonbasle** [comment]
Realistically, using `Long.MAX_VALUE` should be enough, unless I'm missing something. The fastest possible backoff delay will exhaust the `Long.MAX_VALUE` "infinite" retries in... roughly **292 million years**! (see analysis below)

So I think we're good... 😜

The only combination that would differ from that is "infinite numRetries with ZERO backoff", but that boils down to `retry()`.

Maybe that was what you had in mind @smaldini? Make `retryBackoff(Long.MAX_VALUE, Duration.ZERO, Duration.ZERO, 0.0d)` an alias for `retry()`?


<details>
<summary>Why 292 million years?</summary>
Currently the lowest resolution for `Mono.delay` (which drives the backoff) is at best 1ms, provided the OS can even match that precision. Any `Duration` under that precision will be rounded down to 0 MILLIS, so most schedulers will consider that a direct task execution.

(note the actual precision in `retryBackoff` has to be worse than that, since there is the overhead of resubscribing)

Even if the precision was down to the NANOSECOND, with a max backoff of 1 nanosecond and `numRetries == Long.MAX_VALUE`, it would still take 292 **years** for the backoff to reach the _Retries exhausted_ state.

```java
LONG_MAX nanos
 = 2562047 hours
 = 106751 days
~= 292 years

LONG_MAX millis
 = 2562047788015 hours
 = 106751991167 days
~= 292471208 years
 = 2924712 centuries
 = 292 million years
```
</details>

**Comment by simonbasle** [comment]
Note the function produced by `retryBackoff` _does_ accept `long numRetries` (so `Long.MAX_VALUE`) and never decrements that number but rather compares the `index()`-produced iteration number with the constant `numRetries`.

**Comment by simonbasle** [comment]
Looking at `Flux#repeat(long)` and `Flux#retry(long)`, it appears that these **do** decrement the `long`. In the case of `Long.MAX_VALUE`, it can mean that the repeat/retry is not "practically infinite". Would that be the real issue by any chance?

**Comment by simonbasle** [comment]
Closing, this is good for now. When a combination of infinite retries and no backoff is needed, the way to go is to use `.retry()`.
