### ISSUE TITLE
StepVerifier and virtual time

### ISSUE THREAD

**Issue by sergey-morenets** [reactor/reactor-core#1681]
### Actual behavior

Hi, I would like to test functionality of my Flux object that includes delay operations.
So if I run this code it executes properly.
```

		StepVerifier.withVirtualTime(() -> Flux.just(1, 2)
				.delayElements(Duration.ofHours(4)))
				.expectSubscription()
				.thenAwait(Duration.ofDays(1))
				.expectNext(1, 2)
				.verifyComplete();
```

But sometimes I already have constructed Flux object so I just want to pass it to withVirtualTime method:

```
		Flux<Integer> data = Flux.just(1, 2)
				.delayElements(Duration.ofHours(4));
		StepVerifier.withVirtualTime(() -> data)
				.expectSubscription()
				.thenAwait(Duration.ofDays(1))
				.expectNext(1, 2)
				.verifyComplete();
```

However I get an exception in this case:

```
	Suppressed: reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable
		at reactor.core.Exceptions.failWithRejected(Exceptions.java:249)
		at reactor.core.publisher.Operators.onRejectedExecution(Operators.java:799)
```

### Expected behavior

  Code should execute without errors.

### Reactor Core version

3.2.3

### JVM version (e.g. `java -version`)

11.0.2

**Comment by simonbasle** [comment]
It is a pre-requisite of the virtual time feature that the whole `Flux` be constructed inside the `Supplier`, because otherwise there is no way to install the proper `Scheduler` and ensure all scheduling operators use it.

I was going to say that at a minimum, all _time related_ operators must be invoked inside the `Supplier` but even that isn't entirely true, as installing the virtual time `Scheduler` replaces all default `Schedulers`, so the above error could still occur with a simple `.publishOn(Schedulers.elastic())`.
