### ISSUE TITLE
Propagate exception to asyncError in Flux/Mono.usingWhen

### ISSUE THREAD

**Issue by mp911de** [reactor/reactor-core#1687]
### Expected behavior

`Flux/Mono.usingWhen(…)` should provide an override accepting a `BiFunction<? super D,? super Throwable, ? extends Publisher<?>>` to propagate the error to the asynchronous error callback.

### Actual behavior

Currently, we translate transactional errors with `onErrorResume`:

```java
return Flux.usingWhen(Mono.just(it), action::doInTransaction,
		this.transactionManager::commit, s -> Mono.empty())
		.onErrorResume(ex -> rollbackOnException(it, ex).then(Mono.error(ex)));
```

In our case, we want to potentially post-process the exception.

**Comment by smaldini** [comment]
Maybe we could have a `BiFunction<? super D, ? super Signal<Void>>` to derive from the signal directly and avoid too much overloads. Also Mono could materialize that signal using `Signal<V>` making the cleanup even more composable from the resource it protects.

**Comment by simonbasle** [comment]
> Maybe we could have a `BiFunction<? super D, ? super Signal<Void>>` 

After looking into your proposal, this doesn't help much in terms of api breakage / overlap since there is unfortunately already a method that takes a single `Function` for all 3 possible async handlers :(

Plus it is a departure from the current implementation, so it'd require more effort.

I think a good middle ground is to add a single overload with the error `BiFunction` and all the other async `Function`, which would overlap a bit with the 3-`Function` version currently in place.

**Comment by simonbasle** [comment]
open question: if we introduce a new overload, would it make sense to deprecate all the other ones? sure it is more verbose to use the version with the 3 `(Bi)Function`, but at the same time it is _saner_ to explicitly think about the 3 cases: completion, error or cancellation.

**Comment by simonbasle** [comment]
we'll align the API on 2 use cases: a single handling `Function` to rule them all, and a complete set of complete `Function`/error `BiFunction`/ cancel `Function` for the more advanced use cases. intermediary signatures (2 handlers, 3 handlers that are all `Function`) will be deprecated. The single handler signature will be introduced to `Mono`.
