### ISSUE TITLE
Inconsistent `onErrorContinue` behavior depending on how a flux was created

### ISSUE THREAD

**Issue by elrodro83** [reactor/reactor-core#1705]
### Expected behavior

`onErrorContinue` on a `Flux` with an error, and converting it to a `Mono` to get the first result should work consistently.

### Actual behavior

Depending on how the `Flux` was created, calling `blockFirst` after `onErrorContinue` has different behaviors.

The following test cases show this: 
```
  @Test
  public void fluxCreateWithOnErrorContinue() {
    // call to blockFirst never returns

    Flux.<String>create(sink -> sink.next("A"))
        .map(s -> {
          throw new NullPointerException();
        })
        .onErrorContinue((t, s) -> {
          System.out.println("Skipped...");
        })
        .blockFirst();
  }

  @Test
  public void fluxJustWithOnErrorContinue() {
    final Object blockFirst = Flux.<String>just("A")
        .map(s -> {
          throw new NullPointerException();
        })
        .onErrorContinue((t, s) -> {
          System.out.println("Skipped...");
        })
        .blockFirst();

    // returns null
    System.out.println(blockFirst);
  }

  @Test
  public void fluxErrorWithOnErrorContinue() {
    // This fails with the passed NPE, not calling the error callback
    Flux.<String>error(new NullPointerException())
        .onErrorContinue((t, s) -> {
          System.out.println("Skipped...");
        })
        .blockFirst();
  }
```

### Steps to reproduce

Create a test case with the tests above and run them.

### Reactor Core version

Tested with 3.2.9 and 3.2.6

### JVM version (e.g. `java -version`)

```
java version "1.8.0_192-ea"
Java(TM) SE Runtime Environment (build 1.8.0_192-ea-b04)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b04, mixed mode)
```

and 

```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**Comment by simonbasle** [comment]
`onErrorContinue` is intended to prevent errors in the middle of a sequence, for cases where there is ideally at least one more value in the source that can be further processed. At worst, it can work with a source that **completes** right after the error-producing value, like in your second test case, potentially resulting in an empty sequence, which in turn translates to `null` with `blockFirst`.

On the other hand, an error-producing source like `Flux.error` cannot recover. Use `.onErrorReturn`/`onErrorResume` fallbacks for that sort of cases.

Your first example cannot work either, as the `sink` is never fed with more values, nor is it completed. This results in skipping the only element emitted by the `create` source (since it produces an error), and then never completing. Aka this is not equivalent to `Flux.empty().blockFirst()` but to `Flux.never().blockFirst()`.
