### ISSUE TITLE
FluxRefCount doesn't accomodate double cancellation

### ISSUE THREAD

**Issue by rasentry** [reactor/reactor-core#1738]
### Expected behavior
 No exception
### Actual behavior
stream throws java.util.concurrent.CancellationException. Without .onBackpressureBuffer() it works as expected. Also .refCount(1, Duration.ofMillis(1)) fix issue.
### Steps to reproduce
```
public static void main(String[] args) throws InterruptedException {
        Flux<Integer> stream = Flux.range(0, 100)
                .delayElements(Duration.ofMillis(2))
                .publish()
                .refCount()
                .onBackpressureBuffer();

        stream
                .log("subscriber 1")
                .subscribe();

        Thread.sleep(50);

        stream
                .take(1)
                .log("subscriber 2")
                .subscribe();

        Thread.currentThread().join();
    }
```
### Reactor Core version
 3.2.9-RELEASE
### JVM version (e.g. `java -version`)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

**Comment by simonbasle** [comment]
Unlike `FluxRefCountGrace`, `FluxRefCount`'s inner can receive 2 cancellations (or a cancellation after a terminate) and happily propagate the cancellation to the coordinator twice, making it think several of the hot subscribers have disconnected (which is not the case).

The inner subscriber can be made to do nothing in case of such redundant signals, which will fix the issue for all cases.

**Comment by simonbasle** [comment]
On a side note for @smaldini:
This manifest with `onBackpressureBuffer` because this operator does cancel twice (once in `cancel()` and once in `checkTerminated()`). @smaldini although this behavior is not counter to the spec (cancel MUST be idempotent), does it make sense? I see this pattern in several places where the checkTerminated/drain cancels the subscription with `if (cancelled) {s.cancel(); ...;}` where the `cancel()` method already does that...
