### ISSUE TITLE
reactor.scheduler.id metric tag for Schedulers.fromExecutorService is not useful

### ISSUE THREAD

**Issue by philsttr** [reactor/reactor-core#1739]
When using a `Scheduler` created via `Schedulers.fromExecutorService`, with metrics enabled via `Schedulers.enableMetrics()`, the metrics for the scheduler are tagged with `reactor.scheduler.id=fromExecutorService(null)`, which is not very useful.

The first problem is the `null` string, which is caused by:
1. [`this` escaping the constructor](http://www.javapractices.com/topic/TopicAction.do?Id=252) of `DelegateServiceScheduler` [here](https://github.com/reactor/reactor-core/blob/d4fd8c61d75e9ab44a98524ae8d9a52cfc4868b8/reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java#L50).
2. The `decorateExecutorService` call results in the `SchedulerMetricDecorator` accessing the not-fully-constructed `DelegateServiceScheduler` when it [scans for the Attr.NAME](https://github.com/reactor/reactor-core/blob/d4fd8c61d75e9ab44a98524ae8d9a52cfc4868b8/reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java#L49-L51)
3. The scan calls back into the not-fully-constructed `DelegateServiceScheduler` [scanUnsafe](https://github.com/reactor/reactor-core/blob/d4fd8c61d75e9ab44a98524ae8d9a52cfc4868b8/reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java#L101)
4. At that point, the executor is null, because `this.executor` hasn't been assigned yet from step 1

The second problem is that even if the first problem was solved, using the [`executor.toString()`](https://github.com/reactor/reactor-core/blob/d4fd8c61d75e9ab44a98524ae8d9a52cfc4868b8/reactor-core/src/main/java/reactor/core/scheduler/DelegateServiceScheduler.java#L101) as the scheduler name, and therefore in the `reactor.scheduler.id` tag, is questionable.  The standard executor service implementations provided by the JDK have toString() values that change based on the state of the executor service.  For example, [`java.util.concurrent.ThreadPoolExecutor` includes the number of active tasks, etc in the `toString()` value](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/concurrent/ThreadPoolExecutor.java#l1916).  Using such an unpredictable value in a tag is bad.

It seems that there should be a first class way of providing a scheduler name/id.  You could somewhat do this by wrapping an ExecutorService in something that provides a better .toString() , but that seems like a hack.

### Expected behavior

`reactor.scheduler.id` metric tag value for `Schedulers.fromExecutorService` has a useful value.

### Actual behavior

`reactor.scheduler.id=fromExecutorService(null)`

See main description.

### Steps to reproduce

1. Call `Schedulers.enableMetrics()`
2. Construct a scheduler via `Schedulers.fromExecutorService`
3. Observe tag values of metrics for the scheduler

### Reactor Core version

3.2.9.RELEASE

### JVM version (e.g. `java -version`)

11.0.2

**Comment by simonbasle** [comment]
I think we need to overhaul the whole shebang on how `Scheduler` metrics work, and right now it feels it's not even that useful...

 It is unclear to me what people typically want to see in schedulers metrics though, so any insight on this would be appreciated.

And note the current approach of translating `enableMetrics` to wrapping every underlying `ScheduledExecutorService` with a Micrometer instrumenting wrapper only makes sense for the (majority of) Schedulers that are backed by one or more executor services. Typically `newParallel` and `newElastic` will be backed by more than one, which is an additional difficulty: we probably WANT tags to separate each executor, and we NEED them anyway (because calling the micrometer instrumentation method on two different executors with the same id and same tags will "replace" the gauges, loosing visibility of the oldest executors).

On a more general note, it appears exposing the executor decorator as a `BiFunction<Scheduler, ScheduledExecutorService, ScheduledExecutorService>` was a mistake, because executors are guaranteed to be created inside constructor at least most of the time... So this is asking for `this` escaping constructor...

In most core schedulers, calling `scan(NAME)` at the end of the constructor is ok because these have a name derived from the constructor input parameters, but in the case of `fromExecutorService` we unfortunately reference the `executor` (which is not initialized at this point, since we're in the process of decorating it 🤕).

A band aid solution to this particular constructor escapism would be to offer an overload of `fromExecutorService` that takes an explicit `name` and have its `scan(NAME)` return something either static (eg. `fromExecutorService(anonymous)`) if name not explicitly set or the `fromExecutorService(${EXECUTOR_NAME})` if set.

**Comment by simonbasle** [comment]
more breaking follow-up to be tracked in https://github.com/reactor/reactor-core/issues/1778
