### ISSUE TITLE
Replay processor buffer add()s set() atomic reference then immediately reassign ref to it

### ISSUE THREAD

**Issue by Bill** [reactor/reactor-core#1760]
### Expected behavior
This report is about something that seems odd in the source code. It is not about a functional problem.

### Actual behavior
I see some code I don't understand in `ReplayProcessor. SizeAndTimeBoundReplayBuffer.add()`:

https://github.com/reactor/reactor-core/blob/v3.2.10.RELEASE/reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java#L400

and similarly in `ReplayProcessor. SizeBoundReplayBuffer.add()`:

https://github.com/reactor/reactor-core/blob/v3.2.10.RELEASE/reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java#L747

In each case I see:

```java
tail.set(n);
tail = n;
```

In each case, `tail` is a reference to an instance of a class that extends `AtomicReference`.

Why would it ever make sense to `set()` the atomic reference and then immediately reassign the variable to a new atomic reference? Is this some sort of elegant (but inscrutable, to me at least) concurrency measure?

### Steps to reproduce
n/a

### Reactor Core version
3.2.10.RELEASE

### JVM version (e.g. `java -version`)
n/a

**Comment by akarnokd** [comment]
This is how linked lists are appended to, with the addition that the links have to be traversable from other threads which requires atomic publication of a next pointer. `tail.set()` sets the next pointer to the new node `n`, then the new tail becomes that new node. Since an append is guaranteed to be non-concurrent and serialized, this assignment doesn't have to be atomic too.

**Comment by Bill** [comment]
Oh yeah. I remember linked lists now. Thanks @akarnokd!
