### ISSUE TITLE
ExecutorService metrics remain even after the scheduler is terminated

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1787]
Since there is no way of removing reporter in Micrometer, once [we apply the decorator](https://github.com/reactor/reactor-core/blob/832d870a2ee7b36286750f69719a45245b18f55e/reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java#L82) it will continue reporting even if we terminate the scheduler & executor.

Steps to reproduce:
1. Enable metrics
2. Create a scheduler
3. Submit a task
4. Dispose the scheduler
5. Observe metrics being reported for the underlying executor after it got disposed

**Comment by simonbasle** [comment]
@shakuzen can you confirm that now that we keep the reference to the decorated `ExecutorService`, its meters will be unregistered once the reference is garbage collected?

**Comment by simonbasle** [comment]
(see https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java#L81)

**Comment by shakuzen** [comment]
Meters can be removed with the `MeterRegistry#remove` method since Micrometer 1.1, if it makes sense to do that when disposing.

> can you confirm that now that we keep the reference to the decorated `ExecutorService`, its meters will be unregistered once the reference is garbage collected?

No, meters will not be unregistered when the ExecutorService is garbage collected. Micrometer keeps reference to the meters created. Using the `remove` method is the way to unregister metrics. Even meters backed by an object reference that has been garbage collected will not be unregistered. The affected metrics would report `NaN` or `null` depending on the configured metrics backend.

**Comment by bsideup** [comment]
@shakuzen thanks! I will look into using `#remove` 👍

**Comment by bsideup** [comment]
Submitted https://github.com/reactor/reactor-core/pull/1991

@shakuzen is there a reason why Micrometer's executor service wrapper is not removing the metrics on executor's shutdown? Perhaps it should be changed there instead?

**Comment by shakuzen** [comment]
> @shakuzen is there a reason why Micrometer's executor service wrapper is not removing the metrics on executor's shutdown? Perhaps it should be changed there instead?

Good question. Removing them immediately may prevent the metrics from ever being published, depending on the timing of registering and removing the metrics with the publishing.
