### ISSUE TITLE
Context is always empty

### ISSUE THREAD

**Issue by Brutus5000** [reactor/reactor-core#1790]
### Expected behavior

Citing the docs: `Mono.subscriberContext() always returns the Context set by subscriberContext calls`

### Actual behavior
Mono.subscribedContext() always returns an empty context (`java.util.NoSuchElementException: Context is empty`)

### Steps to reproduce

I tried multiple variations but for the sake of example I give you these simple cases (also tried unblocking variants - do not work as well):
```
        Flux.just(1,2,3,4)
                .subscriberContext(Context.of("metadata", 1234))
                .subscribe(i -> {
                   System.out.println(Mono.subscriberContext().block().get("metadata").toString());
        });


        Flux.just(1,2,3,4)
                .doOnNext(i ->
                        System.out.println(Mono.subscriberContext().block().get("metadata").toString()))
                .subscriberContext(Context.of("metadata", 1234))
                .subscribe();
```

### Reactor Core version
3.2.10

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_212"

**Comment by simonbasle** [comment]
Just in case, be sure to read the whole "Adding a Context to a reactive sequence. This feature is advanced and supposes you have a good grasp of reactive streams principles, like the fact that the subscribe signal propagates from bottom to top (the mechanism the `Context` resolution piggybacks on), or that you should always avoid breaking the chain of operators with intermediate `subscribe()` and/or `block()`.

These two principles are pre-requisites for the sentence you quoted to hold true.

Bottom-up propagation: none of your examples write to the `Context` late enough in the chain. The simple example section of the refguide explicitly states that order maters greatly.

Intermediate subscribe/block: Both of your examples try to read the `Context` from a broken out portion of the chain, within a side effect (`doOnNext`) or a `subscribe`. In order to materialize the `Context` with `Mono.subscriberContext()`, you need to call it within a `flatMap` (which will attach the outer context to the inner mono). Alternatively you can access the `Context` in a `doOnEachNext` instead of `doOnNext`, but only by directly resolving it from the passed `Signal`: `.doOnEach(sig -> sig.getContext())`.
