### ISSUE TITLE
bad stack trace for Mono.just() operators

### ISSUE THREAD

**Issue by Aleksandr-Filichkin** [reactor/reactor-core#1858]
If we have exception inside .just() operator, then stacktrace is only for the upstream operator.
````
@GetMapping(value = "/test")
    public Mono<Integer> test()  {
        return webClient
                .get()
                .uri(URI.create("http://google.com"))
                .retrieve()
                .bodyToMono(String.class)
                .flatMap(x->mono1())
                .doOnError(throwable -> {
                    System.out.println("Error" + throwable);
                    throwable.printStackTrace();
                });
    }
```
    public Mono<Integer> mono1()  {
        return mono2();
//        return mono2().map(x->x/0); Good
    }

    private Mono<Integer> mono2() {
        return Mono.just(10/0);
//        return Mono.just(10); Good
    }`


Is it expected behaviour or we can improve it?

**Comment by bsideup** [comment]
Hi @Aleksandr-Filichkin,

I transferred this issue to to `reactor-core` since it does not belong to BlockHound.

`Mono.just` does not capture any exceptions, because it accepts a value. Think about it this way:
```java
var result = 10/0;
return Mono.just(result);
```

Obviously, it will throw an exception even before reaching `Mono.just`. Then, the exception will be captured by `flatMap` (the behaviour you observe).

Consider using `Mono.defer` or `Mono.fromCallable` if you need to capture that exception.
