### ISSUE TITLE
Update to Micrometer 1.3 and use their ScheduledExecutorService support

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1911]
Since https://github.com/micrometer-metrics/micrometer/issues/1021 is implemented now, we should use it instead of our own:
https://github.com/reactor/reactor-core/blob/d5a124fd69448e6e378d44c4617f488f222ff91c/reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java#L111

**Comment by thiyagu-7** [comment]
I have made the changes for this and it is in my forked repo

https://github.com/thiyagu-7/reactor-core/commit/a79f3f1ccae1ed87553c988da438225d6b9acc9c
Would be happy to send a PR.

But the title says to update to Micrometer 1.3. But AFAIU, since reactor-code is using the latest version of micrometer, there is no need to make any gradle config changes.. Correct me if I'm wrong.

**Comment by bsideup** [comment]
Hi @thiyagu-7,

You're move than welcome to contribute this change! Let me know if you need any clarification or anything 👍 

> since reactor-code is using the latest version of micrometer, there is no need to make any gradle config changes

Yes, we use `latest.release` and it should catch the latest available release (1.3.0) automatically

**Comment by simonbasle** [comment]
re `latest.release` I'm not sure that is a good strategy long term, though, when some backward incompatible changes inevitably start creeping into Micrometer 🤔

**Comment by bsideup** [comment]
@simonbasle I was surprised too 😅maybe now is a good time to change it, while it is still stable
