### ISSUE TITLE
Flux.mergeOrdered with reverse order does not order correctly

### ISSUE THREAD

**Issue by sinwe** [reactor/reactor-core#1918]
`Flux.mergedOrdered` operator with `Comparators.naturalOrdering.reversed` does not reverse the value emitted properly.

## Expected Behavior
        StepVerifier.withVirtualTime(() => {
          Flux flux1 = Flux.just(1, 20, 40, 60, 80).delayElements(Duration.of(5, Seconds))
          Flux flux2 = Flux.just(10, 30, 50, 70).delayElements(Duration.of(5, Seconds)).delaySubscription(Duration.of(2500, Milliseconds))
          Flux.mergeOrdered(Comparator.naturalOrder().reversed(), flux1, flux2)
        }).thenAwait(Duration.of(30, Seconds))
          .expectNext(80, 70, 60, 50, 40, 30, 20, 10, 1)
          .verifyComplete()
      }

## Actual Behavior
        StepVerifier.withVirtualTime(() => {
          Flux flux1 = Flux.just(1, 20, 40, 60, 80).delayElements(Duration.of(5, Seconds))
          Flux flux2 = Flux.just(10, 30, 50, 70).delayElements(Duration.of(5, Seconds)).delaySubscription(Duration.of(2500, Milliseconds))
          Flux.mergeOrdered(Comparator.naturalOrder().reversed(), flux1, flux2)
        }).thenAwait(Duration.of(30, Seconds))
          .expectNext(10, 30, 50, 70, 1, 20, 40, 60, 80)
          .verifyComplete()
      }

## Steps to Reproduce

```java
@Test
public void repoCase() {
        StepVerifier.withVirtualTime(() => {
          Flux flux1 = Flux.just(1, 20, 40, 60, 80).delayElements(Duration.of(5, Seconds))
          Flux flux2 = Flux.just(10, 30, 50, 70).delayElements(Duration.of(5, Seconds)).delaySubscription(Duration.of(2500, Milliseconds))
          Flux.mergeOrdered(Comparator.naturalOrder().reversed(), flux1, flux2)
        }).thenAwait(Duration.of(30, Seconds))
          .expectNext(80, 70, 60, 50, 40, 30, 20, 10, 1)
          .verifyComplete()
      }
}
```

## Your Environment

* Reactor version(s) used: 3.2.9.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): 1.8
* OS and version (eg `uname -a`): Mac OS

**Comment by simonbasle** [comment]
This is working as intended, the comparison is "local" and not a sort of the whole sequence: the operator looks at the first element of each flux, takes the greatest (due to reverse comparator) and requests the next element ONLY FOR THE FLUX IT JUST TOOK FROM.

The sequence of events in your particular case is:
 - peeks at flux1 => 1
 - peeks at flux2 => 10
 - chooses 10 over 1, peeks at flux2 => 30
 - chooses 30 over 1, peeks at flux2 => 50
 - chooses 50 over 1, peeks at flux2 => 70
 - chooses 70 over 1, peeks at flux2 => complete
 - drains flux1 => 1, 20, 40, 60, 80

**Comment by sinwe** [comment]
@simonbasle Thanks for the explanation.
