### ISSUE TITLE
What are the alternatives of doAfterSuccessOrError

### ISSUE THREAD

**Issue by codesonteen** [reactor/reactor-core#1934]
What are the alternatives of doAfterSuccessOrError(BiConsumer)

I would like to use Consumer as a lambda argument.

**Comment by simonbasle** [comment]
The problem we saw with `doAfterSuccessOrError` is the fact that the `BiConsumer` had to deal with a lot of potential `null` cases: null left hand side, null right hand side, but also both sides null in the case of an empty successful `Mono`. So we tried to reduce the number of places where `null` are allowed or passed to the user, and to keep those cases as simple as possible.

But maybe you need the content of the terminal signal, but not the "side-effect must occur AFTER the termination" aspect? in that case you could use the more classic `doOnSuccess` (a remaining occurrence where `null` is passed) combined with `doOnError` ?

The alternative is to use `doFinally`, which _doesn't_ expose the values but just the _type_ of termination that just occurred.


If you can produce a compelling example where you absolutely need the side effect to apply AFTER the termination AND you absolutely need access to the content of the terminal signal, we might consider introducing new `doAfterXXX` methods, but that would mean 3 new methods (after valued success, after empty success and after error). That's something we'd like to avoid.

**Comment by codesonteen** [comment]
For an instance of one of my use cases,

I am building a middleware API system which the underlying system is accepting the request and takes time for processing automation (e.g. resource provisioning system).

example code:
```
public Mono<Resource> deploy() {
  Mono<Resource> resource = underlyingService.allocateResource();
  resource.flatMap(resourceRepository::save).doAfterSuccess(this::initResourceAsync)
  return resource;
}

public void initResourceAsync(Resource resource) {
  // Do something...
}
```

I expected my middleware API to return a result of repository.save() and do something asynchonously which having significant effect on API response time.

**Comment by simonbasle** [comment]
shouldn't the `deploy` `Mono` be considered "done" _only_ when the resource has been initialized, though?

it is a common mistake and code smell to do a `subscribe` from inside a `doXXX` method (aka side effect methods), because you lose any ability to deal with errors and cancellation. what you usually want instead is to tie it to your main sequence with eg. `flatMap` or `then`.

**Comment by simonbasle** [comment]
note however that in your case, it is perfectly fine to use `doOnNext`: saving of the resource is already done by the time it reached the side effect operator, it's just a matter of when the `doSomething` will be triggered (before the `onNext` event is passed further down in the case of `doOnNext`, after in the case of `doAfterSuccess`, which doesn't change anything since there is no further processing and the doSomething is asynchronous anyway).

**Comment by codesonteen** [comment]
The `deploy` `Mono` is considered ready to return when it is already been `allocated` by `allocateResource()` and the resource has been saved into the collection/database. After that, the `initResource(resource)` is going to execute in background if the `allocateResource()` success. 

For logging and exception handling consideration, There are exception handlers in the underlying service implementation classes.

**Comment by simonbasle** [comment]
ok, so use `doOnSuccess` and `doOnError` then :+1:

**Comment by codesonteen** [comment]
`doOnSuccess` works but it is having a significantly higher response time. (around 1400 milliseconds higher)

**Comment by simonbasle** [comment]
that is very surprising, probably an indicator that your `doSomething` is blocking somehow?

**Comment by codesonteen** [comment]
There is a call to Apache Commons ClosableHttpAsyncClient in `doSomething()` which may somehow end up blocking. I will check on this and will get back with the result.

**Comment by simonbasle** [comment]
@codesonteen were you able to verify there was a blocking call?

**Comment by codesonteen** [comment]
I've test by creating a demo project and use both doOnSuccess() and doAfterXXX() with both blocking and non-blocking

Results as below.

```
// Constant URI for tests
final var URI_1 = "http://hostname/index.html";
final var URI_2 = "http://hostname/index.php" // I set up a 5 seconds sleep here.
```

`doOnSuccess()` with `non-blocking`, return ~50ms
```
WebClient.create()
            .get()
            .uri(URI_1)
            .exchange()
            .flatMap(response -> response.bodyToMono(String.class))
            .doOnSuccess(response -> client.get().uri(URI_2).exchange().flatMap(res -> res.bodyToMono(String.class)));
```

`doAfterXXX()` with `non-blocking`, return ~50ms
```
WebClient.create()
            .get()
            .uri(URI_1)
            .exchange()
            .flatMap(response -> response.bodyToMono(String.class))
            .doAfterSuccessOrError((response, throwable) -> client.get().uri(URI_2).exchange().flatMap(res -> res.bodyToMono(String.class)));
```

`doOnSuccess()` with `blocking`, return > 5 seconds
```
WebClient.create()
            .get()
            .uri(URI_1)
            .exchange()
            .flatMap(response -> response.bodyToMono(String.class))
            .doOnSuccess(response -> {
                try {
                    HttpClient.newHttpClient().send(HttpRequest.newBuilder(URI.create(URI_2)).GET().build(), HttpResponse.BodyHandlers.ofString()).body();
                } catch (IOException | InterruptedException e) {
                    e.printStackTrace();
                }
            })
```

`doAfterXXX()` with `blocking`, return ~50ms.
```
WebClient.create()
            .get()
            .uri(URI_1)
            .exchange()
            .flatMap(response -> response.bodyToMono(String.class))
            .doAfterSuccessOrError((response, throwable) -> {
                try {
                    HttpClient.newHttpClient().send(HttpRequest.newBuilder(URI.create(URI_2)).GET().build(), HttpResponse.BodyHandlers.ofString()).body();
                } catch (IOException | InterruptedException e) {
                    e.printStackTrace();
                }
            });
```

To sum up, 
`doAfterXXX()` which is having blocking call inside can return immediately.
`doOnSuccess()` which is having blocking call inside have to wait and the return will be delayed.

So, According to my underlying service, I think it is end up blocking by 

```
ClosableHttpAsyncClient httpClient = ...;
Future<HttpResponse> httpResponse = httpClient.execute(request, null);
httpResponse.get();
```

The underlying service was written by using Future.get() which is blocking.

**Comment by simonbasle** [comment]
This is simply a misuse to do anything blocking in a `do*` method. The fact that you were doing the blocking in `doAfterSuccessOrError` was hiding the symptoms, because downstream the `onComplete` signal would still appear to arrive in a timely fashion (_then_ you would block the current thread). Now that you have to use `doOnSuccess`, the blocking call occurs _before_ `onComplete` is propagated and the problem becomes much more visible.

Try to either rewrite the underlying service, or offset that call in another thread (eg. by using `Mono.fromCallable(...).subscribeOn(Schedulers.boundedElastic())`).

Also, avoid performing such side effects if possible, and favor tying the call to the outer `Flux` by using methods like `then` or `zipWith` or `concatWith`... Otherwise you'll lose the ability to notice errors or handle cancellations.
