### ISSUE TITLE
take(Duration) does not terminate inside Schedulers.parallel()

### ISSUE THREAD

**Issue by mikeharder** [reactor/reactor-core#1957]
## Expected Behavior
`take(Duration)` should terminate after the specified duration, regardless of the scheduler.

## Actual Behavior
`take(Duration)` does not terminate inside `Schedulers.parallel()`.  The inner flux runs forever.

## Steps to Reproduce
This code works as I would expect.  It prints the current time in a loop for one second, then completes.

```java
Scheduler newParallel = Schedulers.newParallel("name", 10);

Flux.just(1)
    .parallel()
    .runOn(newParallel)
    .flatMap(i -> Flux.just(1)
                      .repeat()
                      .doOnNext(j -> System.out.println(System.nanoTime()))
                      .take(Duration.ofSeconds(1)))
    .then()
    .block();

newParallel.dispose();
```

However, if `Schedulers.parallel()` is used instead of `Schedulers.newParallel()`, the inner flux runs forever:

```
Flux.just(1)
    .parallel()
    .runOn(Schedulers.parallel())
    .flatMap(i -> Flux.just(1)
                      .repeat()
                      .doOnNext(j -> System.out.println(System.nanoTime()))
                      .take(Duration.ofSeconds(1)))
    .then()
    .block();
```

## Your Environment
* Reactor version(s) used: `3.3.0.RELEASE`
* JVM version (`javar -version`): `openjdk version "11.0.4" 2019-07-16`
* OS and version (eg `uname -a`): `Windows 10`

**Comment by simonbasle** [comment]
The `parallel().runOn(...)` has a parallelism that defaults to the number of CPUs, which is the same as the global `parallel()` pool size. On the other hand, all time-sensitive operators default to scheduling their work on said `Schedulers.parallel()` global scheduler.

Since essentially `Flux.just(1).repeat()` is an infinite loop, it fully occupies ALL the threads backing the parallel scheduler, and starves the `take` scheduled cancellation from ever executing.

This is similar to what would happen with this `Executor`-based imperative code:

```java
int size = 2;
final ScheduledThreadPoolExecutor service = (ScheduledThreadPoolExecutor) Executors.newScheduledThreadPool(size);
service.setMaximumPoolSize(size);

//the "parallel" with "repeat" part:
final Future<Object> loopFuture1 = service.submit(() -> {
	while (true) {
		Thread.sleep(100);
		System.out.println("repeat rail 1");
	}
});
final Future<Object> loopFuture2 = service.submit(() -> {
	while (true) {
		Thread.sleep(50);
		System.out.println("repeat rail 2");
	}
});
//the "take(duration)" part:
service.schedule(() -> {
	System.out.println("Cancelling both rails");
	loopFuture1.cancel(true);
	loopFuture2.cancel(true);
}, 500, TimeUnit.MILLISECONDS)
       .get();
```

Maybe we should make a recommendation that for `parallel().runOn(x)`, users should favor a dedicated `Schedulers.newParallel()` that they would have to manage? 🤔

**Comment by simonbasle** [comment]
Also note that you'll get in the exact same issue with a separate Scheduler if you force `.parallel(x)` (same parallelism as the `Scheduler`) and pass the `Scheduler` to `take(Duration, Scheduler)`.
