### ISSUE TITLE
WorkQueueProcessor number of subscribers more than thread pool size

### ISSUE THREAD

**Issue by srinivasvsk** [reactor/reactor-core#199]
Trying to understand bit on how the number of subscribers would work in parallel. Here is an example, when i have the executor service with fixed thread pool of say 2 and i have more than 2 subscribers. The process seems to hang, i was expecting to see some error or warning.

```
   ExecutorService executorService = Executors.newFixedThreadPool(2)
   def bc = WorkQueueProcessor. create(executorService, 16)
   bc.subscribe(sub('spec1', latch))
   bc.subscribe(sub('spec2', latch))
   bc.subscribe(sub('spec3', latch))
   bc.subscribe(sub('spec4', latch))
   bc.subscribe(sub('spec5', latch))
```

**Comment by simonbasle** [comment]
The problem is that to detect that you are subscribing too many subscribers, we'd have to introspect the `ExecutorService`... but the interface doesn't offer a way of evaluating the maximum capacity of an `ExecutorService` 😞 

We *could* try, in a best effort way, to introspect the `executor`, but that wouldn't cover all the cases:

- For instance, using `Executors.newFixedThreadPool(2)` returns a `ThreadPoolExecutor` which can be detected, allowing to use `getMaxPoolSize()` to evaluate and reject a new subscriber ✅ 
- `newWorkStealingPool` and the corresponding `ForkJoinPool` are another usable class, evaluating through `getParallelism()` ✅ 
- On the other hand, using `Executors.newSingleThreadExecutor()` returns a `FinalizableDelegatedExecutorService`, which can't be introspected and has no method to evaluate if a subscriber can be added ❌

**Comment by simonbasle** [comment]
a bunch of solutions that I thought about, none of which are perfect 😢 :

1. best effort detection (only direct instances of `ThreadPoolExecutor` and `ForkJoinPool` could be guaranteed safety).
2. restrict creation to `ThreadPoolExecutor` instead of Executor (**big bad breaking change** as some users may have rolled their own `Executor` implementations)
3. allow any `Executor` but also require to provide a `maxSubscribers` limit explicitly (**breaking change**, new parameter)

@smaldini @srinivasvsk let me know what you think

**Comment by srinivasvsk** [comment]
Thanks for looking in to. It sounds complicated, initially i thought when you call the .subscribe method,  within the method where you do this executor.execute(signalProcessor), that call might give you some error or block because there is no thread available from pool which means threads in pool exhausted. 
Sorry just talking theory, didn't test.
1) sounds like good idea

**Comment by simonbasle** [comment]
ok we'll go with the best effort approach first, see PR #287 @srinivasvsk

**Comment by dfeist** [comment]
FYI: @simonbasle The test that asserts this is flakey for me.  reactor.core.publisher.WorkQueueProcessorTest#singleThreadWorkQueueDoesntRejectsSubscribers
