### ISSUE TITLE
Consider a fromPaginated specialized operator

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1998]
> (original request below was focusing on using `expand` with a factory method - "Add Flux.expand creator that does not require a state upfront")

# The problem

Since `expand()` is an operator, the one has to have a bit of a code duplication to use it:
```java
Flux<Page> flux = client.fetchPage(null).expand(it -> {
    return Mono
        .justOrEmpty(it.nextPageId())
        .flatMap(nextPageId -> client.fetchPage(nextPageId));
})
```

Here, `client#fetchPage` is duplicated.

# Proposal
It would help to have a factory method with a "default" state:
```java
public <S, T> Flux<T> expand(
			Supplier<S> stateSupplier,
			Function<T, S> stateExtractor,
			Function<S, ? extends Publisher<T>> expander
	) 
```

And use it like this:
```java
flux = Flux.expand(
    () -> Optional.of(""),
    Page::nextPageId,
    it -> {
        return Mono.justOrEmpty(it)
            .flatMap(nextPageId -> Mono.fromCompletionStage(
                client.fetchPage(trimToNull(nextPageId))
            ));
    }
)
```

**Comment by simonbasle** [comment]
I'm coming back to this one and I wonder if `expand` in its current form is _that_ well suited for the pagination case. Especially if both fetching the next page and fetching the page's content are async operations.

In that later case, what we'd usually get is a duality of types: the PAGE type and the CONTENT type.
And what would probably be desirable for page processing would be to:

 1. fetch the first PAGE
 2. fetch the CONTENT as a `Flux<CONTENT>` of that page
 3. propagate each `onNext(CONTENT c)`
 4. when content flux completes, resolve and fetch the next PAGE
 5. repeat from step 2. until fetching the next PAGE returns an empty `Publisher`
 6. complete the outer sequence

Expand isn't comfortable to use in that scenario, because it recursively expands publishers assuming they all bear the same type `<T>`.

When processing pages, I don't think we're that interested in the PAGE objects themselves, other than as a mean to access the `Flux<CONTENT>` and resolve the next `PAGE`.

So maybe an `expandPage` specialized operator would be a good idea? 🤔 

```java
Flux<PageContent> pages = Flux.expandPages(
    Mono.just(initialPage), //or a more dynamic call to fetch first PAGE
    Page::contentFlux,
    Page::nextPage);
```

This could implement meaningful backpressure translation, eg. for a `request(100)`:
 - on the first page, `request(100)` from the content `Flux`
 - track how many elements are emitted
 - if enough elements have been emitted, complete. don't fetch next page on completion. cancel the content subscription
 - if < 100, eg. 30, fetch the next page on completion
 - from the content, `request(100 - 30)`
 - etc...

**Comment by bsideup** [comment]
@simonbasle I would suggest changing the first argument from `Mono<T>` to `<T>` to keep it simple. If anyone needs to perform an asynchronous lookup of a first page, they can use:
```java
lookupInitialPage().flatMapMany(initialPage -> {
    return Flux.expandPages(initialPage, Page::contentFlux, Page::nextPage);
});
```

I would also avoid controlling the page size and/or relying on it, since sometimes pagination is implemented in the "until null returned" style.

Last but not least, if you plan to have a specialized operator, perhaps `expand` should not be used, as it seems to be confusing to the users, and maybe more specific word can be used instead (e.g. `Flux.paginate` or similar)

**Comment by simonbasle** [comment]
I have made good progress on the draft, and that initial implementation looks promising.

But for the naming, I fear that `paginate`/`paging`/`paginated`/etc. give the wrong impression that the operator will perform pagination, ie. divide into pages.

How about... `fromPaginated(...)`?

**Comment by simonbasle** [comment]
closing this as the exploratory PR didn't demonstrate much benefit in practical cases, and it's been in limbo for a while.
