### ISSUE TITLE
onErrorContinue behaves differently for Mono and Flux publishers

### ISSUE THREAD

**Issue by deepak-auto** [reactor/reactor-core#2006]
## Expected Behavior
onErrorContinue should behave the same way for a Mono publisher as it does for a Flux publisher

## Actual Behavior
onErrorContinue propagates ("rethrows") the error for a Mono publisher but drops the error for a Flux publisher

### Mono
```java
    @Test
    void testOnErrorContinue() throws Exception {
        Mono.just(1)
                .flatMap(a -> Mono.error(new RuntimeException("oops")))
                .onErrorContinue((e, l) -> System.out.println("onErrorContinue works!"))
                .subscribe(a -> System.out.println("hello"), e -> System.out.println("onErrorContinue does not work!"));
    }
```
**Output**: `onErrorContinue does not work!`

### Flux
```java
    @Test
    void testOnErrorContinue() throws Exception {
        Flux.just(1)
                .flatMap(a -> Mono.error(new RuntimeException("oops")))
                .onErrorContinue((e, l) -> System.out.println("onErrorContinue works!"))
                .subscribe(a -> System.out.println("hello"), e -> System.out.println("onErrorContinue does not work!"));
    }
```
**Output**: `onErrorContinue works!`

## Your Environment

* Reactor version(s) used: 3.3.1.RELEASE
* JVM version (`javar -version`): 11.0.2
* OS and version (eg `uname -a`): 19.2.0 Darwin (MacOS Catalina)

**Comment by simonbasle** [comment]
Use `onErrorContinue` with a ten foot pole, because it is a weirder beast than most other operators, which is why it comes with a big red warning in the javadoc. Because:

1. it impacts operators ABOVE it
2. it doesn't guarantee any impact, rather it hints: operators MUST implement a special `onErrorContinue` codepath to take that hint. Not all do.
3. the hint basically says: "if your operation generates an error, rather than stopping there and propagating it downstream, IF YOU KNOW YOU MIGHT HAVE FURTHER SOURCE DATA TO WORK WITH, request one more source element and continue from there"

This last point is especially relevant to your `Mono` source case and your original assumption, because by definition such `Mono`s will NEVER have further source data to work with. So `onErrorContinue` is irrelevant on most `Mono` operators, plain and simple.

**Comment by deepak-auto** [comment]
Thank you for responding. We will stop using `onErrorContinue`. 

Regarding the documentation for the `Mono` `onErrorContinue` - it says "Let compatible operators recover from errors by dropping the incriminating element from the sequence and continuing with subsequent elements", which gives the impression that it would work exactly for `Mono` as it would for `Flux`. It would be great if you could update it to reflect that the operator is actually irrelevant for `Mono`.

**Comment by simonbasle** [comment]
The thing is, since it hints operators above it to change their behavior when they're about to generate an error, it is still pretty useful to have it in the `Mono` api.

That is for cases where you have several operators in a chain, some of which are compatible with continuing, but the last operator in the chain switches to a `Mono`.

For instance the following would benefit from `onErrorContinue`:

```java
Mono<Integer> sum = Flux.just(1, 10, 0, 100)
    .map(i -> 100 / i)
    .reduce(0, (i, sum) -> sum + i);
```
The source is ultimately a `Flux`, and the operator that will trigger an `onError` is `map`, also a `Flux`. So despite having a `Mono` on our hands due to the `reduce`, we still might want to activate continue mode for the relevant parts of the sequence by doing:

```java
sum.onErrorContinue(...)
   .subscribe(System.out::println);
```
The above would print `101` (`100/1`+`100/10`+(skipped)+`100/1`).

**Comment by deepak-auto** [comment]
Thanks for the explanation! It is a bit confusing but hopefully I will get a hang of this "gotcha"s soon.
