### ISSUE TITLE
wrap exceptions sent to windows (rather than main sequence)  in a SourceException

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#2041]
The following results in `BubblingException` containing the `IllegalStateException`:

```java
Mono.just("a").concatWith(Mono.error(new IllegalStateException("e")))
		.windowUntil(s -> s.equals("b"))
		.concatMap(Flux::collectList)
		.blockLast();
```

By comparison the following results in just the `IllegalStateException` as expected:

```java
Mono.just("a").concatWith(Mono.error(new IllegalStateException("e")))
		.bufferUntil(s -> s.equals("b"))
		.blockLast();
```

**Comment by simonbasle** [comment]
IIRC this is a blanket behavior of window operators, that have to deal with currently opened windows on top of the main subscriber when propagating an upstream error.

Buffering operators don't have that notion, because there's no notion of the user handling errors at the buffer level, unlike with windows.

**We need to propagate the error to the last window** so that the _user_ can decide how to treat interrupted windows, especially when the window is treated in "batches" somehow. For example, let's consider a windowing associated with remote HTTP requests and collecting the results. Compare these two approaches:

```
Flux.range(1, 10).concatWith(Mono.error(new IllegalStateException("e")))
    .window(4)
    .concatMap(w -> w.flatMap(this::makeRequest)
					.collectList()
					.onErrorReturn(Collections.emptyList()))
    .blockLast();
```
and
```
Flux.range(1, 10).concatWith(Mono.error(new IllegalStateException("e")))
    .window(4)
    .concatMap(w -> w.flatMap(this::makeRequest)
					.onErrorResume(Mono.empty())
					.collectList())
    .blockLast();
```
In the former, if there is an error in the source the last window's collected `List` will be _replaced_ by an empty `List`, discarding the responses accumulated so far.
In the later, the `onErrorResume` swallows the error, allowing the collected responses to be emitted as a partial `List` despite the error.

**We also need to propagate the error to the main sequence subscriber** (here `concatMap`) in order to correctly terminate the sequence:
 - in case there is no window opened at the moment whose consumption could propagate the error to the main sequence
 - in case the window consumption _doesn't_ propagate the error to the main sequence at all

In the case above, the window consumption swallows the errors. As a result, it appear to `concatMap` as if the mapping completed normally, but without error-to-main propagation no further signal would come in, so the sequence would hang.

I have mixed feelings about the situation, but it seems to me this is still the best choice.
The trouble is that there is no real way for the operator to be sure that window consumption and main sequence are tied (even though we expect the vast majority of cases to use `concatMap` or `flatMap` for window consumption, which does tie window and main).

So the alternatives for the window are:
 - `cancel()` the window: would always drop partially accumulated elements
 - `onComplete()` the window: would always emit partially accumulated elements
 - `onError(e)` the window: lets the user decide between dropping and emitting

I don't think there is any discussion on the propagation to the main sequence...

**Comment by simonbasle** [comment]
It would be a breaking change, but one possible solution to differentiate between errors in the window consumption (ie. part of the `flatMap` function) vs errors propagated to an open window from the main sequence's source could be to wrap the later in a `SourceException` when propagating it to the window (and not wrapped when propagating it to the main sequence).

Another potential idea would be to make it configurable with eg. an `enum` (`PROPAGATE_DIRECT`, `SWALLOW`, `CANCEL`, `PROPAGATE_WRAPPED`, the default being the first one), but then we're exploding the number of window overloads

**Comment by simonbasle** [comment]
I've thought a bit about the implication of "making it configurable", and I think it is probably going to be too much work because it implies creating a new `Flux` sub-type like `ConnectableFlux` and `GroupedFlux`. This in turn has wider implications, like implementing `OnAssembly` and `Lift` hooks...

Adding a `SourceException` and wrapping upstream onError in `SourceException` would probably be a lower hanging fruit that could still help quite a bit, though.
