### ISSUE TITLE
Exception handling with ability to replace incriminating element with exception wrapper and continue Flux execution.

### ISSUE THREAD

**Issue by pavelkuchin** [reactor/reactor-core#2090]
Hello! For Flux It would be great to have ability to replace incriminating element with generated element and continue flux execution. I've searched through Handling Errors Decision Tree and haven't found case where we are catching exception, generating new element based on the exception properties AND continuing current Flux processing.

onErrorReturn - emits captures fallback value without ability to generate it dynamically based on exception properties.
onErrorResume - Subscribe to a fallback publisher, which makes it possible to generate value based on exception properties but it terminates current flux.
onErrorContinue - Drops incriminating element and continues flux processing.

## Motivation
We have need to replace exceptions with wrapper-objects during Flux consumption. In our case each flux element leads to an independent action which may or may not trigger an exception. For elements which led to an exception client expects a resulting element which wraps exception's code and message. Since all the elements are independent, error during processing of one of them should not trigger flux termination. We can continue flux processing by using onErrorContinue (which drops error causing element completely) and we can replace exception by wrapper-object using onErrorResume (which terminates current flux and uses provided one) but we can't satisfy both conditions (replace element to wrapper and continue current stream execution).

## Desired solution
It would be nice to have onErrorReturn method with exception handler (so it can return exception based generated element instead of captured one).

## Considered alternatives
Separate method (for instance onErrorContinueWithReplacement) which would allow to emit an element based on exception properties.

**Comment by simonbasle** [comment]
How is this method that can throw applied? You should either apply it in a `map` or a `flatMap`, catching the exception in the first case, or using `onErrorReturn` in the second case:

```java
source.map(v -> { try { return process(v); }
    catch (Exception e) {
        return wrapError(e);
    }
});
```

```java
source.flatMap(v -> asyncProcess(v)
    .onErrorResume(e -> Mono.just(wrapError(e)))
);
```

Keep in mind that a source that emits `onError` is **terminated**, per the spec. If you expect exceptions in some of the lambdas you provide, it is up to you to recover from them **within the lambda** in order to prevent termination of the sequence.

(note that in that regard `onErrorContinue` is an _unsafe_ advanced operator which goes around the spec)

**Comment by pavelkuchin** [comment]
Hi @simonbasle, thank you for the detailed answer. Our case is a complex processing chain with multiple steps leading to the final result (or error). Almost every step potentially can throw an exception. It is possible to do exception handling on step level (in lambda) but it will require considerable amount of boilerplate code (i.e. catching exceptions, passing wrapper object instead of value, additional logic which would skip steps if previous triggered an error). My hope was to avoid the boilerplate and handle all the exceptions in one shot. Since there is already onErrorContinue which goes around the spec, do you think it is possible to extend it / add new method which would follow current onErrorContinue pattern with ability to emit exception wrapper instead of dropping the element? When you are saying that onErrorContinue is unsafe, do you mean that it is not supported by all operators (and it is safe if used with supporting operators), or there are some other caveats?

**Comment by simonbasle** [comment]
`onErrorContinue` is not supported by all operators, doesn't compose with `Publisher` other than a subset of reactor-core ones, and isn't really an operator at all (ie. it _influences_ operators UPSTREAM of it to deal with errors raised in `onNext` in a very very generic way). Even if we wanted to extend this pattern (which we don't), we couldn't because of the fact that the `Consumer` is specifically one that deals will _any_ `Object` (as it serves all the upstream operators that are compatible with error mode continue).

You have more requirement around how to represent the error to your users, so you will need to write that boilerplate, which is actually business logic.

**Comment by pavelkuchin** [comment]
Thank you for the clarification and your time. Closing the ticket.
