### ISSUE TITLE
Add timeout functionality to retry

### ISSUE THREAD

**Issue by PyvesB** [reactor/reactor-core#2092]
## Motivation
This is somewhat related to https://github.com/reactor/reactor-addons/pull/222. We want to improve our monitoring and simplify our error handling code.

We have configured a `Retry` object, but we only want to retry for at most X seconds and be able to tell how many retry attempts have happened by then. This number of attempts is not known in advance given that retrying may include a random backoff with jitter, or the operation we want to retry may take a variable amount of time.

In https://github.com/reactor/reactor-addons/pull/222#issuecomment-593872082, @simonbasle suggested using `onRetryExhaustedThrow`, but what I hadn't quite clocked when reading through the new functionality is that timeout support is missing.

## Desired solution

Defining timeouts in the `Retry` object, as in reactor-extra:
```
Retry retry = Retry.timeout(X). ...
```

However, the `timeout` in reactor-extra is only evaluated at the beginning of a new attempt, so the attempt would not be aborted if an operation takes more than the defined retry time. It isn't an actual timeout, but rather a "don't retry any further if previous retries took more than X seconds". Having a proper timeout that may abort an operation in progress would be more useful.

## Considered alternatives
The workaround we currently have is along the following lines:
```
AtomicInteger attempts = new AtomicInteger();
...
somePusblisher
  ...
  .doOnNext(n -> attempts.incrementAndGet())
  .doOnError(e -> attempts.incrementAndGet())
  .retryWhen(someRetry)
  .timeout(Duration.ofSeconds(X))
  .doOnError(e -> {
    int attemptCount = attempts.get();
    if (e instanceof TimeoutException) {
      // create more helpful exception message including attemptCount, similar to RetryExhaustedException
    }
    // use attemptCount for any other monitoring purposes
  })
  ...
```

Is there any other better way to achieve this with the current Reactor capabilities?

**Comment by simonbasle** [comment]
I'm not sure what that would exactly look like on a per-attempt basis...
What's a "per attempt timeout"? How is it different from a `.timeout` applied directly on the source ?
For the "global timeout", putting the `.timeout()` after the whole `retryWhen` is the way to go IMHO (as it is not tied to a particular attempt)

**Comment by PyvesB** [comment]
> I'm not sure what that would exactly look like on a per-attempt basis...
> What's a "per attempt timeout"? How is it different from a `.timeout` applied directly on the source ?

Yes, a timeout could also be put upstream in the reactive chain. That was just a suggestion in passing and was not meant to sidetrack the discussion, I've removed the small bit about it in the feature request. :)

> For the "global timeout", putting the `.timeout()` after the whole `retryWhen` is the way to go IMHO

That works, however, the code is less concise and requires creating things such as `AtomicInteger` counters outside the reactive chain to keep track of the number of attempts, as illustrated by my code above. Compared to reactor-extra's API if it had included my PR, that's at least 7 or 8 additional lines of code. Not the end of the world, but worth raising this improvement request IMHO.

> (as it is not tied to a particular attempt)

Here's a different way of viewing things: `public static RetrySpec max(long max)` is not tied to a particular attempt either, but it considers them as a whole. `public static RetrySpec timeout(Duration duration)` would simply be a cap on the total duration rather than the total count. 😉

**Comment by simonbasle** [comment]
there is a major limiting factor for achieving what you want : the operator only provides the meta-information at points in time where the source has emitted `onError`. the companion publisher tells nothing about successful retries. So whatever the case, you won't be able to get the number of attempts from the operator in the case of a timeout (be it with core's `RetrySpec` or addons' `Retry` builder)

looking at the addons implementation of `timeout`, it is a bit clunky as well, because it relies on the fact that there is a pre-computed backoff, computes a timestamp for the "timeout" and only triggers the timeout if A) the source fails and B) the computed backoff for that failure would trigger a delayed retry past the timestamp that was initially computed.

I could add something equivalent like `onMaxBackoffThrow` to the `RetryBackoffSpec`, but I'm less and less convinced this pattern is that useful compared to putting timeouts upstream and downstream of retryWhen.

Note that one way to increment the `AtomicInteger` would be to use the `doOnRetry` handler of the `Retry[Backoff]Spec`. However the `AtomicInteger` should be tied to a single subscription to the whole retried `Flux` by wrapping all that chain you have in a `Flux.defer`.

**Comment by PyvesB** [comment]
Okay, thanks for looking into it and sharing your point of view, it makes sense. Feel free to close if you think no neat solution can be achieved in the `Retry` object. I've taken note of the `doOnRetry`, that will simplify things a little!

**Comment by simonbasle** [comment]
I'll keep this issue open in the backlog, if an elegant solution comes up. Worse case scenario you can explore what can be done by forking the `RetryBackoffSpec` in your codebase (right now it is `final` but a possible future enhancement would be to make both specs inheritable so that users can start from these to roll their own specs / builders / `Retry` custom functions)

**Comment by simonbasle** [comment]
We haven't been able to find an elegant way around the limitations exposed above. Closing this.

**Comment by simonbasle** [comment]
(Please feel free to reopen if you were able to write a PoC inspired by `RetryBackoffSpec`)
