### ISSUE TITLE
StepVerifier steps can execute out of order.

### ISSUE THREAD

**Issue by hearnden** [reactor/reactor-core#2139]
The `StepVerifier` API gives the appearance of a verifier that will run verification steps in the order they are declared.  e.g.:
```java
  .assertNext(cmd1)
  .then(cmd2)
  .assertNext(cmd3)
```
gives the appearance that `cmd1`, `cmd2`, and `cmd3` will run in order.  However, it appears that steps can sometimes run out of order.

## Expected Behavior
Verification steps should execute in-order.

## Actual Behavior
Verification steps execute out of order.

## Steps to Reproduce

Here's a concrete failing test case:
```java
  @Test
  public void testVerificationOrder() {
    var src = TestPublisher.<String>create();
    
    // Record the order in which verification steps execute.
    var steps = new ArrayList<Integer>();
    StepVerifier
        .create(src.flux())
        .then(() -> {
          steps.add(1);
          // Emit two items, then complete.
          src.next("", "");
          src.complete();
        })
        .assertNext(s -> {
          steps.add(2);
        })
        .then(() -> {
          steps.add(3);  // <-- This runs after the step below
        })
        .assertNext(s -> {
          steps.add(4);  // <-- This runs before the step above
        })
        .expectComplete()
        .verify();
    assertEquals(List.of(1, 2, 3, 4), steps);  // <-- Fails.  Steps = [1, 2, 4, 3]
  }
```

This is all with a single thread (main), no schedulers or multi-threading race conditions involved.

## Your Environment

* Reactor version(s) used: 
  - `reactor-core`: 3.3.2
  - `reactor-test`: 3.3.2

* Other relevant libraries versions: 
  - `reactive-streams`: 1.0.3

* JVM version (`javar -version`): OpenJDK 11.05

* OS and version (eg `uname -a`): MacOS 10.15.4

**Comment by simonbasle** [comment]
the expectations in `StepVerifier` are triggered whenever an async signal is notified to the `StepVerifier`. `then` steps are a bit different, and for historical implementation reasons can indeed be effectively reordered after the enclosing expectations (including `expectNext`, `expectComplete` and `assertNext`)... This is hard to change at this point, because the potential impact on existing tests from our users is difficult to measure (and IIRC this hasn't been raised as an actual issue before). The reordering was apparently necessary for `thenAwait()` and `thenCancel()` type of steps.

Note that the `then()` commands aren't reordered between them, only with expectation steps.

We'll try to revisit the internal implementation of the default `StepVerifier` and see if we can streamline that particular case while simplifying the implementation.

**Comment by simonbasle** [comment]
It appears evident that we won't be able to rework the `StepVerifier` enough to change that behavior, unfortunately.
