### ISSUE TITLE
Make Scheduler/TimeScheduler and their Worker/TimedWorker @FunctionalInterface

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#216]
It would be possible to add more default interface methods in order to support inlined scheduling implementations and more progressive API. Direct schedule, periodic schedule, worker periodic schedule can be provided.

**Comment by simonbasle** [comment]
Also merge `TimedScheduler` into `Scheduler`

 - [ ] default scheduled methods to REJECTED
 - [ ] all current implementation should use `ScheduledExecutorService`
 - [ ] remove the `now()` from the worker (duplicate and unused)
 - [ ] `Mono.delay` should use `parallel` by default

**Comment by simonbasle** [comment]
@smaldini the only remaining abstract methods are `schedule` and `createWorker`. What we could do is leave `createWorker` abstract and have all schedule methods delegate to `createWorker().schedule...`. Sub-optimal since you create a worker per invocation, but works.

Then `Worker` can be made functional interface by having all timed schedule methods return `REJECTED`, implement a default no-op `dispose()` and leave only simple `schedule(Runnable)` as  abstract.

I think we should add a `@implSpec` tag to hint that if you override `dispose()` you should strongly consider overriding `isDisposed()` too.

**Comment by simonbasle** [comment]
After discussing it further with @smaldini, this doesn't bear enough benefits compared to the risk of abusing the functional interface for anything other than tests. It would become far too easy to produce an unreliable or incomplete `Scheduler`, which is too important an interface to mess up.

We could consider putting a simplified `Scheduler`-building facility like this for tests in `reactor-test` if there is some demand for it, though.
