### ISSUE TITLE
Metrics should record onError exception's toString rather than just class name

### ISSUE THREAD

**Issue by aneveu** [reactor/reactor-core#2305]
When recording the onError tag, the exception tag is created by using the class name of the exception. Using the `toString` method would be more relevant.

**Comment by simonbasle** [comment]
I'm wondering about that one. Metrics != logs, so I wonder if the original behavior made more sense from an "aggregated view" perspective. ie. people would be more interested in having the class name of the exception rather than the message, because they want to aggregate by "class of failure" where messages could vary from a particular instance to another (eg. `NullPointerException`s are bound to have a ton of variation in messages, but one probably is more interested in how many NPE occurred?).

wdyt @shakuzen ? would you expect recording of failure path to include the exception's message as a tag?

**Comment by shakuzen** [comment]
I think it will be hard for Reactor to make the decision to use the exception's message in a metric tag and ensure bounded cardinality on those metrics. For some set of exception messages it might be reasonable, but I could imagine user-made exception messages including unique IDs, for example, which would result in unbounded cardinality for the metric time series.

**Comment by simonbasle** [comment]
yeah, that must be why I initially elected to only tag with the exception's class name. Ok closing this then 👍
