### ISSUE TITLE
Challenge the `contextWrite` name: can we find better verb than write?

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2321]
## Motivation
There could be a better name for the new `contextWrite` operator to convey that this is a "write on an immutable object which results in another immutable object being returned and visible from upstream".

## Additional context
`write` suffix was chosen because other alternatives (mutate, append, etc...) didn't convey the immutable aspect of `Context` any better, so simplest least surprising word was deemed the best.

## Challenges
`warn/api-change`: If we choose a new name, it has to be objectively better because that would be another breaking API change between M2 and RC1.

**Comment by UgiR** [comment]
Maybe something like 'interpose' : "place or insert between one thing and another".. operator changes the context between itself and the upstream..

I don't know, I might still prefer contextWrite because it more clearly conveys the general spirit of the operator without needing to own a dictionary. Just an idea.. 🤷‍♂️

**Comment by simonbasle** [comment]
Since a more adequate name couldn't be found on time, and since my personal preference of keeping `contextWrite` seems to be shared by at least one user (thanks for chiming in @UgiR 😄), we'll keep that one.
