### ISSUE TITLE
Add support for validation function in Mono.cache

### ISSUE THREAD

**Issue by a701440** [reactor/reactor-core#2324]
When specified call a custom function to validate the cached value before returning. When value is not valid obtain a new value from the source is if it was not cached. Can be useful for caching connections and checking if the connection is still open before returning.

**Comment by simonbasle** [comment]
stretch goal, this could be interesting indeed maybe in 3.4.0

**Comment by ericbottard** [comment]
The more I look at this, the more I feels like it departs from the original spirit (and I guess, implementation) of `Mono.cache()`. Wouldn't this be better handled by eg `Mono.create()` with a stateful callback or something?

**Comment by a701440** [comment]
I ended up with a fairly verbose code handling RabbitMQ connection, would be much nicer if something more "compact" was available. Also you guy have custom TTL provider function for Mono.cache it's called once when value/error becomes available and there is no easy way to "flush" the cache if needed, recompute the TTL after the fact, etc.

The code I ended up with sing Mono.create, which works OK is below. 
In Reactor-rabbit integration code guys just use mono.cache and it causes closed connection to be cached and returned indefinitely under some circumstances.

    public static Mono<Connection> connectionMono(final ConnectionFactory connectionFactory, String connectionName) {
        ConnectionHolder connectionHolder = new ConnectionHolder();
        Mono<Connection> result = Mono.create(sink -> {
            try {
                Connection conn;
                synchronized (connectionHolder) {
                    Connection existingConn = connectionHolder.connection;
                    if (existingConn != null && existingConn.isOpen()) {
                        conn = existingConn;
                    } else {
                        Connection newConn = connectionFactory.newConnection(connectionName);
                        connectionHolder.connection = newConn;
                        conn = newConn;
                    }
                }
                if (conn == null) {
                    sink.error(new RuntimeException("Failed to create RabbitMq connection"));
                }
                sink.success(conn);
            } catch (Exception e) {
                sink.error(e);
            }
        });
        return result;
    }

    static class ConnectionHolder {
        Connection connection;
    }

**Comment by acogoluegnes** [comment]
The need in the context of Reactor RabbitMQ would be able to skip the caching all-together, with a condition based on the value. This is for this [kind of code](https://github.com/reactor/reactor-rabbitmq/blob/cd8ef36f46173ebdd7a12acfbf6acaa52dc83b53/src/main/java/reactor/rabbitmq/Sender.java#L112-L114
):

```java
cm = cm.doOnNext(conn -> connection.set(conn))
  .subscribeOn(this.connectionSubscriptionScheduler)
  .transform(this::cache);

...

protected <T> Mono<T> cache(Mono<T> mono) {
  return Utils.cache(mono);
}

... 
(Utils class)

public static <T> Mono<T> cache(Mono<T> mono) {
return mono.cache(
  // cache success
  element -> Duration.ofMillis(Long.MAX_VALUE),
  // do not cache failures (allows retry to work)
  throwable -> Duration.ZERO,
  // do not cache empty
  () -> Duration.ZERO);
}
```

We'd like to not use the cache at all (making the operator a pass-through) if the `Connection` is an instance of `RecoverableConnection`.

**Comment by OlegDokuka** [comment]
@simonbasle it is sound exactly to what we implemented at RSocket -> https://github.com/rsocket/rsocket-java/blob/master/rsocket-core/src/main/java/io/rsocket/core/ReconnectMono.java.

Tests to grasp the idea -> https://github.com/rsocket/rsocket-java/blob/master/rsocket-core/src/test/java/io/rsocket/core/RSocketReconnectTest.java#L41
(FYI, ReconnectMono is used underneath in that test)

**Comment by simonbasle** [comment]
@OlegDokuka how would you envision the API if `ReconnectMono` was added to core, eg. in the `Connection` case above?

**Comment by rstoyanchev** [comment]
@simonbasle given how this is [configured in RSocket](https://github.com/rsocket/rsocket-java/blob/7f3da28d607cd0604767b6dae00240bf9c095436/rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java#L684) I would say it's some combination of `Retry` plus a [callback](https://github.com/rsocket/rsocket-java/blob/7f3da28d607cd0604767b6dae00240bf9c095436/rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java#L81-L82) for the cached item `<T>` to be invalidated based on an external event (e.g. connection closed), plus a `Consumer<T>` to invalidate the cached item when the `Mono` is terminated due to other reasons.

BTW I believe this can also be of use for R2DBC as well around the use of connections.

**Comment by simonbasle** [comment]
so far it seems we have three seemingly close use cases, but they have enough differences that trying to come up with a unifying API is challenging:

 1. the original "Each late subscriber needs to trigger a check of the cached value, like `Connection#isValid()`" case (@a701440)
 2. the refined "Each subscriber should be able to detect an issue with the `Connection` and atomically flush the cache" case (from @philsttr)
 3. the "Cached value itself can notify it has become invalid, which must be converted to a cache flush" case (from @OlegDokuka)

2 and 3 are pretty close although 2) would probably require users to still write _some_ boilerplate to guarantee that downstream operators can access the flush trigger somehow, while resetting said trigger every time a new value is stored in the cache.
3) doesn't need it because the value itself stores / is the flush trigger.

1 is quite unique in the sense that it needs the cache operator to apply the `Predicate` each time 1 (or a concurrent batch of) subscriber registers _after_ the cache has been populated. Also, it implies that a miss on the predicate triggers a resubscription to the source (whereas in the two other cases, we wait for the next incoming subscription, which is more "natural").

**Comment by simonbasle** [comment]
here are my API ideas and a demonstration of how it would look like to reuse the most generic API, which is 3):

### all three cases with tailor-made approaches
```java
  // 1): public Mono<T> cacheUntil(Predicate<? super T> validationForLateSubscribers)

		Mono.fromCallable(Connection::new)
				.cacheUntil(Connection::isValid) //very specific to 1)
                //simulate usage
				.flatMapMany(co -> co.runQuery());

  // 2: public static interface Flushable<T> {
  //		void flush();
  //		T get();
  //	}
  //
  //public Mono<Flushable<T>> cacheAndWrap()

		Mono.fromCallable(Connection::new)
				.cacheAndWrap() //very specific to 2)
				//simulate normal usage of the connection which may detect a failure at any time
				.flatMapMany(flushableConnection -> flushableConnection.get().runQuery()
						.map(i -> {
							if (i == 5) {
								//something went wrong !
								flushableConnection.flush();
								return "FALLBACK";
							}
							return "value" + i;
						})
				);

  // 3): public Mono<T> cacheUntilOther(Function<? super T, Mono<Void>> cacheFlushingGenerator)

		Mono.fromCallable(RSocket::new).cacheUntilOther(RSocket::onClose) //can be adapted for 1 and 2
                //simulate usage
				.flatMapMany(rsocket -> rsocket.runQuery());
```

### Using API 3) to tailor other cases
```java
		AtomicReference<Sinks.Empty<Void>> flushTriggerHolder = new AtomicReference<>();
		Mono.fromCallable(Connection::new)
				.doOnSubscribe(sub -> flushTriggerHolder.set(Sinks.empty()))
				.cacheUntilOther(c -> flushTriggerHolder.get().asMono())
				.map(v -> {
					//this allows us to validate v each time the _cache_ is subscribed to
					if (!v.isValid()) {
						//intentionally ignores errors, FAIL_TERMINATED is desirable for idempotency
						flushTriggerHolder.get().tryEmitEmpty();
						//we'll want to detect this invalidation and resubscribe. best best at that point is retry()
						//we'd probably want a more specific exception type, like a business exception
						throw new IllegalStateException("the object in cache is now invalid");
					}
					return v;
				})
				.retryWhen(Retry.indefinitely().filter(t -> t instanceof IllegalStateException))
				.flatMapMany(co -> co.runQuery());

		AtomicReference<Sinks.Empty<Void>> flushTriggerHolder = new AtomicReference<>();
		Mono.fromCallable(Connection::new)
				//each time the original source gets subscribed, we recreate what will serve as the trigger
				.doOnSubscribe(sub -> flushTriggerHolder.set(Sinks.empty()))
				.cacheUntilOther(c -> flushTriggerHolder.get().asMono())
				//simulate normal usage of the connection which may detect a failure at any time
				.flatMapMany(co -> co.runQuery()
					.map(i -> {
						if (i == 5) {
							//something went wrong !
							//intentionally ignores errors, FAIL_TERMINATED is desirable for idempotency
							flushTriggerHolder.get().tryEmitEmpty();
							return "FALLBACK";
						}
						return "value" + i;
					})
				);
```

### Alternative API where we get a `Disposable` rather than provide a `Mono<Void>`
That one is immediately clunkier for 3) and not that better for 1 nor 2...

```java
public Mono<T> cacheFlushable(BiConsumer<T, Disposable> triggerListener)

Mono.fromCallable(RSocket::new)
    .cacheFlushable((rsocket, trigger) -> rsocket.onClose().then(Mono.fromRunnable(trigger::dispose)).subscribe())
    .flatMapMany(rsocket -> rsocket.runQuery());
```

```java
		AtomicReference<Disposable> flushTriggerHolder2 = new AtomicReference<>();
		Mono.fromCallable(Connection::new)
				.cacheFlushable((value, flushTrigger) -> flushTriggerHolder2.set(flushTrigger))
				.map(v -> {
					//this allows us to validate v each time the _cache_ is subscribed to
					if (!v.isValid()) {
						//intentionally ignores errors, FAIL_TERMINATED is desirable for idempotency
						flushTriggerHolder2.get().dispose();
						//we'll want to detect this invalidation and resubscribe. best best at that point is retry()
						//we'd probably want a more specific exception type, like a business exception
						throw new IllegalStateException("the object in cache is now invalid");
					}
					return v;
				})
				.retryWhen(Retry.indefinitely().filter(t -> t instanceof IllegalStateException))
				.flatMapMany(co -> co.runQuery());

		AtomicReference<Disposable> flushTriggerHolder2 = new AtomicReference<>();
		Mono.fromCallable(Connection::new)
				.cacheFlushable((value, flushTrigger) -> flushTriggerHolder2.set(flushTrigger))
				//simulate normal usage of the connection which may detect a failure at any time
				.flatMapMany(co -> co.runQuery()
					.map(i -> {
						if (i == 5) {
							//something went wrong !
							//intentionally ignores errors, FAIL_TERMINATED is desirable for idempotency
							flushTriggerHolder2.get().dispose();
							return "FALLBACK";
						}
						return "value" + i;
					})
				);


```

**Comment by simonbasle** [comment]
for the invalidation `Predicate`, the "quality" of the `Predicate` can heavily influence the behavior of the operator. For instance, how do you envision the behavior in the following cases @a701440 (cc @robotmrv, @Rostom35 since you upvoted):

	1. the predicate is always false, leading to continuous re-subscription
	2. the objects tested can be created in a state where the predicate would consider it invalid from the beginning (again, leading to potentially continuous re-subscription)
	3. what if the object becomes invalid atomically in the time between the predicate is applied and the time the value is emitted to the downstream subscribers (ie the operator cannot guarantee that the object visible downstream is valid, it can only guarantee that once a cached object is _known_ to be invalid the cache will be cleared)
	4. the predicate alternates between true and false on each call (ie it returns a value that depends on the number of applications/subscribers rather than the actual state of the stored object)


on one hand I get the feeling that using such a method, despite the predicate, tends to mean "I want to get an object that is valid" from the user experience perspective, but I think the argument can be made in favor of "predicate not passing = error propagated to currently registered subscribers" and then leaving retries in the hands of users (which can be fine tuned for each subscription)

**Comment by a701440** [comment]
IMO, a variant where Predicate returning false propagates an error which can be dealt with in retry and so can cause a new subscription and a new cached value is a decent option. The "invalid" value would have to be passed down in the error, etc.

I am not sure if a library can really do anything meaningful about bad Predicate code which does not behave according to the contract.

**Comment by simonbasle** [comment]
> I am not sure if a library can really do anything meaningful about bad Predicate code which does not behave according to the contract.

@a701440 that sounds reasonable

regarding the behavior of the `cacheInvalidateIf(Predicate<T>)` operator, how about this:
 1. upon receiving the value from upstream, all accumulated subscribers will receive the value **no matter what** => predicate is not triggered at that point.
 2. the first extra subscriber that registers after that will trigger the predicate
   - if predicate passes: invalidate. a resubscription happens and we're back to case (1) above
   - if predicate doesn't pass: valid object, the new subscriber gets it

would that seem acceptable to you?

Note that I've worked with the interpretation that `Predicate.test(v) == true` means **`v` is invalid** (so that the operator reads logically: `cacheInvalidateIf(somePredicate.test(value) == true)`, which also allows the naming to nicely align with the `invalidateWhen` logic).
