### ISSUE TITLE
Add `cache` operator

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#25]
In spring-reactive [WebSessionManager](https://github.com/spring-projects/spring-reactive/blob/d95638ac5ea802bcfa064067d9bfc783086efec7/src/main/java/org/springframework/web/server/session/WebSessionManager.java#L36) returns a `WebSession`. In turn that's used from [ServerWebExchange.getSession()](https://github.com/spring-projects/spring-reactive/blob/2294cd217ee0ea889f7a1e80d14e40b7e47eaa6d/src/main/java/org/springframework/web/server/adapter/DefaultServerWebExchange.java#L81-L92) such that multiple calls to `getSession()` should always return the same `Mono` and that should provide the same `WebSession` instance to all subscribers.

I think this is a common pattern to lazily initialize a class field such as a Mono and/or Flux where all subscribers should get the same values.

**Comment by smaldini** [comment]
Some context:

It's only Mono we're talking about, cache is somewhat complicated due to the implication it turns lazily a source sequence into a shared state replayable sequence.

In `Stream` we use `Stream#multicast(EmitterProcessor.replay(history)).autoConnect()`. The whole point of `multicast + autoconnect` is to share a reference processor and coordinate the subscribe so it happens safely once upstream on first subscribe downstream.

For `Mono`, due to the nature of its volume things can be much simpler. Actually that's the point of `Promise`, caching and sharing one deferred scalar value.

**Comment by smaldini** [comment]
There are also 2 cache points we can use: 
- Cache on receiving side as in `Stream#cache` that will preserve current and late subscribers from requesting or subscribing the decorated source.
- Cache on producing side, a sort of cached `Mono#defer` that will only preserve late subscribers from subscribing the decorated source.

**Comment by rstoyanchev** [comment]
Yes a cache on Mono would suffice for me.
