### ISSUE TITLE
 Pool#acquire(Duration) has been pending for more than the configured timeout of 4500ms

### ISSUE THREAD

**Issue by aninja8** [reactor/reactor-core#2544]
I have a use case where I have to make API calls from a flux iterable based on an inbound HTTP request. When I make several parallel calls, I end up with ` Pool#acquire(Duration) has been pending for more than the configured timeout of 4500ms`

I know this has been reported earlier but I am using the `2.4.1` version of the spring boot jar. (latest?)

I also set the `pendingAcquireMaxCount` as -1 and as per the documentation, it means there should be no upper bound on the requests so I wasn't expecting this time out.

I also notice blockhound reporting a blocking call in `BodyExtractors`. Log attached in the minimum reproducible.

## Expected Behavior
Get queued without exception/ backpressure on the constrained connection resource

## Actual Behavior
After a while, I start seeing the ` Pool#acquire(Duration)` exception. 

https://github.com/aninja8/hello-world-reactor/blob/master/log.txt

## Steps to Reproduce
https://github.com/aninja8/hello-world-reactor

> 
> Flux.fromIterable(nums) // Mocking operation to retrieve a list based on the incoming request
>                 .publishOn(Schedulers.fromExecutor(serviceOpsExecutor))
>                 .flatMap(i->{
>                    return callService(); // Mock service call
>                 },5)
>                 .subscribe();
>  

Steps and issue are detailed in the read me

## Environment

- java version "1.8.0_191"
- Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
- Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
- `2.4.1` version of spring boot.

**Comment by simonbasle** [comment]
you mention `pendingAcquireTimeout(-1)`, yet right next to where you configure that you also do `pendingAcquireTimeout(Duration.ofMillis(4500))`...

you have:

 1. a budget of at most 30 connections live at the same time
 2. attempts to acquire more than 30 will "park" the attempts (no limit on how many can be parked, that's `pendingAcquireMaxCount(-1)`)
 3. parked attempts can only stay parked for 4.5 seconds otherwise an error will be triggered (that's `.pendingAcquireTimeout(Duration.ofMillis(4500))`)

you are doing 1000s of webclient calls via the `flatMap` in `doSomethingAsync`. at a minimum, thanks to the default concurrency factor of `flatMap` of 256, it will fire 256 webclient calls to that URL, but only 30 of these can make progress... the others will be parked as in point 2. above.

the error you get seems to indicate one of these get parked for more than 4.5 seconds.

how reliable is the remote service? what's the latency like?

PS: it would have made more sense to open this issue in reactor-netty (or at worse on reactor-pool)...

**Comment by aninja8** [comment]
@simonbasle 

Thanks for looking at this and explaining. I understand it much better now.

However, I set the flat map concurrency as 5 overriding the default 256 and it shouldn't buffer too much was my expectation. 

Originally I was testing with a stub with configurable latency. This failed even for 2s latency.  The original service has great availability (99.9%) and I'd expect similar latency. 

We can look at increasing the timeout but is there any way to backpressure and not pull more elements if the queue is full or when the timeout happens? (I was expecting this to happen automatically before setting pendingAcquireMaxCount(-1)) 
I can close this and post this in reactor-netty if it would help.

**Comment by simonbasle** [comment]
mmh I missed the concurrency factor of `5` being set. that said, I just had a better look at the logs and here is your explaination I think: `Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/202.83.24.6:53] query via UDP timed out after 5000 milliseconds (no stack trace available)`

**Comment by aninja8** [comment]
@simonbasle just checking again to see if you have any suggestions

**Comment by simonbasle** [comment]
I don't. I would look into the DNS timeout, which sounds like a possible root cause. 5s DNS timeout and 4.5s pendingAcquireTimeout sound too close to be a coincidence.

Backpressure is already accounted for, because the pendingAcquireTimeout starts counting down on first request on the `Mono` you get from `Pool#acquire`...

**Comment by alpamys-qanybet** [comment]
@aninja8, @simonbasle, @dittos, @subbarao, Hi there everyone, I also have this problem in a project, spring-boot 2.3.8.RELEASE, reactor-netty 2.3.8.RELEASE - Jan 15, 2021, facing 2.3.8.RELEASE - Jan 15, 2021, can someone explain how to fix it? Maybe update reactor-netty or spring-boot? Maybe do some settings as mentioned above. Need help.

**Comment by alpamys-qanybet** [comment]
@aninja8, @simonbasle, @dittos, @subbarao, Hi there everyone, I also have this problem in a project, spring-boot 2.3.8.RELEASE, reactor-netty 2.3.8.RELEASE - Jan 15, 2021, facing 2.3.8.RELEASE - Jan 15, 2021, can someone explain how to fix it? Maybe update reactor-netty or spring-boot? Maybe do some settings as mentioned above. Need help.
