### ISSUE TITLE
Completed Flux used in Zip still gets cancelled

### ISSUE THREAD

**Issue by WouterBancken** [reactor/reactor-core#2550]
## Expected Behavior
A Flux that has been completed (`doOnTerminate` triggered) should not be cancelled anymore (`doOnCancel` should not trigger) if it's used in a `zip` or `zipWith` operation. 

## Actual Behavior
Both `doOnTerminate` and `doOnCancel` get called for the same Flux that is used in a `zip` or `zipWith` operation.

## Steps to Reproduce
Example with `zip`:

```java
Flux.zip(Flux.range(0, 12)
                        .doOnNext(System.out::println)
                        .doOnTerminate(() -> System.out.println("Terminate"))
                        .doOnCancel(() -> System.out.println("Cancel"))
                , Flux.interval(Duration.of(1, ChronoUnit.SECONDS)))
                .takeUntil(v -> v.get(0) == Long.valueOf(10))
                .subscribe();
```

Example with `zipWith`
```java
Flux.range(0, 12)
                .doOnNext(System.out::println)
                .doOnTerminate(() -> System.out.println("Terminate"))
                .doOnCancel(() -> System.out.println("Cancel"))
                .zipWith(Flux.interval(Duration.of(1, ChronoUnit.SECONDS)))
                .takeUntil(v -> v.get(0) == Long.valueOf(10))
                .subscribe();
```

The output for both is 

```
0
1
2
3
4
5
6
7
8
9
10
11
Terminate
Cancel
```

## Your Environment
~The issue started occurring since release 3.3.12.RELEASE and is caused by https://github.com/reactor/reactor-core/issues/2519~

~Before [issue 2519](https://github.com/reactor/reactor-core/issues/2519) cancel wasn't called since the Flux was already completed `(l == null)`.~

* Reactor version(s) used: 3.3.12.RELEASE
* Other relevant libraries versions (eg. `netty`, ...): /
* JVM version (`java -version`): 11
* OS and version (eg `uname -a`): MacOS

**Comment by simonbasle** [comment]
Two interesting things to observe here:
 1. the range is producing immediately. that is due to `zip`'s inner doing a prefetch of 32 elements (which are stored in a queue), resulting in an immediate termination of the `range`
 2. the spec allows "cancel() after onComplete()", but that cancel is supposed to be no-op (https://github.com/reactive-streams/reactive-streams-jvm#1.6 and https://github.com/reactive-streams/reactive-streams-jvm#3.7)

`doOnCancel` is pretty naive in that regard though, and doesn't really check for a previous termination signal before triggering its `Runnable`.

we could try to be more conservative in zipInner.cancel and try to avoid propagating the cancel to the actual source if said source has terminated, but we'd need to be super careful due to the prefetch above.

in general, due to point 2, Reactor operator have `cancel()` implementations that are idempotent so they don't necessarily bother checking for preceding termination.

NB: The issue you mentioned was only targeting the `collect` operator. I just tested with `3.3.11.RELEASE` and the same happens, it has nothing to do with that fix. Zip has actually probably behaved that way since the beginning.

**Comment by simonbasle** [comment]
There could still be valid use cases for `doOnCancel` triggering in that sort of case. I think the best way forward for you is to use `doFinally`, which IIRC will let only one of the three possible end signals trigger the handler (either cancelled, onComplete or onError).
