### ISSUE TITLE
onErrorContinue: limit of 256 errors in conjunction with Spring WebClient

### ISSUE THREAD

**Issue by PMacho** [reactor/reactor-core#2562]
## Expected Behavior

onErrorContinue() should work for more than 256 errors.

## Actual Behavior
onErrorContinue() blocks the Publisher after 256 errors, in case Flux.flatMap(...) is used to call Spring WebClient.

## Steps to Reproduce
Referencing to https://github.com/reactor/reactor-core/issues/2011 the following now fails (as expected):

```java
    @Test
    public void repoCase() throws InterruptedException {
        int numberOfRequests = 500;
        Set<Integer> sink = new HashSet<>();

        Flux
                .fromStream(IntStream.range(0, numberOfRequests).boxed())
                .map(sink::add)
                .flatMap(i -> Mono.error(new Exception("any")))
                .onErrorContinue((throwable, o) -> {})
                .subscribe();

        Thread.sleep(1000);
        Assertions.assertNotEquals(numberOfRequests, sink.size());
        Assertions.assertEquals(256, sink.size());
    }
```

However, slightly modifying this, e.g. calling the Spring WebClient to a non-existing URI (in our production system we saw the same with 5xx server errors, in combination with `Mono.retryWhen(...)` until a RetryExhaustedException was thrown), still lets the publisher stop publishing after 256 `onError` signals.

```java
    @Test
    public void repoCaseWebClient() throws InterruptedException {
        int numberOfRequests = 500;
        Set<Integer> sink = new HashSet<>();

        Flux
                .fromStream(IntStream.range(0, numberOfRequests).boxed())
                .doOnNext(System.out::println)
                .map(sink::add)
                .flatMap(i -> webClientBuilder.build().get().uri("http://not-existing").exchange().doOnError(System.out::println))
                .onErrorContinue((throwable, o) -> {System.out.println(throwable.getMessage());})
                .subscribe();

        Thread.sleep(1000);
        Assertions.assertNotEquals(numberOfRequests, sink.size());
        Assertions.assertEquals(256, sink.size());
    }
```
 I added some `System.out`s for clarification. Interestingly, the error of `RequestHeadersSpec.exchange()` appears only once in the **stdout**. 

## Your Environment

* reactor-core version used: 3.3.10
* spring-webflux version: 2.2.10
* reactor-netty version: 0.9.12
* JVM version (`java -version`): 1.8.0_232
* OS and version (eg `uname -a`): Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

**Comment by simonbasle** [comment]
I couldn't reproduce the issue with pure reactor code. There are several puzzling things about this piece of code, but I guess they are minor (why use an `InStream` instead of `Flux.range`? why `map` to a boolean by adding to a `Set`? hopefully the `Set` is only for testing purposes in the first place, since it is shared state...)

As a side note, are you aware that `onErrorContinue` is quite different from a lot of operators and not guaranteed to work with all combinations? (although if it is not compatible with a given operator, that operator should simply continue emitting a terminal `onError`)

We generally recommend to deal with errors inside the `flatMap` lambda via `onErrorReturn`/`onErrorResume` instead.

**Comment by PMacho** [comment]
@simonbasle Thanks for your answer.

I can't reproduce the issue with pure reactor either. Are you suggesting to post this issue in spring-webflux repository? 
I am not sure if that would be a better place. As you mentioned, the javadoc of `onErrorContinue` says "Let compatible operators upstream recover". It is however not really clear what "compatible" means, at least it is not clear to me. The `WebClient` produces a `Mono`, which I assumed can be considered compatible.

I didn't entirely get that "although if it is not compatible with a given operator, that operator should simply continue emitting a terminal `onError`".

Considering the test code, I just wanted to stay as close a possible to the original issue. I fixed it for the next examples.
 
I am aware of the `onErrorReturn`/`onErrorResume` methods. However, both methods usually require knowledge about the actual content of the reactive pipeline. In my concrete use case, I am implementing a general workflow for an infinite subscription to a messaging system, that should never stop and can be configured later. The main purpose of `onErrorContinue` is to make sure, the workflow never stops.

I continued playing a bit with the test code, and found further interesting, yet (by me) not expected behaviour. The following does not block the pipeline, which is expected:

```java
    public void repoCaseWebClient() throws InterruptedException {
        int numberOfRequests = 500;
        Set<Integer> sink = ConcurrentHashMap.newKeySet();

        Flux
                .range(0, numberOfRequests)
                .doOnNext(sink::add)
                .flatMap(i -> webClientBuilder
                        .build()
                        .get()
                        .uri("http://not-existing")
                        .exchange()
                        .onErrorResume(throwable -> {
                            System.out.println("hit");
                            return Mono.empty();
                        })
                )
                .subscribe();

        Thread.sleep(1000);
        Assertions.assertNotEquals(numberOfRequests, sink.size());
        Assertions.assertEquals(256, sink.size());
    }
```

Adding `onErrorContinue` again blocks the pipeline since `onErrorResume` isn't invoked at all:

```java
    public void repoCaseWebClient() throws InterruptedException {
        int numberOfRequests = 500;
        Set<Integer> sink = ConcurrentHashMap.newKeySet();

        Flux
                .range(0, numberOfRequests)
                .doOnNext(sink::add)
                .flatMap(i -> webClientBuilder
                        .build()
                        .get()
                        .uri("http://not-existing")
                        .exchange()
                        .onErrorResume(throwable -> {
                            System.out.println("hit");
                            return Mono.empty();
                        })
                )
                .onErrorContinue((throwable, o) -> {
                    System.out.println(throwable.getMessage());
                })
                .subscribe();

        Thread.sleep(1000);
        Assertions.assertNotEquals(numberOfRequests, sink.size());
        Assertions.assertEquals(256, sink.size());
    }
```

I may have a wrong understanding of how reactor treats errors, but I expected the error handling of the inner sequence to be invoked before the outer sequences error handling.

**Comment by simonbasle** [comment]
`onErrorContinue` bends around the Reactive Streams specification, and only a **subset** of Reactor core operators supports it. There is absolutely no guarantee that an opaque arbitrary `Mono` from a 3rd party supports it. Operators that do support it indicate so in their javadoc.

it is not really an operator, but rather writes a feature flag in the `Context`. Operators above it that know about the feature flag and have implemented a way to take it into account then detect it and activate an alternative codepath where they'll drop the error to the provided `Consumer` and `request(1)` from their source in places where they would have instead propagated `onError()` downstream.

**Comment by rstoyanchev** [comment]
This is probably just sample code but worth to point out that use of `.exchange()` without consuming of the body will leak the connection and eventually you'll run out of connections. The `exchange()` is also deprecated in 5.3.

**Comment by PMacho** [comment]
@simonbasle 
Thank you for clarification, got it now. So that means, it is actually known behaviour and not considered to be an issue? 
I was wondering if there isn't another way to implement `.onErrorContinue`, similar to `onErrorResume`, so it can actually see the `onError` signal and react on it directly, instead of depending on the implementation of each operator in the chain. I guess, I am missing the point why this isn't possible, however.
Anyways, I'll close this issue, still a bit disappointed about a method that works only sometimes. I guess, I am not the only one out there, having trouble to entirely get that right. 

@rstoyanchev 
Thank you for the comment. You are right this is just sample code. In production we usually use `.retrieve()`. Still it is good to know about possible connection leaks.

**Comment by simonbasle** [comment]
yeah, I understand that frustration and `onErrorContinue` is something I regret adding to be honest, at least in its current form where nothing at first glance designates it as a last resort / hack.

It was indeed made for the case of "long running `Flux` that should never stop", as a better performing alternative to doing all risky steps in `flatMap(v -> doRiskyStep(v).onErrorResume(helper::logThrowableAndReturnEmpty))`.

But since the Reactive Streams specification mandates that if a `Flux<T>` emits an `onError`, that `Flux` is terminated, there was no composition possible here: each and every operator implementation that can trigger an `onError` from an incoming `onNext` must "opt-in" into taking that scenario into account where it avoids signalling its downstream with `onError`, pushes the error in a side channel (the `Consumer`) and continue processing...

In a future version, we are thinking about changing the name of the pseudo-operator to better reflect its hacky /unsafe nature.

**Comment by PMacho** [comment]
@simonbasle 
Hmm ... if I got that right, it is just the specification that prohibits from something like:

```java 
Subscription s;

public void onError(Throwable t) {
   log.error("Uncaught error in reactive pipeline: ", t);
   s.request(1)
}
```

Maybe the following is possible? 
`onError`:

1. "Copy" the current state of the `Flux` say **original** to another `Flux` say **leftOver**.
2. Terminate **original**.
3. Continue with **leftOver**.

I can't judge if that is total nonsense. However, the specification wouldn't be violated and the program could continue doing its job.

**Comment by simonbasle** [comment]
that's litteraly `onErrorResume(t -> leftOver)` 😉

**Comment by PMacho** [comment]
Hmm, maybe I’m getting the wrong. I think, the problem is the state of the publisher. 

It could be arbitrarily complicated, e.g. the publisher could actually wrap around a subscription to a messaging system, like a broker, it could do some prefetching, maybe by utilizing a fifo queue ...

In the moment when `onError` is signaled, I was wondering how to reconstruct the state of the Flow, skip one element and continue.
I think, `retry` does something like that, besides the skipping.

**Comment by simonbasle** [comment]
And in that case the `Publisher` in question must encapsulate all that logic and is the only one aware that it turns internal errors into "reconstruct the state, skip one element and continue". It cannot emit `onError` at all, otherwise it would be malformed.

Some (again, not all) vanilla reactor-core operators do include that logic, except it must be opted in.
Pure Reactor chains of operators do enable one channel through which that opt-in can take place, the `Context`.
The `onErrorContinue` pseudo-operator is just convenience method to place the opt-in flag into the `Context`.

As for `retry`: the way it works is it sees an incoming `onError` from an arbitrary source `Publisher` and rather than propagate it downstream and terminate itself, it subscribes again to that source `Publisher`.

To be precise, `Publisher`s are generally lightweight and the actual logic is in the `Subscription` objects they create (which in reactor-core are also often a `Subscriber`).
So the `retry` sees an `onError` from the _Subscription_ it got from the source `Publisher` the first time around, and re-subscribes to the `Publisher`, which generates a new `Subscription`, replacing the original one.

**Comment by simonbasle** [comment]
Another fine point: in order for the "continue" approach to work, it must occur in the same operator that throws/catches the `Exception` and turns it into an `onError` (precisely **because it MUST refrain from generating that `onError` signal**). Once the `Exception` has been transmitted as an `onError` signal, there is no continuation possible: the next operator in the chain could `request(1)` all it wants, that `Subscription` is terminated.

So continuing cannot be achieved by composition (unlike eg. `onErrorResume`), hence the flag approach and the partial support.

**Comment by PMacho** [comment]
@simonbasle Thanks for all the clarification. I am still now and then wrapping my head around this thing. However, your comments made things it very clear.

**Comment by PMacho** [comment]
@simonbasle 
Maybe another approach: 
At the moment the reactive specification only knows about one type of failure, i.e. onError. This failure has very defined behaviour, that is cancelling the whole pipeline. Similar to checked and uncheck exceptions, one might think about a further type of error signal, e.g. onRuntimeError, that just stops processing the actual element but allows to continue processing the rest of the pipeline.
This would be a fundamental change, but feels cleaner, then trying to work around the reactive specification.

**Comment by simonbasle** [comment]
> Maybe another approach:

I don't think this approach is that practical, because it implies A) less interoperability with Reactive Stream publishers in the chain and B) a separate dedicated mechanism to choose which exception are `onError` and which are `onRuntimeError`.

We cannot assume "onRuntimeError" to be the default either, not without rewriting most if not all of the operators and underlying complex algorithms. At that point, this would almost be a different library.

Relying on the `Context` at least had the benefit of reusing an existing feature to configure the `continue` behavior.

**Comment by PMacho** [comment]
I agree, this would be a fundamental change and each and every `Subscriber` would need to implement `onRuntimeError`, thus producing a lot of work. However, it would "just" be an extension to the existing specification, and thus only extend and not alter existing code. Plus, at the moment all other implementations of reactive streams specification (as far as I know), have exactly the same problem, and may consider adapting.

Still, I totally understand that such a change is not the first choice and would imply huge amounts of investigation. So you may just interpret my message as a suggestion to think about, rather than a request. Finally, we all just want something that is robust, predictable, practical, clear and simple to use for all of us.

I think, the existing solution based on the context is rather ingenious. Yet, since there is no specification about such an operator, interoperability with other libraries is not given too.
Further, due to its nature, being a workaround, the implementation doesn't look very straight forward to me, no offence, just my very personal impression.

Regarding the default error mechanism, I am not sure if there is a need to assume something. Both could be co-existing and it would be up to the Subscription or any intermediate operator to decide which one to choose. Another possibility would be to just stick to `onError` and depending on the type of Exception (e.g. `extends RuntimeException`), decide which path to go. The letter would however imply altering existing  code, and might thus not be favourable.
