### ISSUE TITLE
Context propagation over ParallelFlux, how to propagate Context through each rails after .parallel() operator

### ISSUE THREAD

**Issue by AtticusLv** [reactor/reactor-core#2564]
## Motivation
Thanks to new feature for ParallelFlux class, it's easy to convert Flux to parallel operation.

But theres's no contextWrite operator in ParallelFlux. How to propagate context info after Flux.parallel() operator?

## Desired solution
such as below fake codes: 
```
        Flux.just(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
                .parallel(Schedulers.DEFAULT_BOUNDED_ELASTIC_SIZE)
                .runOn(Schedulers.boundedElastic())
                .contextWrite(context -> {
                    // put sth to context
                    return context;
                })
                .doOnNext(i -> log.info("current thread: {}", Thread.currentThread().toString()))
                .subscribe();
```

now I use below codes to operate reactor Context
```
        Flux.just(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
                .parallel(Schedulers.DEFAULT_BOUNDED_ELASTIC_SIZE)
                .runOn(Schedulers.boundedElastic())
                .sequential()  // here is diff!!!
                .contextWrite(context -> {
                    // put sth to context
                    return context;
                })
                .doOnNext(i -> log.info("current thread: {}", Thread.currentThread().toString()))
                .subscribe();
```
using ParalleFlux.sequential() , Flux.contextWrite operator can be used. Is this changing to a synchronized world?

Any support is appreciated~

**Comment by AtticusLv** [comment]
Find sth interesting, I can use ParallelFlux.flatMap to inject other Flux operator into the parallel world. 
such as
```
Flux.just(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
                .parallel(Schedulers.DEFAULT_BOUNDED_ELASTIC_SIZE)
                .runOn(Schedulers.boundedElastic())
                
                .flatMap(i -> {
                    log.info("current thread: {}, item: {}", Thread.currentThread().toString(), i);
                    return Flux.just(i);
                })
                .sequential()
                .contextWrite(context -> {
                    // put sth to context
                    return context;
                })
                .subscribe();
```

it seems that the codes can fix my Context propagation issue. Any good advice?

**Comment by simonbasle** [comment]
Yeah, `parallel` has less operators, by nature focusing on the few one that are most adapted to be parallelized. In a non-blocking world, `parallel` is less needed because it is less problematic to start multiple lines of work on a common thread), so it is kind of a second class citizen in that regard.

Do you really need `parallel` at all? Wouldn't a `flatMap(v -> doSomething().subscribeOn(Schedulers.boundedElastic()))` work as well here?

> How to propagate context info after Flux.parallel() operator?

Keep in mind that `Context` is something attached to a conceptual subscription. the `Subscriber` **at the end** of the sequence bears it, and subscriber upward of it access it transitively. We usually summarize this by saying that "Context propagates from bottom to top". So it doesn't "propagate _after_" in any case.

**Comment by AtticusLv** [comment]
thanks for your tips~
