### ISSUE TITLE
Discrepancy between flatMap and concatMap prefetch

### ISSUE THREAD

**Issue by martin-tarjanyi** [reactor/reactor-core#2571]
## Expected Behavior
Based on the name of the input parameter I would expect that both concatMap and flatMap prefetch does the same: sets how many items it will request from its upstream.

## Actual Behavior
In case of concatMap this seems to the case and prefetch (also?) influences upstream request. However, in case of flatMap this value influences demand towards the inner publishers but has no impact on upstream request.

### FlatMap
```java
Flux.range(1, 3000)
        .log()
        .flatMap(a -> Mono.just(a), 10, Integer.MAX_VALUE)
        .blockLast();
```

Log
```
[ INFO] (main) | onSubscribe([Synchronous Fuseable] FluxRange.RangeSubscription)
[ INFO] (main) | request(10)
[ INFO] (main) | onNext(1)
[ INFO] (main) | onNext(2)
[ INFO] (main) | onNext(3)
[ INFO] (main) | onNext(4)
[ INFO] (main) | onNext(5)
[ INFO] (main) | onNext(6)
[ INFO] (main) | onNext(7)
[ INFO] (main) | onNext(8)
[ INFO] (main) | request(8)
...
```

### ConcatMap
```java
Flux.range(1, 3000)
        .log()
        .concatMap(a -> Mono.just(a), Integer.MAX_VALUE)
        .blockLast();
```

Log
```
[ INFO] (main) | onSubscribe([Synchronous Fuseable] FluxRange.RangeSubscription)
[ INFO] (main) | request(unbounded)
[ INFO] (main) | onNext(1)
[ INFO] (main) | onNext(2)
[ INFO] (main) | onNext(3)
[ INFO] (main) | onNext(4)
...
```

## Possible Solution

First of all I wonder why is the difference between the two.  I guess they work this way for a reason and it's not a bug but I wonder if documentation (or parameter naming) can be clarified to highlight the difference and maybe offer alternative for the other behaviour (inner prefetch vs upstream prefetch).

In case of concatMap documentation says `The prefetch argument allows to give an arbitrary prefetch size to the inner Publisher.` which is misleading for me.

In case of flatMap I was able to achieve the same using limitRate operator. However, based on its documentation it rather should be used for decreasing the request rate and I wonder if it just works for this use case accidentally. Is there any other way to increase the upstream request rate?
```java
Flux.range(1, 3000)
        .log()
        .limitRate(Integer.MAX_VALUE)
        .flatMap(a -> Mono.just(a), 10)
        .blockLast();
```

**UPDATE**: onBackpressureBuffer also looks promising

## Your Environment

* Reactor version(s) used: 3.4.2

**Comment by simonbasle** [comment]
yeah, it looks like the javadoc is misleading on `concatMap` at least. `prefetch` is used to get multiple values from the source, making these readily available whenever the current inner source completes. IIRC the original intent was to speed up the generation of the next inner publisher. Note that in the 3.4.x line, the operator accepts `0` as the prefetch value. This might become the default in the next line (3.5.0) but nothing has been decided yet.

`flatMap` has two parameters, `concurrency` and `prefetch`, which gives more levers to adjust the upstream request pattern, due to the interleaved nature of the operator: it can both request multiple values from the source (`concurrency`) and set up a minimum request pattern on each inner publisher it generates from these source values (`prefetch`).

**Comment by simonbasle** [comment]
@martin-tarjanyi would you like to try to come up with a better javadoc for these variants and their prefetch parameters ?

**Comment by martin-tarjanyi** [comment]
yeah, I'll take a shot
