### ISSUE TITLE
Relax generic type checks

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-core#258]
In [this `reduce()` code sample](https://github.com/sdeleuze/projectreactor.io/blob/df6d93908fb4ba5c593bbe9dae8e1459d31304e8/build.gradle.kts#L88), the input parameter of type `DefaultDataBuffer` does not work without an explicit call to `cast(DataBuffer.class)`. It should work without since `DefaultDataBuffer` implements `DataBuffer`.

`Mono<T> reduce(BiFunction<T, T, T> aggregator)` should be maybe transformed to  `Mono<T> reduce(BiFunction<? super T, ? super T, ? extends T> aggregator)`.

As suggested by @smaldini  it could be tested with `Number`.
It could be a good idea to do use such relaxed generic checks for each `Flux` and `Mono` operator.

**Comment by simonbasle** [comment]
After looking into it, I don't think the generic types can be relaxed into making this work.
The root of the problem is that the source is a `Flux<DefaultDataBuffer>` (already pretty specific) and that the method used for `reduce` returns a `DataBuffer`...
Since there is no seed to provide a more relaxed type, the compiler has no way of knowing that it should resolve to `Mono<DataBuffer>`.

Changing the generics the way you suggested doesn't help because the type T is already too specific.
Relaxing the `reduce` method any more would result in a `Mono<Object>` which isn't what we want either...

That said, maybe it is a problem with `DefaultDataBuffer#write(DataBuffer... buffers)`... The other `write` method in DefaultDataBuffer all return a `DefaultDataBuffer`. I reproduced a simplified version of the class hierarchy and confirmed that returning the more specialized type works:

```java
static DefaultConcatenator wrap(String value) {
  return new DefaultConcatenator(value);
}

interface Concatenator {
  Concatenator write(Concatenator... s);
  String getValue();
}

static class DefaultConcatenator implements Concatenator {

  String value;

  DefaultConcatenator(String value) {
    this.value = value;
  }

  @Override
  public String getValue() {
    return value;
  }

  @Override //HERE --v
  public DefaultConcatenator write(Concatenator... s) {
    StringBuilder sb = new StringBuilder(getValue());
    for (Concatenator concatenator : s) {
      sb.append(concatenator.getValue());
    }
    return new DefaultConcatenator(sb.toString());
  }
}

@Test
public void testReduceGenerics() {
  Flux<String> flux = Flux.just("Hello", " ", "World!");

  Flux<DefaultConcatenator> concatenators = flux.map(FluxTests::wrap);
  Mono<? extends Concatenator> finalBuffer = concatenators
      .reduce((b1, b2) -> b1.write(b2));

  System.out.println(finalBuffer.map(Concatenator::getValue).block());
}
```
