### ISSUE TITLE
Helper to try / catch / Exceptions.propagate with callable

### ISSUE THREAD

**Issue by v1nc3n4** [reactor/reactor-core#2583]
## Motivation

Hello,
Following the use of `Exceptions.propagate` method, what if the library provide an helper method to catch the checked exception of a callable, and avoid the `try ... catch ... propagate` statements? The idea behind this is to get a more concise code.
I could suggest an implementation with a PR.

## Desired solution

In class `Exceptions`, add a method such as:
```java
public static <R> R unchecked(Callable<R> callable) {
    try {
        return callable.call();
    } catch (Exception e) {
        throw Exceptions.propagate(e);
    }
}
```

For example, instead of writing:
```java
try {
    return resource.close();
} catch (IOException e) {
    Exceptions.propagate(e);
}
```
We could simply write `Exceptions.unchecked(resource::close)`, inside a reactive processing of course.

I know there has been some similar discussion in the past, but I didn't find if a solution was available now in Reactor 🤔.
Thank you in advance for your answer.
Regards

**Comment by simonbasle** [comment]
hi @v1nc3n4 

In the past, I've generally avoided adding such a feature due to the arbitrary nature of what to wrap, which can add up to more than just `Callable` quite quickly. Instead, I've recommended a library dedicated to that particular use case, namely https://github.com/pivovarit/throwing-function

What do you think?

**Comment by v1nc3n4** [comment]
Hi @simonbasle,
Thank you for your answer. I understand your point of view perfectly,
To be honest I'm hesitating about using the library you mentioned (or other ones) because it is generally not possible to choose the type of the `RuntimeException` used to wrap the checked exception. If Reactor provided it, it could ensure a `ReactiveException` is thrown, which could have its importance in some situations, just like `propagate` does (I can't introduce a concrete use case however 🤔).
I know it is also possible to suggest an improvement in this library, but still it would provide a partial answer for a more concise code, because I would have to write something like `unchecked(callable, ReactiveException::new)` or `unchecked(callable, Exceptions::propagate)`. The first one is not even possible because the `ReactiveException` class is not `public`. Finally, I would write my own reactive exception wrapper anyhow.

Feel free to close the issue and/or correct me if I'm mistaken of course.
BR

**Comment by simonbasle** [comment]
So the feature can already be proven to be larger in scope than "just `unchecked(Callable)`".

As a user, you're in a good position to create your own simpler wrapper, tailored to your case and limited in scope, if you have specific needs.

On the contrary, as a library maintainer, if I start adding such a feature I'll be pressed to implement and maintain a solution that covers the wider scope, with limited direct benefit to the core business of the Reactor library.

I would definitely open a similar issue in the throwing-function library, because it sounds like it would be a better place for a generic solution. It might be against their design and philosophy of course, in which case you always have the solution of implementing your own ad hoc helper.

PS: `ReactiveException` is indeed not intended for direct implementation / extension.
