### ISSUE TITLE
Mono#publish not propagating upstream error signals 

### ISSUE THREAD

**Issue by bivab** [reactor/reactor-core#2600]
Errors in a pipeline that contains a `Mono#publish` operator are not propagated beyond the `publish` operator. Analogous operations on a Flux propagate the error through the pipeline.

## Expected Behavior

I would expect the same behaviour on Mono and Flux pipelines, i.e. the error being propagated through the pipeline and not being "hidden" by the `publish` operator.

## Steps to Reproduce

```java
 @Test
  void testMono() {
    final String errorInMono = "Error in Mono";

    StepVerifier.create(Mono.error(new RuntimeException(errorInMono)).publish(x -> x))
        .expectErrorMessage(errorInMono)
        .verify();
  }
```

## Your Environment

* Reactor version(s) used: 3.4.2 and 3.3.10.RELEASE
* JVM version (`java -version`): 

    ```
    openjdk version "11.0.8" 2020-07-14
    OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode)
    ```

* OS and version (eg `uname -a`):
  * Linux 4.19.121-linuxkit SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux
  * Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64

**Comment by simonbasle** [comment]
This is indeed a bug, and one that has been around for quite some time I think.
`publish(Function)` is not the most commonly used operator

Note that for `Flux.publish(Function)` if you indeed use it with the identity function then prefer using `Flux.share()`.

In 3.3.x, `Mono.share()` doesn't exist, but it has been added to 3.4.0 if that is a baseline option for you. Otherwise, you can have a look at `.cache()` (and its variants) see if can fit the bill.
