### ISSUE TITLE
Using AtomicReference instead of .block() to retrieve Mono value

### ISSUE THREAD

**Issue by VuDo98** [reactor/reactor-core#2603]
Sorry, I am new to reactive paradigm. Is is possible to use AtomicReference to get value of a Mono since reactive code can run asynchronously and different events run on different thread. 

## Motivation
I have an authorization server which provide implementation for old spring security oath2 authorization which is not reactive and there is no support for it. There is a new  Spring authorization server being built right now but it about 1 year or more until first major release. So I want to somewhat move the existing code to reactive. Obviously, I don't want to use .block(). So I wonder if using AtomicReference with Mono would be a workaround to get a piece of code to be reactive. Please see the sample below. I am also not sure if this piece of code is considered reactive

## Desired solution
```
public static void main(String[] a) {
  AtomicReference<UserDTO> dto = new AtomicReference<>();
  Mono.just(new UserDTO())
      .doOnNext(d -> d.setUserId(123L))
      .doOnNext(repository::save)
      .subscribe(d -> dto.set(d));
  UserDTO result = dto.get();
  dto.set(null);
  System.out.println(result); // produce UserDTO(userId=123)
  System.out.println(dto.get()); // produce null
}

**Comment by simonbasle** [comment]
As stated in the [CONTRIBUTING.md guidelines](https://github.com/reactor/.github/blob/master/CONTRIBUTING.md#question-do-you-have-a-question) and [SUPPORT.md](https://github.com/reactor/.github/blob/master/SUPPORT.adoc#do-you-have-a-question), questions like this are best asked on Stackoverflow or Gitter.

**Comment by simonbasle** [comment]
There are two issues with your code:

1. the `AtomicReference` is an external state that would be shared between subsequent subscriptions to the `Mono`. Here, it is kind of acceptable because you subscribe once, explicitly, and feed the AtomicReference through subscribe handler
2. This code may looks like it work because `Mono.just` isn't asynchronous. As soon as the `Mono` is asynchronous it will fall apart, because `UserDTO result = dto.get()` will be execute immediately, while the `Mono` is still running and hasn't invoked the `dto.set(d)` part yet.

**Comment by VuDo98** [comment]
@simonbasle I understand now. Thank you for taking your time. I will keep in mind the guide lines for future reference.
