### ISSUE TITLE
Context not propagated with doOnSuccess

### ISSUE THREAD

**Issue by GmaD-X** [reactor/reactor-core#2615]
Hi team,

  The context is lost when calling `doOnSuccess` and `doOnError` The same code works if I change it `doOnEach` instead of `doOnSuccess`.

## Expected Behavior

`Mono.doOnSuccess()`  & `Mono.doOnError()` should pass the context

## Actual Behavior

`Mono.doOnSuccess()`  & `Mono.doOnError()` are not passing the context

## Steps to Reproduce

On the completion of  a mono as success/error, check if the  context is passed.

## Your Environment

* **Reactor version(s) used:** 3.3.11.Release
* **JVM version :** 11
* **OS and version :** Mac Catalina

**Comment by simonbasle** [comment]
That's not a "step to reproduce". Can you be more specific? How do you assert the context isn't propagated? How do you check the `Context` is lost? What is "the same code" that works?

**Comment by avillev** [comment]
@simonbasle 
I am in @GmaD-X 's team and his concern was that it was not possible to get the context in a doOnSuccess method.

Exemple:

```java
.doOnSuccess(new Consumer<String>() {
                    @Override
                    public void accept(String s) {
                        Mono.subscriberContext().map(context -> {
                            System.out.println("2:" + context.get("milk").toString());
                            System.out.println("Thread:"+Thread.currentThread());
                            return s;
                        });
                        System.out.println("onSuccess");
                    }
                })
```

But since the lambda in that method is a Consumer that does not return a mono or anything, it seems normal that it does not work. I assume it is simply impossible to access to the context within a doOnSuccess or a doOnError.

**Comment by simonbasle** [comment]
@GmaD-X @avillev thanks for the clarification. There are indeed no accessors in most `doOn` methods, which would require us to double the number of operators in order to change the arity of the lambdas (`BiFunction`, and even in some cases some sort of `TriFunction`). Since `doOnEach` was providing a `Signal` object rather than the direct content of each relevant signal, it was way easier to add an accessor to the `Context` there.

Alternatively, consider using `deferContextual` to create a scope in which the `Context` is visible.
