### ISSUE TITLE
Deprecation warning on Context#putAll requires unnecessary downcast

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#2718]
Currently `putAll(Context)` is deprecated in favor of `putAll(ContextView)`. However, the only way to create `ContextView` is through `Context#of` which returns `Context`. That means when writing to an existing `Context`, it necessary downcast like this:

```java
.contextWrite(context -> {
	ContextView view = Context.of("keyA", "valueA", "keyB", "valueB");
	return context.putAll(view);
});
```

while the more convenient form results in a deprecation warning:

```java
.contextWrite(context -> context.putAll(Context.of("keyA", "valueA", "keyB", "valueB")))
```

**Comment by simonbasle** [comment]
This API was kept to ensure backward-compatibility with 3.3.x when `ContextView` was introduced in 3.4.0, so that a common API still existed in both versions (for projects that want to advertise compatibility with both lines, like Spring Cloud Gateway).

The method is entirely redundant, since any `Context` is also a `ContextView` (and in 3.4, only `putAll(ContextView)` is overridden, eg. for optimization purposes).

I suspect it can be pretty efficiently shaved away by the JIT, and it doesn't hurt much since it has the same behavior, name and general user perception as its `ContextView`-based overload...

Note that it is purely the _deprecation_ that causes trouble for projects that disallow deprecated APIs usage:
 

- without deprecation, the compiler doesn't complain (no ambiguity or anything that I could see) but it prevents us from removing that redundant overload in the mid term
- with deprecation, the compiler will tend to select the deprecated method and that triggers warnings
  - post-deprecation and removal, the situation will be back to normal without even the need to recompile for most projects
  - projects that disallow deprecated API usage will have either suppressed the deprecation warning or forcefully casted, which will become unnecessary and will need some clean up

**Comment by simonbasle** [comment]
how about using `Context.of(...).readonly()`? it is less an eyesore than the artificial cast, and usage can be easily found and removed once the deprecated method is actually removed from the library.

I also think that even though it is not a hugely problematic method to have, it can also be aggressively removed (3.5.0) since the `ContextView` based version is a drop-in replacement and no compilation issue would arise.
