### ISSUE TITLE
Add support for primitive objects in the future

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-core#2720]
## Motivation

Our server (works as a gateway) uses reactor-core heavily, and after stress testing against our server, we heap dump -> introspect its memory usage, we found that there is about 5%~7% number of total objects from reactor (about 4.7% from reactor.core.publisher and 2% from reactor.netty). Though it's expected (because our server uses reactor heavily) and not a big deal in the Java world, it's still a part that worth optimizing, especially there is a potential "rival" Loom.
## Desired solution

Make almost all of publisher objects as [primitive objects](https://openjdk.java.net/jeps/401), so there are no redundant and unused object headers anymore, which will reduce the number of objects drastically.

But sadly, JVM may start to support primitive objects only after JDK >=18, so I need to confirm wdyt about this optimization? Will support it or not?

## Considered alternatives

No. We need the support of JVM.

**Comment by simonbasle** [comment]
I don't think this is going to happen anytime soon. The baseline for reactor-core is Java 8. At best, the next generation to change the baseline would jump on the latest LTS Java version, which is likely to be in the Java 17 timeframe. For that reason alone, I wouldn't really count on it.

I'm also unclear which exact classes you'd see turned into primitive objects, and what the expected benefits would be. I assume it would be far more beneficial (and less complicated) to propagate user-defined primitive objects through flux and mono, rather than turning reactor classes into primitive objects? the notion of an "identity-less" reference type doesn't map well with eg. publishers and their internal subscribers/subscriptions, which DO use identity.

Maybe it could be more applicable to utility classes like `Tuple2` and `Context`, but again the LTS baseline is making things unlikely in any case.
