### ISSUE TITLE
Improve flacky performanceOfContinuouslyCancellingGroups test

### ISSUE THREAD

**Issue by OlegDokuka** [reactor/reactor-core#2740]
As of now FluxGoupeBy dropping elements silently #2352 so the related tests case may be unstable (https://github.com/reactor/reactor-core/runs/3054668530?check_suite_focus=true#step:5:516). 

One suggestion to improve it is to add `.doOnDiscard(Long.class, downstream::addAndGet)` to improve its stability

**Comment by Sage-Pierce** [comment]
It looks like that test failed due to the magnitude assertion and not the matching between upstream and downstream items. In theory, the upstream and downstream matching shouldn't be flaky since the upstream publishing and take-duration scheduling are all on a single-Worker Scheduler.

Would recommend just tweaking down the assertion magnitude. Something like 39999

**Comment by simonbasle** [comment]
The assertion magnitude has been tweaked down to a low 9999. I guess we could try to bump it up to 30K. I've come across a single run out of 100 that went down to as low as 31K.

Alternatively, if we're confident the magnitude is still sufficiently asserted and the flakiness removed, we can close this one.

**Comment by Sage-Pierce** [comment]
I would feel slightly better about a higher magnitude, since the issue this catches (#2730) was exposed when asserting emissions greater than 1000s. Not a hard requirement from me, however.
