### ISSUE TITLE
Flux.collectList() returns empty list when was called in a chain after empty Mono

### ISSUE THREAD

**Issue by anton-berdnik** [reactor/reactor-core#2745]
## Documentation Issue

Kotlin example:
```
Mono.fromCallable{methodThatReturnsNull()}
      .flatMapMany { methodThatReturnsFlux(it) }
      .collectList()
      .defaultIfEmpty(methodThatReturnsListWithElement())
```

When first row returns empty Mono, flatMapMany wil not be executed and that is OK.

However, .collectList() is executed, and it turns our chain into a Mono<List> with an empty List inside, but not an empty Mono anymore.

Because of that the whole chain returns empty list, not the list returned by methodThatReturnsListWithElement(), because defaultIfEmpty() will not be executed.

## Improvement Suggestion

It should probably be documented somehow, that collectList() is executed (and will return not empty Mono) in case if it called on a Flux, that was created on a base of an empty Mono.

**Comment by anton-berdnik** [comment]
In other words: looks unobvious that collectList doesnt work like mostly all other operators when called on an empty chain, and it maybe should be described

**Comment by simonbasle** [comment]
indeed, as stated in the javadoc `collectList` will collect elements into a list until it receives the completion event. sure, we can state it in a much more explicit way, and I would be interested in the sort of phrasing you would have expected.

that said, I feel like this you might have missed the reason why _the other operators_ you mention continue returning an empty `Mono` when their source is an empty `Mono`. what you likely felt was a general rule of thumb isn't necessarily: some operators do indeed process incoming `onNext` and themself have `onNext` emission downstream triggered by these incoming `onNext`, but others like `collect` operators aggregate state upon receiving `onNext` but they emit their `onNext` when receiving the `onComplete` signal. others might trigger on `onError` instead. each operator has different semantics regarding this, by definition.

at the time of writing the javadoc it felt like it was quite logical and therefore not something that needed to insist upon so explicitly

**Comment by ivyazmitinov** [comment]
Allow me to chime in, since I've inspired raising the issue. 
While the docs state the general behavior of the `collectList` operator, it doesn't define its behavior in the particular case with the subscription to the empty publisher, and it creates the source of confusion, since the operator could behave as "all other operators", or by logic "empty flux == empty list". I assume that the latter just turned out to be natural part of implementation of the `MonoCollectListSubscriber`, so the best way to reflect it would be an `@implNote` about this behavior in the `collectList`'s javadoc.
If continue the thought "since the operator could behave as "all other operators", or by logic "empty flux == empty list", it may be even more appropriate to allow user to customize the behavior of the `collectList` via boolean parameter like `emptyListOnEmptyUpstream`.

**Comment by simonbasle** [comment]
> it may be even more appropriate to allow user to customize the behavior of the `collectList` via boolean parameter like `emptyListOnEmptyUpstream`.

hard no on that, this would be way past the level of parametric customization that we want to maintain

> the operator could behave as "all other operators"

that's where I think you're confused. there is no such thing as a "all other operators"'s behavior. it all depends on each operator's semantics. you just happen to have used a majority of operators that acted on `onNext` but just propagated `onComplete`, and hence would look similar to their source when said source is empty.

So for an operator that emits upon receiving onNext we can have something like:
```
//no state
  onNext(a)    -> onNext(process(a))
  onNext(b)    -> onNext(process(b))
  onComplete() -> onComplete()
```

When the source is empty, there's no `onNext` to react to
```
//no state
  onComplete() -> onComplete()
```

With an operator like `collect`, we don't emit upon receiving `onNext`, we accumulate in a state.
Upon receiving `onComplete`, we emit that state and complete:
```
//state: container
  onNext(a) -> container.add(a)
  onNext(b) -> container.add(b)
  onComplete() -> onNext(container) + onComplete()
```

so when the source is empty, we _also_ emit that state and complete:
```
//state: container [ ]
  onComplete() -> onNext(container) + onComplete()
```
It just happens that at that point the `container` is empty, which is consistent with the source and the semantics of the operator.

You could make a parallel with `Stream#collect` (which doesn't specify what happens when the stream is empty btw).

Another reactive parallel is `count()`. You wouldn't expect that an empty source would produce an empty `Mono<Long>` instead of `Mono.just(0L)`, would you?

**Comment by simonbasle** [comment]
we can add this short sentence to clarify this particular point, what do you think?

```
A sequence that completes empty will therefore emit an empty `List`.
```

**Comment by ivyazmitinov** [comment]
@simonbasle 
> what do you think
Yep, that's exactly what I had in mind for the `@implNote` :)
Of course, I don't insist upon it being in the `@implNote` section exactly, it just seemed the most appropriate

**Comment by simonbasle** [comment]
@ivyazmitinov would you like to submit a PR, taking the above sentence as model and applying variations of it also to other `collectXxx` operators?

**Comment by ivyazmitinov** [comment]
Yes, of course, I'll be glad

**Comment by simonbasle** [comment]
I think it is ok to target `main` branch for this enhancement. all `collect` methods do seem to have the same model of the first paragraph, more or less, so you can put the new sentence after " when this sequence completes."
