### ISSUE TITLE
doAfterTerminate not executed when subscriber throws an error.

### ISSUE THREAD

**Issue by joshiste** [reactor/reactor-core#2755]
When the subscribed consumer throws an exception the`doAfterTerminate` is not run on Project Reactor 3.4.6

The JavaDoc states:
```
* @param afterTerminate the callback to call after {@link Subscriber#onComplete} or {@link Subscriber#onError}
```

## Expected Behavior
The `doAfterTerminate` to be executed after termination (wether it was successful or not)
    
## Actual Behavior
The `doAfterTerminate` is not executed when the subscriber throws an error.

## Steps to Reproduce

```java
public static void main(String[] args) {
        Flux.just("1", "2")
                .doAfterTerminate(() -> System.out.println("doAfterTerminate()"))
                .subscribe(m -> {
                    if ("2".equals(m)) {
                        throw new RuntimeException(m);
                    }
                    System.out.println(m);
                }, ex -> System.out.println("errorConsumer"));
    }
```

Expected output:
```
1
errorConsumer
doAfterTerminate()
```

Actual output:
```
1
errorConsumer
```

* Reactor version(s) used: 3.4.6

**Comment by simonbasle** [comment]
`doAfterTerminate`, like all operators, can only act on signals that are visible to it. That is, signals that are propagated by the upstream operator. Here, the `RuntimeException` is thrown by the value handler (`Consumer<T>`) of the `subscribe`. This is at the level of the last `Subscriber` in the chain, downstream of `doAfterTerminate`.

Note that subscribe methods like `subscribe(Consumer<T> valueHandler, Consumer<Throwbale> errorHandler)` create a single `Subscriber` instance which uses both lambdas. As of 3.4.x, this Subscriber will also forward exceptions thrown from the valueHandler to the errorHandler, which is why you see `errorConsumer` output.

**Comment by joshiste** [comment]
Maybe it would be desirable to extend the JavaDoc? I guess there may be
other users that may have a false assumption on how this operator works…--
*JOHANNES EDMEIER*
Co-Founder
*steadybit GmbH*

***@***.***
+49 (0) 151 1086 7077

steadybit.com
Hochstrasse 11 | 42697 Solingen | Germany
Commercial Register: District Court Wuppertal | HRB 30206 | Germany

**Comment by simonbasle** [comment]
I don't think the operator's javadoc is the right place for this, it seems like a very basic and wide misunderstanding of how operators work. Sure, it is easy to overlook at first, but then that's true of any and all operators.

The reference guide is already covering these concepts, but if we _really_ need to explain such a thing in a transverse way, then the refguide's FAQ would probably be a better place.
