### ISSUE TITLE
Enhance onBackpressureBuffer(limit) to take an action on overflow and an OverflowStrategy

### ISSUE THREAD

**Issue by balamaci** [reactor/reactor-core#281]
Right now(reactor 3.0.3) it's not possible to specify an OverflowStrategy like dropping elements when  overflowing the buffer.

RxJava has this operator:
http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#onBackpressureBuffer(long,%20io.reactivex.functions.Action,%20io.reactivex.BackpressureOverflowStrategy)

perhaps a similar one can be added to reactor.

**Comment by simonbasle** [comment]
This should be added in 3.0.4, with the following strategies:
 - `DROP_ELEMENT`: the element that causes the buffer to overflow is
   dropped without an onError signal
 - `DROP_OLDEST`: the element that causes the buffer to overflow is
   still added to the buffer, and the oldest element from the buffer is
   dropped instead, without an onError signal
 - `ERROR`: an `IllegalStateException` is propagated as an onError signal.

**Comment by dfeist** [comment]
@simonbasle Did you consider a signature with backpressure strategy but without requiring a consumer?  The more basic use case IMO is to use a strategy and no consumer, but this isn't possible.

**Comment by dfeist** [comment]
Also @simonbasle I don't think it makes sense to use `FluxSink.OverflowStrategy` here because:
- If you want, `IGNORE` you wouldn't even be using this operator.
- If you want `BUFFER` you wouldn't use this signature with a max size you'd use `onBackpressureBuffer()` directly.
- Also `DROP`/`LATEST` aren't as clear as they could be. `DROP_LATEST`, `DROP_OLDEST` would be much clearer.

Reuse of enum is good, but not ideal when it's not a great fit and impacts usability by making strategy harder to understand and introduces different ways to do the same thing.

/cc @smaldini

**Comment by simonbasle** [comment]
@dfeist that's a fair point about making the consumer optional. I don't know if we want to put an override out for that case, because that would kind of encourage not writing a consumer (and IMO if you need to buffer on backpressure, you probably need to do something with all these discarded elements like free their resources). but what about allowing `null`?

For your second point, I actually initially had a dedicated enum (but it was inner to a non-public class, doh!). @smaldini convinced me to reuse the existing, public one. Note that `BUFFER` actually does end up calling `onBackpressureBuffer()` (unbounded version) instead of `onBackpressureBuffer(..., strategy)`...

**Comment by dfeist** [comment]
@simonbasle With my use case, I'm probably using `ERROR` and then handling with `doOnError` so don't think I'll need this consumer.  With the `DROP` action there will be cases where you don't want to do anything either because dropping an event is fine too, for example if your data stream can be sampled because it's a stream of temperatures every 0.1s for example.  So I don't agree you always need to do something with discarded events.

I'd personally deprecate `onBackpressureBuffer(int maxSize, Consumer<? super T> onOverflow)` and introduce `onBackpressureBuffer(int maxSize, OverflowStrategy bufferOverflowStrategy)` but I'll leave this up to you, because i can work around this.

On the enum, I think we need to get @smaldini to reconsider, IGNORE doing nothing and BUFFER simply dong the same as another operator isn't good.

**Comment by simonbasle** [comment]
after discussing this, we'll rework and 1) introduce the override without a callback and 2) create a dedicated strategy enum `BufferOverflowStrategy`

**Comment by dfeist** [comment]
Ideally also consider https://github.com/reactor/reactor-core/issues/295 along with this for 3.0.4, given it's the ERROR action of this operator that is exposing this exception more explicitly to users.
