### ISSUE TITLE
reactor.netty.internal.shaded.reactor.pool.PoolAcquirePendingLimitException: Pending acquire queue has reached its maximum size of 1000

### ISSUE THREAD

**Issue by Jayaram123** [reactor/reactor-core#2838]
I am using spring cloud stream to connect to  azure event hub, while receiving events I am getting this issue, 

please help me how to fix the issue.

**Comment by simonbasle** [comment]
This is a very vague and low-effort bug report.

This could be caused by your usage pattern or any of the parts you say you use (spring cloud stream, azure sdk, less likely reactor netty/pool/core).

The exception message hints at a high load placed on the pool while its whole set of connections is used, maybe for a prolongated time.

**Comment by Jayaram123** [comment]
I am using the below sample application,  I am sending 1000000 events to event hub, my app is not able to consume . 
https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub

Please provide me some solution.
