### ISSUE TITLE
possibility to pause an generator function when buffer is full in Flux.generator()

### ISSUE THREAD

**Issue by Zane-XY** [reactor/reactor-core#2847]
## Motivation

I have a requirement to parallel process the messages polled from an message queue.

Currently, I'm doing it like
```java
Flux.generate((SynchronousSink<Message> sink) -> {
        var messageBatch = messageClient.consume();
        sink.next(messageBatch);
    })
    .flatMap(batch -> process(batch).subscribeOn(Schedulers.boundedElastic()), 10)
    .subscribe();
```

But the problem with this is the pull and process become a synchronous step. Until the process completes, it would request the generator to poll another 10 messages.

Can I make the poll and process as two separate steps, when the downstream `request(10)` is sent to the generator, it returns the data elements from the buffer. When the buffer is full, generator is paused, if the buffer has `m` vacancies , it backfill the buffer with `m` data elements.

## Desired solution
I'm not sure if the `onbackPressureBlock` in RxJava is the thing I'm asking. But it's a failed experiment ( https://github.com/ReactiveX/RxJava/issues/2799)

```java
Flux.generate((SynchronousSink<Message> sink) -> {
        var messageBatch = messageClient.consume();
        sink.next(messageBatch);
    })
    .onBackpressurePause() // pause the generator function if the buffer is full
    .publishOn(Schedulers.boundedElastic()) // make consumer run in async
    .flatMap(batch -> process(batch).subscribeOn(Schedulers.boundedElastic()), 10)
    .subscribe();
```
I don't mean this is my desired solution, I also want to know how can I do this using current reactor operators.

## Considered alternatives

similar discussion https://github.com/reactor/reactor-core/issues/1596

**Comment by simonbasle** [comment]
There's no clear solution right now, but in any case I don't think an `onBackpressurePause()` is the right model.

If anything, I think what you need is more on the side of requesting _more_ than the downstream (prefetching).
There is ongoing exploration of an operator dedicated to prefetching in #2701 which might ultimately help your case.

Note that `flatMap` does already implement a progressive replenishing strategy. It won't necessarily always wait for the full `10` elements to be processed before requesting more from the upstream. Rather, it tries to maintain that level of concurrency and have 10 inner publishers running in parallel.

The discussion around `poll` operator never went anywhere because the problem space was never fully defined in a way that could lead to a generic useful operator, unfortunately.

**Comment by OlegDokuka** [comment]
@simonbasle sounds like `prefetch` related problem
