### ISSUE TITLE
Flux#mergeComparing does not emit last value for second stream until first stream is completed or has next value

### ISSUE THREAD

**Issue by arina-ielchiieva** [reactor/reactor-core#2926]
`Flux#mergeComparing` does not emit last value for second stream until first stream is completed or has next value **_though second stream value is the same as last emitted one._**
In our case such behavior causes problem when we want to merge realtime low frequency streams.

## Expected Behavior
Values 1, 2, 3, 3 are emitted.

## Actual Behavior
Values 1, 2, 3 are emitted.

## Steps to Reproduce
```java
@Test
void reproCase() {
    TestPublisher<Integer> source1 = TestPublisher.createCold();
    source1.next(1, 3);
    TestPublisher<Integer> source2 = TestPublisher.createCold();
    source2.next(2, 3);

    StepVerifier.create(Flux.mergeComparing(source1, source2))
           .expectNext(1, 2, 3, 3)
           .thenCancel()
           .verify(Duration.ofSeconds(1));
}
```

## Your Environment
* Reactor version(s) used: 3.4.15

**Comment by simonbasle** [comment]
This works as intended. With 4 values, only 3 comparisons can be performed for non-completing sources.

Since there is no guarantee that the sources are sorted / monotonically increasing, the operator cannot know that the lingering `3` is going to be the next smaller value unless `source1` precisely either completes or emits another value to compare with.

One simple example to prove this: imagine that `source1` is going to finally emit `2` again:
```java
source1.next(1, 3, 2);
source2.next(2, 3);
```

The comparisons are:
 - 1 vs 2 => 1 wins, source1 replenished
 - 3 vs 2 => 2 wins, source2 replenished
 - 3 vs 3 => 3 wins, source1 replenished (as the operator will consider the first source in case of a tie)
 - *2 vs 3* => 2 wins...

You can even observe that while distinguishing the "equal" numbers by using larger numbers `10, 21, 31, 32, 22` instead and use a comparator that divides by ten:

```java
	@Test
	void reproCaseWithTens() {
		TestPublisher<Integer> source1 = TestPublisher.createCold();
		source1.next(10, 31, 21);
		TestPublisher<Integer> source2 = TestPublisher.createCold();
		source2.next(22, 32);

        Flux<Integer> merged = Flux.mergeComparing(Comparator.comparingInt(i -> i / 10), source1, source2);

        //log and subscribe, or assert with the following StepVerifier:
		StepVerifier.create(merged)
			.expectNext(10, 22, 31, 21)
			.expectTimeout(Duration.ofSeconds(1))
			.verify();
	}
```
