### ISSUE TITLE
Usage of the Flogger logging api with Project Reactor

### ISSUE THREAD

**Issue by apffa** [reactor/reactor-core#2961]
Is it possible to use Google's Flogger logging api with Project Reactor and how? Looks like Reactor has a different way of logging, and I'd like to request this integration if it currently not possible.

**Comment by simonbasle** [comment]
hi @apffa. I think you can use `Flogger` in a Reactor-based application like you would use it in any other application, especially since it doesn't seem to have a `ThreadLocal`-based notion of metadata/contextual data (an approach which falls to pieces in a system that doesn't dedicate exactly 1 thread to 1 request).

I think what got you confused is that Reactor has a `log()` operator, which is pretty much just syntactic sugar to log every Reactive Stream signals.
It also has a `Logger` interface, mainly for its own internal logging, but you can safely ignore that if you plan on using Flogger.

**Comment by simonbasle** [comment]
yes, or within the lambda of any operator you might use that takes user code for that matter.
you can either log alongside your business logic (like in your `map` example, where `map` would also somehow transform each `onNext` signal) or as side effects:

```java
myFlux.map(input -> input.size()) //Flux<Integer>
    .doOnNext(size -> flogger.atInfo().every(10).log("Size sampling: %s", size);
```
