### ISSUE TITLE
When use `sinks.asFlux().toIterable()`, sinks doesn't reduce the subscriber number after the thread was killed

### ISSUE THREAD

**Issue by liukun-msft** [reactor/reactor-core#2972]
## Background

I am using `sinks.asFlux().toIterable()` to synchronously receive data on Thread-1. The `sinks` is defined as `Sinks.many().replay().all()`  and emit data on Thread-2. Sometimes the Thread-1 is killed by some unexpected exceptions, but `sinks` can still emitNext() without any failure. So I am trying to find a way that can let `sinks` know the subscriber on Thread-1 has already been killed. 

Current I want use `sinks.currentSubscriberCount()`. If thread got killed, I can check if  `sinks.currentSubscriberCount()` changed and then decide whether I can emit data. However, I found when the Thread-1 was killed, the subscriber count doesn't decrease.

## Expected Behavior
When use `sinks.asFlux().toIterable()` and thread was killed in the middle of iterating, the sinks should decrease the subscriber count and dispose the related subscriber. 

## Actual Behavior
`sinks.currentSubscriberCount()`  doesn't decrease after the thread was killed. I am not sure whether the subscriber is disposed.

## Steps to Reproduce

Use `sinks.asFlux().toIterable()` . After thread was killed, the `sinks.currentSubscriberCount()` is still 1.
```java
@Test
public void testKillThreadUseToIterate() throws InterruptedException {
    Sinks.Many<Integer> sinks = Sinks.many().replay().all();
    Thread t = createThreadToIterate(sinks);
    t.start();

    //Wait subscribed
    TimeUnit.SECONDS.sleep(1);
    System.out.printf("[%s] Current subscriber count: %d \n", 
            Thread.currentThread().getName(), sinks.currentSubscriberCount());

    sinks.emitNext(1, FAIL_FAST);
    sinks.emitNext(2, FAIL_FAST);
    sinks.emitNext(3, FAIL_FAST);

    //Wait Thread killed
    TimeUnit.SECONDS.sleep(2);

    //When use toIterable(), the subscriber count is 1, but no data received since thread is killed.
    System.out.printf("[%s] Current subscriber count: %d \n", 
            Thread.currentThread().getName(), sinks.currentSubscriberCount());
    sinks.emitNext(4, FAIL_FAST);
    sinks.emitNext(5, FAIL_FAST);
}

private static Thread createThreadToIterate(Sinks.Many<Integer> sinks) {
    return new Thread(() -> {
        for (Integer data : sinks.asFlux().toIterable()) {
            System.out.printf("[%s] Receive index: %d \n", Thread.currentThread().getName(), data);
            if (data == 3) {
                throw new IllegalStateException("kill thread by exception");
            }
        }
    });
}
```
Use `subscribe()`, the `sinks.currentSubscriberCount()` change to 0.

```Java
@Test
public void testKillThreadUseSubscribe() throws InterruptedException {
    Sinks.Many<Integer> sinks = Sinks.many().replay().all();
    Thread t = createThreadToSubscribe(sinks);
    t.start();

    //Wait subscribed
    TimeUnit.SECONDS.sleep(1);
    System.out.printf("[%s] Current subscriber count: %d \n",
            Thread.currentThread().getName(), sinks.currentSubscriberCount());
    sinks.emitNext(1, FAIL_FAST);
    sinks.emitNext(2, FAIL_FAST);
    sinks.emitNext(3, FAIL_FAST);

    //Wait Thread killed
    TimeUnit.SECONDS.sleep(2);

    //When use subscribe(), the subscriber count is 0
    System.out.printf("[%s] Current subscriber count: %d \n", 
            Thread.currentThread().getName(), sinks.currentSubscriberCount());
    sinks.emitNext(4, FAIL_FAST);
    sinks.emitNext(5, FAIL_FAST);
}

private static Thread createThreadToSubscribe(Sinks.Many<Integer> sinks) {
    return new Thread(() -> {
        sinks.asFlux().subscribe(data -> {
            System.out.printf("[%s] Receive index: %d \n", Thread.currentThread().getName(), data);
            if (data == 3) {
                throw new IllegalStateException("kill current thread");
            }
        });
    });
}
```
* Reactor version used: 3.4.16 
* JVM version: 11

Because I am not fully know about `sinks`, if anything wrong, please correct me. 
Also, if this is an expected behavior, could you tell the correct way/give some suggestions to tell `sinks` the subscriber on another thread is killed?

**Comment by simonbasle** [comment]
Your exception doesn't come from within the reactive chain, but is triggered by the external iteration. At that point, there's no way this can influence the subscription behind the `Iterator`, unfortunately, because once you've switched to an `Iterable`/`Iterator` in the imperative world, you've detached from the reactive sequence.

Iterator doesn't have a notion of cleaning up / closing either, unlike `Stream`.

Note that even if it wasn't the case, it's not the `Sink` that detects one of its subscribers has errored. Rather, it is the responsability of the `Subscriber` to `#cancel()` its `Subscription` as needed, and that responsibility can also transfer to the user (see `Disposable` returned by `subscribe(...)` methods).

But again, since your code is producing the error during iteration, no internal error is happening inside the reactive sequence and what you're asking for is not possible.

There are two ways around that though: a hacky way and a slightly better way:

### Hacky: Use a hidden unsupported feature: Cast to `Runnable`

The `Iterator` returned by `.toIterable().iterator()` unofficially implements `Runnable`.
You can invoke its `run()` method to cancel the subscription, although this is undocumented and unsupported:

```java
private static Thread createThreadToIterate(Sinks.Many<Integer> sinks) {
	return new Thread(() -> {


		Iterator<Integer> iterator = sinks.asFlux().toIterable().iterator();
		while (iterator.hasNext()) {
			Integer data = iterator.next();
			System.out.printf("[%s] Receive index: %d \n", Thread.currentThread().getName(), data);
			if (data == 3) {


				if (iterator instanceof Runnable) {
					((Runnable) iterator).run();
				}


				throw new IllegalStateException("kill thread by exception");
			}
		}
	});
}
```

 ## More reliable: The `toStream()` operator includes a close handler
 
If you use `Stream` and `toStream()` *and ensure that an exception leads to a call to `Stream#close()`,  then it will cancel the subscription.

Best way to achieve that is to use try-with-resource:

```java
private static Thread createThreadToIterate(Sinks.Many<Integer> sinks) {
	return new Thread(() -> {


		try (Stream<Integer> stream = sinks.asFlux().toStream()) {
			stream.forEach(data -> {


				System.out.printf("[%s] Receive index: %d \n", Thread.currentThread().getName(), data);
				if (data == 3) {
					throw new IllegalStateException("kill thread by exception");
				}
			});
		}
	});
}
```

**Comment by liukun-msft** [comment]
Thank you for the clarification and suggestions! It helps me understand more about the `.toIterable()`.
