### ISSUE TITLE
Difference in setFuture method of WorkerTask vs SchedulerTask

### ISSUE THREAD

**Issue by anuchandy** [reactor/reactor-core#2997]
Hello, I was looking into the [setFuture](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/scheduler/WorkerTask.java#L120-L127) method of WorkerTask, which won't interrupt the worker if disposition happens via sync-route.
IIUC, this means - the thread_1 running setFuture uses the marker ASYNC|SYNC_CANCELLED to check if disposition was requested by the same thread, thread_2, running call() / run().

The [setFuture](https://github.com/reactor/reactor-core/blob/e7666cc41a1a33e31366dd6dd36ea681b0ed0ced/reactor-core/src/main/java/reactor/core/scheduler/SchedulerTask.java#L102) method of SchedulerTask seems to have somewhat similar logic, but, it only checks if BOTH setFuture() and call() / run() are executed by the SAME thread to decide whether to interrupt or not. 

Just want to confirm if this difference in logic is by design or a bug.

**Comment by simonbasle** [comment]
I'm honestly not sure. The `SchedulerTask` was introduced back in 2017 while the `WorkerTask` pre-dates that (under a different name). At the time, the `WorkerTask` was augmented with the distinction between `FINISHED` and `CANCELLED` (no sync vs async distinction), and the two classes were aligned. Only difference was that the `WorkerTask` has a parent and needs to remove itself from the parent on termination.

sync/async distinction was added to `WorkerTask` later to fix #1107. I'm guessing the same issue hasn't manifested at `SchedulerTask` level because direct task submission to a `Scheduler` rather than to one of its `Worker`s is much rarer.

are you encountering any issue similar to the one linked above?

**Comment by anuchandy** [comment]
Thanks, @simonbasle for sharing the reference, the indirectly linked to the original RxJava work items provided more context.

I was trying to understand an interrupted exception in one selectable channel usage. Unfortunately, I didn't have the stack trace; hence I was scanning the reactor Schedulers for possible places we interrupt and notice the difference in implementation and thought of checking with you.

Is it the case that - If I use one of the Schedulers, then internally, reactor operators use Worker abstraction rather than direct schedule to Scheduler? If so, I believe the interrupted exception I saw could be rooted somewhere else. I'll keep looking.

Feel free to close if the difference in implementation is not anything we need to worry about considering the common use cases.

**Comment by simonbasle** [comment]
yeah most of the time operators will work with a `Worker` rather than directly with a `Scheduler`.

**Comment by anuchandy** [comment]
Thanks for confirming, closing this.
