### ISSUE TITLE
How to cancel cache() at the same time when canceling downstream .

### ISSUE THREAD

**Issue by zhou-hao** [reactor/reactor-core#3031]
How to cancel `cache()` at the same time when canceling downstream .

I tried to use this method, but it doesn't seem to be correct.
```java

AtomicReference<Disposable> ref=new AtomicReference<>();

        Flux<Long> cache = Flux
            .interval(Duration.ofSeconds(1))
            .doOnNext(System.out::println)
            .doOnCancel(() -> System.out.println("cancel"))
            .replay()
            .autoConnect(1,ref::set);

        Disposable disposable = cache
            .take(1)
            .thenMany(cache)
            .doOnNext(j-> System.out.println("j:"+j))
            .doOnCancel(()->{
                // CancellationException exception will be thrown here
                 ref.get().dispose();
            })
            .subscribe();

        Thread.sleep(5000);

        disposable.dispose();

        Thread.sleep(3000);

```

**Comment by simonbasle** [comment]
Can you clarify what you are trying to achieve and what your expectations are?
What do you mean by "cancelling downstream"? In caching, it is likely there are _multiple_ downstreams...
Plus, I don't see a `cache()` operator involved at all here.

**Comment by zhou-hao** [comment]
I want to subscribe to a stream multiple times and cancel the upstream when the downstream cancels.
when i use `cache()` operator, Upstream is not automatically cancelled.  so i tried use `replay()` and `autoConnect ` operator.

In fact, I want to know the correct usage.

**Comment by simonbasle** [comment]
Ah, you probably need to use `.replay(...).refCount(1)`, since `autoConnect(x)` only works one way: it does connect when reaching `x` subscribers, but doesn't `cancel()`.
On the opposite, `refCount(x)` will cancel the source if the number of registered subscribers shrinks back to under `x` (via cancellation of some subscibers).

**Comment by zhou-hao** [comment]
its my test code:

```java
    public static void main(String[] args) throws InterruptedException {
        Flux<Long> job = Flux
                .interval(Duration.ofSeconds(1))
                .doOnSubscribe(sub->{
                    System.out.println("subscribe interval");
                })
                .doOnCancel(() -> {
                    System.out.println("cancel interval");
                })
                .replay()
                .refCount(1);

        Disposable disposable = job
                .doOnNext(val -> System.out.println("first subscriber:" + val))
                .take(3)
                .thenMany(job.doOnNext(val -> System.out.println("second subscriber:" + val)))
                .subscribe();

        Thread.sleep(6000);
        disposable.dispose();
    }

```

output:
```text
subscribe interval
first subscriber:0
first subscriber:1
first subscriber:2
cancel interval
subscribe interval
second subscriber:0
second subscriber:1
cancel interval
```

I want the `job` stream to be subscribed once. like this:
```text
subscribe interval
first subscriber:0
first subscriber:1
first subscriber:2
second subscriber:0
second subscriber:1
cancel interval
```

**Comment by simonbasle** [comment]
please note that there's logically no way of achieving the exact sequence of signals you describe in your last snippet since you want to share a source: if there's no cancellation / re-subscription by `second subscriber`, it _has_ to receive events from further in the interval: not 0/1/2 but rather 3, 4, 5... but I think I get what you are after, now.

So what happens in the actual output is:
 - `take(3)` sees 3 elements
 - it cancels the parent (refCount) before completing
   - `refCount` is now at 0 subscribers, which means it must cancel the source
 - `thenMany` receives `onComplete` signals
   - it subscribes to `job`
   - refCount is back at 1, triggers a new subscription to the source
  - after 6s you manually `dispose()` that subscription, refCount is down to 0, cancels the source for the second time

As you can see, the issue is that `refCount` sees 0 subscribers and cancels fast, despite the fact _we_ know a new subscriber will come pretty fast from `thenMany`.

The way around that is to use the `refCount(int, Duration)` variant (the "refCount with grace period" variant) so that `refCount` waits a tiny bit for a new subscriber before it cancels the source after that `take(3)` cancellation:

```java
                //.refCount(1);
                .refCount(1, Duration.ofMillis(10)); //fine tune the grace period
```

**Comment by zhou-hao** [comment]
Thanks!,I also found another way:
```java
    Disposable[] ref = new Disposable[1];

        Flux<Long> job = Flux
                .interval(Duration.ofSeconds(1))
                .doOnSubscribe(sub -> {
                    System.out.println("subscribe interval");
                })
                .doOnCancel(() -> {
                    System.out.println("cancel interval");
                })
                .replay()
                .autoConnect(1, dis -> ref[0] = dis);

        Disposable disposable = job
                .doOnNext(val -> System.out.println("first subscriber:" + val))
                .take(3)
                .thenMany(job.doOnNext(val -> System.out.println("second subscriber:" + val)))
                .doFinally(s -> ref[0].dispose())
                .subscribe();

        Thread.sleep(6000);
        disposable.dispose();
```
What is the difference between the `.refCount(1, Duration.ofMillis(10));` and which is better?

**Comment by simonbasle** [comment]
The two are similar, although the one you've found requires a bit more setup (holder for the `Disposable`, `doFinally`). But both sound good to me.
