### ISSUE TITLE
doOnEach emits item after onComplete()

### ISSUE THREAD

**Issue by adamZakar** [reactor/reactor-core#3044]
**doOnEach emits item after onComplete() when used with flatMapIterable**

I'm using the doOnEach operator for logging purposes. I'm only interested to log out the items that go through at the given point. I've experienced that if I use flatMapIterable after the doOnEach then the doOnEach reemits the on next signals even though the Flux was completed before. Due to that I cannot rely on that operator for logging, because at debugging there might be some misleading information. I've tried to same with doOnNext operator and the items gets emitted only once. I might miss something, however I think doOnEach should not emmit onNext signals after it's completion. 

```java
    @Test
    void test() {
        StepVerifier.create(Flux.just("a", "b", "c").collectList()
                        .doOnEach(item -> System.out.println(item))
                        .flatMapIterable(Function.identity())
                        .collectList())
                .expectNext(List.of("a", "b", "c"))
                .verifyComplete();
        System.out.println("------ with doOnNext: ------");
        StepVerifier.create(Flux.just("a", "b", "c").collectList()
                        .doOnNext(item -> System.out.println(item))
                        .flatMapIterable(Function.identity())
                        .collectList())
                .expectNext(List.of("a", "b", "c"))
                .verifyComplete();
    }
```

**Console logs for me:** 

doOnEach_onNext([a, b, c])
onComplete()
doOnEach_onNext([a, b, c])
------ with doOnNext: ------
[a, b, c]

**Expected would be:**

Console logs for me: 
doOnEach_onNext([a, b, c])
onComplete()
------ with doOnNext: ------
[a, b, c]

I've tried that with Reactor version: 3.4.18

**Comment by simonbasle** [comment]
There seem to be a bug with `FluxDoOnEachFuseable.DoOnEachFuseableSubscriber`: it happily negotiates ASYNC fusion but fails to deal with the `onNext(null)` signal.

This is multiplied by another bug in `Operators.MonoSubscriber` which also negotiates ASYNC fusion (the only kind of fusion it supports btw) but when ASYNC fusion is enabled it call `a.onNext(t)` instead of `a.onNext(null)`.

Ultimately, the `doOnEach` handler is called twice: once from the `onNext` and once from a `poll()` from the fused downstream.
