### ISSUE TITLE
FlatMap::onErrorContinue not work as expect

### ISSUE THREAD

**Issue by tmzk1005** [reactor/reactor-core#3064]
```java
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

public class ErrorTest {

    public static void main(String[] args) {
        Flux.just(1, 2, 3)
                .flatMap(ErrorTest::int2Mono)
                // .onErrorContinue((throwable, o) -> System.out.println(throwable.getMessage()))
                .subscribe(System.out::println);
    }

    private static Mono<Integer> int2Mono(int n) {
        return Mono.just(n).map(ErrorTest::intMap).onErrorResume(throwable -> {
            System.out.println("int2Mono error: " + n);
            return Mono.empty();
        });
    }

    private static int intMap(int n) {
        if (n == 2) {
            throw new RuntimeException("intMap error: " + n);
        }
        return n * 100;
    }

}
```

output is :
```txt
100
int2Mono error: 2
300
```

This output make sence, but  after uncomment the commented line， the output changed:

```txt
100
intMap error: 2
300
```

I think the output  shoud not change. 

Maybe it's not bug, but I can not understand why `onErrorResume` not work any more if there is a `onErrorContinue`.

reactor-core version is `3.4.16`

**Comment by simonbasle** [comment]
this is working exactly as intended for `onErrorContinue`: it influences the whole chain of operators upstream of it to avoid `onError` signal from an operator _if the operator supports it_. `map` does support `onErrorContinue` mode, so the exception generated (I'm guessing) from `intMap` is passed to the `onErrorContinue` handler instead of terminating the sequence with an `onError` signal (which is what `onErrorResume` reacts to).
