### ISSUE TITLE
Deprecated Flux.subscribe method used in documentation

### ISSUE THREAD

**Issue by jdsdc** [reactor/reactor-core#3090]
## Documentation Issue

Deprecated method subscribe method taking a subscriber as method parameter is used in example. 
Version: 3.4.19
Chapter: 4.3.1.

Flux.subscribe(consumer, errorConsumer, completeConsumer, **subscriptionConsumer**)

```
Flux<Integer> ints = Flux.range(1, 4);
ints.subscribe(i -> System.out.println(i),
    error -> System.err.println("Error " + error),
    () -> System.out.println("Done"),
    sub -> sub.request(10));

```

Suggestion

```
BaseSubscriber<Integer> baseSubscriber = new BaseSubscriber<Integer>() {
            @Override
            protected void hookOnSubscribe(Subscription subscription) {
                subscription.request(2);
            }
            @Override
            protected void hookOnNext(Integer value) {
                System.out.println(value);
            }
            @Override
            protected void hookOnComplete() {
                System.out.println("Completed");
            }
        };
        Flux.range(1, 4)
                .subscribe(baseSubscriber);

```

**Comment by jdsdc** [comment]
Missed that there was a chapter below describing BaseSubsciber (4.3.3). But anyhow, usage of deprecated methods maybe shouldn't be included in examples.

**Comment by simonbasle** [comment]
for reference, there is currently a `NOTE` admonition for that particular paragraph / method overload that states:
> NOTE: That variant requires you to do something with the `Subscription` (perform a
`request(long)` on it or `cancel()` it). Otherwise the `Flux` hangs.

@jdsdc would it improve the situation if the `NOTE` was turned into a `WARNING` and have a few words about how this method is discouraged and to link to the `BaseSubscriber` section, or do you feel this should be removed entirely from the guide?

**Comment by jdsdc** [comment]
@simonbasle, i think the documentation should reflect the latest version and not use deprecated versions since documentation for the deprecated methods can be found in the documentation for earlier releases.
