### ISSUE TITLE
Specify error handling for data pipelines in the docs

### ISSUE THREAD

**Issue by almogtavor** [reactor/reactor-core#3131]
I'm writing a data pipeline in which my flow is a `Flux` of Spring's `Message<MyPojo>`. In each step in the pipeline I handle my errors with `.onErrorResume`, and after that I'd like to propagate `Message<MyException>` to a unified place so I would be able to process these messages easily, and keep the original pipeline clean (only for the happy flow). One way to achieve this was using functional programming objects (e.g. from Vavr) such as `Either<Message<? extends Expection>, Message<MyPojo>>` or others like `Option` or `Try`. 

The problem with this is that in every step I needed to get that as input and filter the errors at the beginning, and merge them at the end. Which was pretty cumbersome.

I want to be able to handle all of the exceptions in one place (similar to the DLQ pattern). This way I would be able to keep the pipeline clean and propagate only `Message<MyPojo>`, so each step will only handle its one responsibility.

Is there a way of implementing the DLQ pattern within Project Reactor?

I thought of using one big `onErrorContinue` and process  (write to some errors table) errors over there, but I've understood that `onErrorContinue` isn't really recommended. Is it a use case for `onErrorContinue` still?

## Documentation Issue

I feel that the docs doesn't direct to a solution in the case of error handling when writing data pipelines. I haven't found any suggestions for my question. 

## Improvement Suggestion

Answers to the comparison with DLQ would help a lot for understanding error handling in Reactor.

## Additional context

Specifying recommended way of propagating errors for unified handling would improve the docs in my opinion.

**Comment by simonbasle** [comment]
you seem to be in a place where the `onError` signal is generally not produced in your pipeline's steps, being replaced by `onNext(Message<Exception>`, correct?

I'm not sure why you would need to "filter the errors and merge them at the end" in every step.
Sure, you'll need your business logic in the operators to distinguish between `Message<Exception>` and `Message<BusinessObject>`. Perhaps `Try` would be better adapted to that by the way (decoupling the `Exception` from the `Message`).

But in any case, this is more a matter of letting each `Message<Exception>` (or each `Try.Failure`) flow down as is, ignoring business logic transformations, until the very last step.

Then you can `filter` out these `Failure`s once at the end, using the `Predicate` as an opportunity  to drop them to a Dead Letter Queue (which should probably be a MPSC queue drained in a separate thread).

`onErrorContinue` was an attempt at helping with such cases BUT without the materialization of exceptions as normal signals / onNext. it is not a perfect solution by far, and I would go as far as calling it a footgun. I don't recommend you use it, especially since you've made the hard work of avoiding `onError` in the first place already.

**Comment by almogtavor** [comment]
@simonbasle Thanks for the quick response!

> I'm not sure why you would need to
"filter the errors and merge them at the
end" in every step.
- I need to do this when I work with batches (the IO operations - e.g. writing to databases & enriching phases are batch-based). This is exactly the reason why need to filters errors at the beginning, and merge them at the end. Since we only want to write data to the databases, but we still want to propagate errors. `Either`'s `left()` and `right()` operations aren't available for `Collections`.

> Perhaps
Try would be better adapted to that by
the way
- I can't really use `Try` since I need the headers of the original messages that had errors (since they hold objects like `ReceiverOptions` to ack with Reactor Kafka, and other context data for better monitoring).

So in general I'm not really sure how can I let the messages flow down as is, since `Try` is problematic with Message's headers, and `Either` is problematic with batches. If you have an idea for this, I'd like to hear.


> Then you can filter out these
Failure s once at the end, using the
Predicate as an opportunity to drop
them to a Dead Letter Queue (which
should probably be a MPSC queue
drained in a separate thread).

- If I understand correctly, you suggest to send to the `Queue` only at the end of the pipeline, but I thought that DLQ in general refers to enabling the sending of errors in each step. This way the user won't need to propagate errors, but only propagating data and filtering errors immediately. Than, on batch cases, no need for considering errors filtering before, and merging after.

- And in general I haven't seen much documentation for Reactor's `Queue` / MSPC. Is it possible to implement errors sending (might be from different threads) in each step this way? If so, can you please give a little code example?

Thanks ☺️

**Comment by simonbasle** [comment]
I see. I'm not that familiar with the DLQ pattern. My initial thought was that `onErrorContinue` was close, but not entirely adapted since you sort of materialize the errors as their own `Message`.

Given that what you're describing seems to be complex pipelines with fan-out, windowing and the like, there's not much we can do to support this other than the manual steps that you are already taking.

**Comment by almogtavor** [comment]
@simonbasle I see. My basic question about this (and this is what I meant by referring to DLQ) is - is it possible to send messages to another `Flux`, within my own main flow `Flux`? This way I'd manage an `errorsFlux` and a `dataFlux`.

Same concept does appear at similar reactive streams based frameworks like Akka, e.g. `[divertTo](https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/divertTo.html)`. Which is explained [here](https://bszwej.medium.com/akka-streams-error-handling-7ff9cc01bc12).


The `[Queue](https://projectreactor.io/docs/core/release/api/reactor/util/concurrent/Queues.html)` class you've mentioned seemed interesting, is it documented anywhere/ can fit my needs?

**Comment by almogtavor** [comment]
@simonbasle what do think?

**Comment by simonbasle** [comment]
@almogtavor `divertTo` doesn't really translates to Reactor, as there is no distinction between Source/Flow/Sink.

well, we do have `Sinks`, but that's quite an advanced API that we'd prefer not to expose at the same level as a `Flux` operator.

one thing that can be done to approach `divertTo` is to share the same root `Flux` between two chains with opposite `filter`s, using a `refCount(2)` to ensure the root subscription starts only when both sides have been subscribed :

```java
Flux<Message<T>> rootFlux;
//prepare to share between two "sides"
Flux<Message<T> sharedForTwo = rootFlux.publish().autoConnect(2);

//the main side filters out errors
Flux<Message<T>> main = sharedForTwo
  .filter(m -> !isErrorMessage(m)); //mind the `!`

//the divertedError side receives the Exceptions extracted from the Messages
Flux<Exception> divertedErrors = sharedForTwo
  .filter(m -> isErrorMessage(m))
  .map(m -> extractException(m));
```

(use `refCount(2) instead if root subscription must also be cancelled as soon as one of the sides is cancelled)

**Comment by almogtavor** [comment]
@simonbasle It looks awesome! But will I be able to send an error caught from `main`, to `errors`?
