### ISSUE TITLE
Enabling logging changes the thread on which callable is executed.

### ISSUE THREAD

**Issue by janvojt** [reactor/reactor-core#3161]
Enabling logging on a Mono wrapping a callable with `publishOn` changes the thread the callable executes on.
If logging is enabled, the callable is run on the main thread.
If logging is disabled, the callable is run on the published thread pool.

## Expected Behavior
The callable should run on the main thread regardless of logging.

## Actual Behavior
The thread on which callable is run depends on the logging.

## Steps to Reproduce
See reproduction test case below.

```java
@Test
void reproCase() {
    String expectedResult = "123";
    String result = Mono.fromCallable(() -> {
        System.out.println("sleeping on " + Thread.currentThread().getName());
        Thread.sleep(1_000);
        return expectedResult;
    })
    .log("INFO") // if this line is commented out, the test fails
    .publishOn(Schedulers.boundedElastic())
    .block(Duration.ofMillis(200));
    
    assertEquals(expectedResult, result);
}
```

## Possible Solution
Did not investigate why the behavior is as it is, but I believe it should be consistent regardless of the logging.

## Your Environment
* Reactor version(s) used: `3.4.22`
* JVM version: `OpenJDK 64-Bit Server VM (build 19-ea+23-Debian-1, mixed mode, sharing)`
* OS: `Linux 5.17.0-3-amd64 #1 SMP PREEMPT Debian 5.17.11-1 (2022-05-26) x86_64 GNU/Linux`

**Comment by OlegDokuka** [comment]
that is expected behavior. publishOn has optimizations that eliminate redundancy such as allocating a queue or redundant intermediate operator when the source is a scalar value or a single element function. In such a scenario, `publishOn` is transformed into a simple `subscribeOnValue`. 

This behavior is disabled when there are intermediate operators between the source and `publishOn` since the execution thread for those operators should correspond to the subscription thread. In such case `publishOn` can not be changed to `subscribeOn` since we guarantee a threading model when there are intermediate operators so the `publishOn` affects downstream only operators. 

In case you need to ensure that your `MonoCallable` is not fused with downstream `publishOn` you may use `.hide` operator designed to hide the original characteristics of the source
