### ISSUE TITLE
retryOnNext maybe not next others; we found  retry same server many a time

### ISSUE THREAD

**Issue by yangyxiao** [reactor/reactor-core#3196]
sames like retry next still excute  reactiveLoadBalancer.choose()  choose on server   may  retry same server many a time

<img width="894" alt="image" src="https://user-images.githubusercontent.com/24884445/191162795-ba91d74d-9240-4664-afee-16a1751b7478.png">

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/24884445/191162684-47546610-4012-419d-9bf4-e79d2d7329fb.png">

**Comment by chemicL** [comment]
It seems the issue is regarding https://github.com/PlaytikaOSS/feign-reactive. Please report the issue there if it's not specific to reactor-core. The internal logic of the `getRetry(request)` is responsible for deciding when a retry should happen, so it seems the issue is a question/bug report for feign-reactive. If still you think reactor-core is at fault, please provide an isolated reproducer.
BTW. consider copy-pasting or linking relevant code in the future instead of using screen captures, which cause an accessibility issue.
