### ISSUE TITLE
limitRate() gets request unbounded when called before log()

### ISSUE THREAD

**Issue by cosminnicula** [reactor/reactor-core#3197]
When limitRate() is called before log(), the request gets unbounded:

```java
Flux<Integer> flux = Flux.range(1, 10)
        .limitRate(2)
        .log();
// console output: [main] INFO reactor.Flux.Range.1 - | request(unbounded)
```

When called after log(), the request is correctly bounded:

```java
Flux<Integer> flux = Flux.range(1, 10)
        .log()
        .limitRate(2);
// console output: [main] INFO reactor.Flux.Range.1 - | request(2)
```

## Expected Behavior

The request should be bounded even when I use limitRate() before log().

## Actual Behavior

The request is not bounded when I use limitRate() before log().

## Steps to Reproduce

See above.

## Possible Solution

N/A

## Your Environment

* Reactor version(s) used: 3.4.22
* Other relevant libraries versions (eg. `netty`, ...): slf4j-api@2.0.0, slf4j-simple@2.0.0, junit-jupiter@5.9.0
* JVM version (`java -version`): 17
* OS and version (eg `uname -a`): Linux thor 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by simonbasle** [comment]
This is expected and actually demonstrates that `limitRate` works: the request signal flows from bottom to top, so in order to see what `limitRate` did request to its parent, you have to place `log()` _before_ it.

In your first snippet, `log` merely shows the request made by the downstream subscriber (which I assume is a plain `.subscribe()` which default to an unbounded initial request).

**Comment by cosminnicula** [comment]
It makes more sense now. Thank you, Simon!
