### ISSUE TITLE
`doAfterSubscribe` operator similar to `doFirst`

### ISSUE THREAD

**Issue by OlegDokuka** [reactor/reactor-core#3286]
@simonbasle
 > alternative idea: add it to SignalListener with a default NO-OP implementation

**Comment by injae-kim** [comment]
This issue is still valid? I want to try this issue :)

**Comment by chemicL** [comment]
Hey, @injae-kim!

Thanks for considering this issue. I must apologise for the late response. I've been busy with another investigation. Regarding this operator, I'd take a pause first to consider its usefulness. I believe the proposal came from some discussion around enabling something else, which as it turned out was possible to be implemented without this operator (my memory is really foggy here, so won't name the ideas what it was about).

Due to that, I'd first ask - what would adding this operator enable people to do? In terms of practical examples, it would be useful to back this up with some concrete use cases. Because adding an operator carries with it a maintenance cost, I'd prefer to avoid adding it unless it is justified.

@injae-kim I do know you've put some effort into the PR and I apologise for taking so long to respond here. Yet, the PR still would require revising and perhaps its best to stop here and consider if this is really needed. Thanks.

**Comment by chemicL** [comment]
Also, please note my comment in the PR about the behaviour of this operator and the possible contract for it: https://github.com/reactor/reactor-core/pull/3736#pullrequestreview-1913943004

Even if there is a need for this, it needs to be specified up-front and should consider the various scenarios.

**Comment by chemicL** [comment]
Thank you for your understanding @injae-kim ! I really appreciate the open-mindedness on your part ❤️. We can always come back to this if a use case comes to light.

**Comment by injae-kim** [comment]
@chemicL just curious, is there any way that I can donate to you? (e.g. github sponsor?)

I'm big fan of reactive-streams and learn lot's, impressed by from your kind code review :)
