### ISSUE TITLE
Mono#retryWhen and Flux#retryWhen cancel the source on error

### ISSUE THREAD

**Issue by GeorgiPetkov** [reactor/reactor-core#3322]
`Mono#retryWhen` and `Flux#retryWhen` cancel the upstream when an error is propagated from the upstream. Consider the following example:

```java
Mono.error(RuntimeException::new)
    .doOnCancel(() -> {
        throw new IllegalStateException("Why cancelling?");
    })
    .retryWhen(Retry.fixedDelay(0L, Duration.ZERO)) // the parameters to Retry#fixedDelay are irrelevant
    .block();
```

If executed you'll find the IllegalStateException in the logs (being dropped).
This behavior is unexpected and not observed in simpler alternatives like `Mono#retry`.

This has a bigger impact in the following use case using jOOQ which behaves similarly except that it hangs rather than propagating the error downstream (making it much worse):

```java
Mono.from(dslContext.transactionPublisher(config -> Mono.error(RuntimeException::new)))
    .retryWhen(Retry.fixedDelay(0L, Duration.ZERO)) // the parameters to Retry#fixedDelay are irrelevant
    .block();
```

In this case, since jOOQ doesn't have an idempotent close of the connection and tries to close it on error or cancel (and it is not expected that both occur) there's an error which is again dropped, but the whole execution hangs (none of the errors is propagated at all).

## Expected Behavior
The source should not be cancelled.

## Actual Behavior
The source is cancelled.

## Steps to Reproduce
Here are a few tests depending only on JUnit5 to quickly check the problem (both when cancellation should and should not occur). There's also a TODO to fill in and test a possible workaround.
Currenty for `retryWhen`:
- the cancellation occurs incorrectly in the first test
- the cancellation occurs correctly in the second test

```java
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import reactor.core.Exceptions;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;
import reactor.util.retry.Retry;

import java.time.Duration;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Function;

import static org.junit.jupiter.api.Assertions.*;

class RetryWhenSourceCancellationTest {

    @ParameterizedTest
    @MethodSource("retryWhenImplementations")
    void assertRetryWhenDoesNotCancelTheSourceOnUpstreamError(Function<Mono<?>, Mono<?>> transformer) {
        AtomicBoolean sourceCancelled = new AtomicBoolean(false);

        StepVerifier.create(Mono.error(() -> new RuntimeException("failed on purpose"))
                        .doOnCancel(() -> sourceCancelled.set(true))
                        .as(transformer))
                .expectErrorSatisfies(e -> {
                    assertTrue(Exceptions.isRetryExhausted(e));
                    assertEquals("failed on purpose", e.getCause().getMessage());
                })
                .verify();

        assertFalse(sourceCancelled.get());
    }

    @ParameterizedTest
    @MethodSource("retryWhenImplementations")
    void assertRetryWhenDoesCancelTheSourceOnDownstreamCancellation(Function<Mono<?>, Mono<?>> transformer) {
        AtomicBoolean sourceCancelled = new AtomicBoolean(false);

        StepVerifier.create(Mono.delay(Duration.ofSeconds(10))
                        .doOnCancel(() -> sourceCancelled.set(true))
                        .as(transformer))
                .thenAwait()
                .thenCancel()
                .verify();

        assertTrue(sourceCancelled.get());
    }

    // the parameters to Retry#fixedDelay are irrelevant
    private static List<Function<Mono<?>, Mono<?>>> retryWhenImplementations() {
        return List.of(

                mono -> mono.retryWhen(Retry.fixedDelay(0L, Duration.ZERO)),
                // the workaround
                mono -> {
                    AtomicBoolean cancelledFromDownstream = new AtomicBoolean(false);

                    // TODO:
                    //  How to allow being cancelled conditionally (only if cancelledFromDownstream)
                    //  A general solution is necessary that is appropriate for Flux as well.
                    return Mono.defer(mono::cache) // Mono#cache to prevent cancellation, Mono#defer to prevent caching
                            .retryWhen(Retry.fixedDelay(0L, Duration.ZERO))
                            .doOnCancel(() -> cancelledFromDownstream.set(true));
                });
    }
}
```

## Possible Solution
None. I would appreciate it very much if someone could provide insights on how to implement the incomplete workaround in the provided tests above.

## Your Environment
* Reactor version(s) used: latest BOM versions 2020.0.26 and 2022.0.1 using respectively 3.4.26 and 3.5.1.
* JVM version:
  ```
  openjdk version "18.0.2.1" 2022-08-18
  OpenJDK Runtime Environment (build 18.0.2.1+1-1)
  OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
  ```

**Comment by GeorgiPetkov** [comment]
I mentioned that the max number of retries is irrelevant. This is true for the given test with `Mono.error()` because it always fails, but it is imporant to note that the cancellation occurs only when the retries are exhausted.

**Comment by NamrataGuptaRoy** [comment]
I was looking into this and noticed that retryWhen indeed has the functionality where the source is cancelled when the inner subscriber has error or is empty, and there are tests covering this functionality. 
```
 void whenError(Throwable e) {
        super.cancel();

        actual.onError(e);
}

void whenComplete() {
	super.cancel();

	actual.onComplete();
}
```
Could someone point out why is it important to cancel the source in these cases ? 
Is it not enough to just perform actual.onError or actual.onComplete?

**Comment by chemicL** [comment]
Hey.

Let's first discuss the [Reactive Streams Specification](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md).

* Rule 1.6 says that after receiving `onError` from the source, the `Subscription` MUST be considered as cancelled
* Rule 3.5 says `cancel` should be idempotent
* Rule 3.7 says that additional `cancel` calls should be NOPs (have no observable effect)

Yet Rule 1.7 says that after `onError` no further signals occur. However, the explanation mentions the `Subscriber` and `Publisher` pair having no more interactions and there is no mention of the `Subscription`.

My interpretation of the above is that a call to `Subscription.cancel()` is permitted and should not cause problems.

Now regarding the actual behaviour here, my take is the following. The `retryWhen` operator takes `Retry` instance as an argument. Anyone is free to implement `Retry` as this is a public abstract class. One of the methods of `Retry` is

    public abstract Publisher<?> generateCompanion(Flux<RetrySignal> retrySignals);

The intention is to provide a transformation of the `RetrySignal` (which turns out to be the current upstream `Subscription` itself) into a signal interpreted as either a call to re-subscribe or a terminating signal (`onComplete`, `onError`). Because the companion is something that can be provided by the user as well as can come from the provided implementations, e.g. for the backoff implementation, we can't assume any relationship between a termination of the source and the signals from the companion. For instance if the companion `Publisher` spuriously terminates, we have no means of knowing whether it's a reaction to a prior source termination. Because of that we cancel the source. It so can happen that the cancellation results as a result of the source emitting an error, as in the case here. However it can also be a different case.

Take for example [the test case in our codebase](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/test/java/reactor/core/publisher/FluxRetryWhenTest.java#L406). The termination of the companion comes from the original first failure and the completion of the companion, but it cancels the second subscription that happens as a result of the first signal to retry. The implementation in the test is a broken one, however possible for users to come up with. The intention of the implementation is to make sure that proper cleanup happens and no hanging subscriptions are left when the companion terminates as it limits our possibility to react to future failures. Therefore its termination necessitates the entire stream cancellation.

As this problem has been reported a while ago and it mentions JOOQ as the implementation not providing an idempotent cancel implementation, have there been any reports of this in JOOQ? I found [a similar subject in the JOOQ Github repository](https://github.com/jOOQ/jOOQ/issues/15462). I'll close the issue, but if there's arguments that my interpretation of the RS Spec is invalid we can revisit this subject. I do however sense that the issue lies in the higher layers of the stack (r2dbc? JOOQ?).
