### ISSUE TITLE
Can dependencies to sun.misc be optional?

### ISSUE THREAD

**Issue by vogella** [reactor/reactor-core#3338]
Using the latest io-projectreactor.reactor-core library in an Eclipse RCP application results in the following validation error:

![image](https://user-images.githubusercontent.com/139910/215430559-2ca312f7-9f47-44f9-bd07-43a1148cf1f6.png)

AFAICS this package is not exported / available in Java 17. Could you make the dependency optional in the MANIFEST.MF?

````
Manifest-Version: 1.0
Automatic-Module-Name: reactor.core
Bnd-LastModified: 1673363290775
Bundle-ManifestVersion: 2
Bundle-Name: reactor-core
Bundle-SymbolicName: io.projectreactor.reactor-core
Bundle-Version: 3.5.2.RELEASE
Created-By: 1.8.0_352 (Temurin)
Export-Package: reactor.adapter;version="3.5.2.RELEASE";uses:="org.rea
 ctivestreams,reactor.core.publisher",reactor.core;version="3.5.2.RELE
 ASE";uses:="org.reactivestreams,reactor.util.annotation,reactor.util.
 context,reactor.util.function",reactor.core.observability;version="3.
 5.2.RELEASE";uses:="org.reactivestreams,reactor.core.publisher,reacto
 r.util.context",reactor.core.publisher;version="3.5.2.RELEASE";uses:=
 "org.reactivestreams,reactor.core,reactor.core.observability,reactor.
 core.scheduler,reactor.util,reactor.util.annotation,reactor.util.cont
 ext,reactor.util.function,reactor.util.retry",reactor.core.scheduler;
 version="3.5.2.RELEASE";uses:="reactor.blockhound,reactor.blockhound.
 integration,reactor.core,reactor.core.publisher,reactor.util.annotati
 on",reactor.util;version="3.5.2.RELEASE";uses:="io.micrometer.core.in
 strument",reactor.util.annotation;version="3.5.2.RELEASE",reactor.uti
 l.concurrent;version="3.5.2.RELEASE",reactor.util.context;version="3.
 5.2.RELEASE";uses:="io.micrometer.context,reactor.util.annotation",re
 actor.util.function;version="3.5.2.RELEASE";uses:="reactor.util.annot
 ation",reactor.util.retry;version="3.5.2.RELEASE";uses:="org.reactive
 streams,reactor.core.publisher,reactor.core.scheduler,reactor.util.an
 notation,reactor.util.context"
Implementation-Title: reactor-core
Implementation-Version: 3.5.2
Import-Package: org.slf4j;resolution:=optional;version="[1.5.4,2)",rea
 ctor.blockhound;resolution:=optional,reactor.blockhound.integration;r
 esolution:=optional,io.micrometer.context;resolution:=optional,io.mic
 rometer.core.instrument;resolution:=optional,io.micrometer.core.instr
 ument.binder.jvm;resolution:=optional,io.micrometer.core.instrument.c
 omposite;resolution:=optional,io.micrometer.core.instrument.search;re
 solution:=optional,org.reactivestreams;version="[1.0,2)",reactor.core
 ;version="[3.5,4)",reactor.core.observability;version="[3.5,4)",react
 or.core.publisher;version="[3.5,4)",reactor.core.scheduler;version="[
 3.5,4)",reactor.util;version="[3.5,4)",reactor.util.annotation;versio
 n="[3.5,4)",reactor.util.concurrent;version="[3.5,4)",reactor.util.co
 ntext;version="[3.5,4)",reactor.util.function;version="[3.5,4)",react
 or.util.retry;version="[3.5,4)",sun.misc
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-6.3.1.202206071316
````

The last import statement for ,sun.misc could be optional I think, at least while using in Java 17.

**Comment by pderop** [comment]
Hello @vogella ,

Could you tell a bit more about the issue ? especially:
- which JDK version are you using
- does Eclispe RCP reports a resolution error ?
- are you using OSGI at runtime ? or it's just that you are building your components using ECP which just ensure OSGI metada is consistent ?

**if you are using JDK9+ and OSGI at runtime:**

When using JDK9+, the `sun.misc` package  (which is part of the `jdk.unsupported` module) is automatically reexported by the OSGI framework. Indeed, for example Apache Felix automatically reexports all exported packages from all available JPMS modules, and if I'm correct it is the same with Equinox).
So, when using JDK9+, you should not have an error;

So, maybe you don't have the `jdk.unsupported` module referenced in your Eclipse RCP application (I never used RCP) ?

**if you are using JDK8 or <= 1.8 and OSGI at runtime**

It's only when using a version < 9 (like JDK8) where you may have a resolution error, and in this case you need to  configure your OSGI framework in order to reexport `sun.misc` from the system bundle. For example, from your configuration: 
```
org.osgi.framework.system.packages.extra=sun.misc;version=0.0.0
```

Alternatively, you can also install an extension bundle, like [this one](https://mvnrepository.com/artifact/com.diffplug.osgi/com.diffplug.osgi.extension.sun.misc/0.0.0)

Now, if reactor-core would import sun.misc optionally, I tend to think that it would be a bit dangerous. Let's say JDK8 is used, the OSGi framework does not reexport sun.misc from the system bundle, and reactor-core does import sun.misc optionally. So; In this case the following OSGI component bundle would be indeed installed without problems, and the handleRequest() method would work properly:

```java
import org.osgi.service.component.annotations.Component;
import reactor.core.publisher.Flux;

@Component
public class HelloComponent {
	
	void handleRequest() {
		try {
			Flux<String> flux = Flux.just("foo", "bar");
			flux.subscribe(System.out::println);
		} catch (Throwable err) {
			err.printStackTrace();
		}
	}
}
```

But now, let's say the handleRequest() does this:

```java
import org.osgi.service.component.annotations.Component;
import reactor.core.publisher.Flux;

@Component
public class HelloComponent {

	void handleRequest() {
		try {
			Flux<String> flux = Flux.just("foo", "bar")
                               .checkpoint("checkpoint", true);
			flux.subscribe(System.out::println);
		} catch (Throwable err) {
			err.printStackTrace();
		}
	}
}
```

In this particular case, since the checkpoint method internally uses `sun.misc.SharedSecrets`, then the service component bundle would be installed properly (because we import sun.misc optionally), but at runtime, when the handleRequest() is called, then we would have this exception:

```
java.lang.NoClassDefFoundError: sun/misc/SharedSecrets
	at reactor.core.publisher.Traces$SharedSecretsCallSiteSupplierFactory$TracingException.<clinit>(Traces.java:178)
	at reactor.core.publisher.Traces$SharedSecretsCallSiteSupplierFactory.get(Traces.java:173)
	at reactor.core.publisher.Traces$SharedSecretsCallSiteSupplierFactory.get(Traces.java:168)
	at reactor.core.publisher.Flux.checkpoint(Flux.java:3533)
	at coding.hello.HelloComponent.handleRequest(HelloComponent.java:14)
        ...
Caused by: java.lang.ClassNotFoundException: sun.misc.SharedSecrets cannot be found by io.projectreactor.reactor-core_3.4.26.RELEASE
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
```

so, I'm not sure whether is it safe to let the reactor-core import sun.misc optionally, especially in case the reactor-core jar is used within an OSGI runtime.
so, could you please clarify ? maybe I missed your point, or something else ?

thanks.

**Comment by pderop** [comment]
oops, I did a mistake , please ignore my previous post, sorry, will get back on this a bite later.

**Comment by vogella** [comment]
Thanks for the detailed reply, I wait for your new comments. The warning I see is created by the Eclipse Plug-in (bundle) development tooling. Maybe we report a false result here.

**Comment by pderop** [comment]
Hi @vogella ,

I double checked. What happens is that `sun.misc` is actually used only when using `JDK8`, not when using `JDK9+`. Actually, the `Traces` class inside reactor-core will choose whatever is available by doing some class loading in order to detect if JDK8 is used.

So, based on the example I gave earlier, when using JDK8, I believe it could be dangerous to optionally import `sun.misc`, because when running within OSGi, if this package is not reexported from the system bundle by the OSGI framework, then we may sadly come across an unfortunate CNF at runtime if the execution path is reaching the `Traces` class. So, in this case, better is to not install the bundle at startup time.

So, if you don't mind, I will close this issue, but if you disagree, please never hesitate to reopen, I'll get back to this.
thanks !

**Comment by vogella** [comment]
Thanks @pderop for your answer and the check. I'm fine with closing this issue, I will try to investigate on the Eclipse side. On the runtime side reactor works fine, it seems to be only a check in our tooling.

Thanks again for this very nice interaction.

**Comment by laeubi** [comment]
@pderop if you having different code/impl for different JVMs instead of detecting the running JVM Multi-Release-Jars are a much better, portable and save way: https://openjdk.org/jeps/238

**Comment by pderop** [comment]
@laeubi ,

probably it would be better,  but if I'm correct multi-release jars feature is only available from JDK9+, and we need to be compatible with JDK8.

**Comment by laeubi** [comment]
> @laeubi ,
> 
> probably it would be better, but if I'm correct multi-release jars feature is only available from JDK9+, and we need to be compatible with JDK8.

The good thing about Multirelease jar is that the are compatible with with any previous java version (then versioned classes will just be ignored) but Java 9+ will choose the correct class variant,

**Comment by pderop** [comment]
@laeubi ,

yes, you are correct, I'll think about that.
