### ISSUE TITLE
Unable to get traceid and spanid after error when connecting from mongoDB with using Hooks.enableAutomaticContextPropagation();

### ISSUE THREAD

**Issue by VinishKumar1** [reactor/reactor-core#3367]
We were unable to get traceid/spanid on log messages from .doOnError() or .onErrorResume(). We had below code:

    @GetMapping("/api1")
    public Mono<String> span1(@RequestHeader(value = "Correlation-Id", required = false) String correlationId,@RequestHeader(value = "Order-Id", required = false) String orderId) {
        log.info("test" + correlationId + ":correlationId");
        return Mono.deferContextual(contextView -> {
            return mongoRepository
                    .findById(orderId)
                    .doOnNext(i -> {
                            log.info("tested once");
                    })
                    .doOnError(i -> {
                            log.info("tested twice");
                    })
                    .onErrorResume(err -> {
                            log.info("onErrorResume");
                            Mono.error(
                                    new RuntimeException("Error occurred while storing bookingEntity in database"));
                            return Mono.empty();
                    })

                    .doFinally(i -> {
                            log.info("tested twice");
                    });
        });

We were unable to get the trace-id and span-id in messages in doOnError() or .onErrorResume().
Reactor [3.5.3]
Micrometer Context-Propagation [1.0.2]
Micrometer [1.10.4]
Micrometer Tracing [1.0.2]

**Comment by chemicL** [comment]
Please try adding `contextWrite` like this:

```
return mongoRepository
                .findById(orderId)
                .contextWrite(Function.identity())
```

For the time being this should propagate ThreadLocal values for you.

The issue is that `mongoRepository.findById()` works using a `Publisher` that is outside of Reactor's control. When It switches the `Thread` in the event-loop it uses, we need to restore TLs -> `contextWrite` provides such a barrier, which restores TLs for you.

We intend to introduce a global hook that will fix this problem without the need for integration libraries to do anything:
#3366.
