### ISSUE TITLE
Is it not possible to intercept processing requests across multiple microservices？

### ISSUE THREAD

**Issue by fatapan** [reactor/reactor-core#3444]
I am learning webflux for the first time, but I am having some problems when using it. Could you help me

![image](https://user-images.githubusercontent.com/77669844/234210093-7b590676-15aa-4a60-bca6-43ca112018ee.png)
I have 2 services, they all depency webflux-common.
In webflux-common, have 2 classes: 
![image](https://user-images.githubusercontent.com/77669844/234210881-2b3f07ba-39e5-442d-bcbb-271d6cdced29.png)
![image](https://user-images.githubusercontent.com/77669844/234210908-1f70c988-7461-4fa9-93da-544ea02ba19e.png)

I use postman invoke 'center-service' with AuthorizationToken, then in centerController, will invoke storage-service
![image](https://user-images.githubusercontent.com/77669844/234211458-dd4ad1b3-9b3a-4c6a-bcd9-ff5261b607ea.png)
![image](https://user-images.githubusercontent.com/77669844/234211592-293d2c11-f839-40e6-ab8f-0bc5ab3457ef.png)

but this will make exception
![image](https://user-images.githubusercontent.com/77669844/234212010-30b6e62e-72cc-4be7-915d-07dd156d049c.png)
![image](https://user-images.githubusercontent.com/77669844/234212501-5bc568dc-8452-4f21-aee3-e398aaf96a76.png)

My question is that I already have the contextwriter in the filter, why the deferContextual is not available, because of the asynchronous request? Or maybe there's something wrong with my way of writing it. How should I write it

**Comment by OlegDokuka** [comment]
@fatapan This is unrelated to reactor-core. 

I recommend to follow up with that at StackOverflow

**Comment by chemicL** [comment]
@fatapan from the code you provided it looks what you're doing is ok from the perspective of attaching the Context in the filter to the Monos produced by your controller. If the first service has the Authorization context value properly present in the controller, but the second does not, it probably is because you did not add any header in the WebClient request that the first service performs.

This is just a guess, but just wanted to offer some perspective on whether the use of Context looks ok - to me it does.

Please use stackoverflow for questions in the future. We use Github for bug reports and enhancement requests, not for questions.

**Comment by fatapan** [comment]
> @fatapan from the code you provided it looks what you're doing is ok from the perspective of attaching the `Context` in the filter to the `Mono`s produced by your controller. If the first service has the `Authorization` context value properly present in the controller, but the second does not, it probably is because you did not add any header in the `WebClient` request that the first service performs.
> 
> This is just a guess, but just wanted to offer some perspective on whether the use of `Context` looks ok - to me it does.
> 
> Please use stackoverflow for questions in the future. We use Github for bug reports and enhancement requests, not for questions.

Thank you for your advice.
As you said, I should need to use WebClient.builder().filter(), here setting the 'Authorization' that was previously put into the context to the header.
