### ISSUE TITLE
Ensure consistent behaviour of scheduler RejectedExecution across different usage scenarios.

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#347]
While reactor's built-in schedulers use an unbounded queue, in real-life situations executors will almost always be bounded and often schedulers will also be shared too.

It is clear from previous discussions with @smaldini that reactor if not designed to, and has no plans to handle scheduler rejection by permitting retry or applying back-pressure in reaction to this type of failures and instead scheduler rejection is treated as an unexpected/terminal exception which should fail/cancel the flux.

Assuming this is the case, it is important that:
- Behaviuor is as consistent as possible across different scenarios
- Data signals do not get dropped silently
- There is a way to receive notification via hook on all data signals dropped due to scheduler rejection.

Currently, there are a number of significant inconsistencies, and also some behaviour changes in 3.0.4 that could do with being reviewed. (as a side note, some things are also very different between reactor and rxJava)

In my mind the main/primary scenarios are:
1) `.publishOn(scheduler).doOnNext(..)`
2) `flaptMap(d -> just(d).publishOn(scheduler).doOnNext(..)).`
3) `.paralell(n).runOn(scheduler).doOnNext(..).sequential().`
4) `.doOnNext().subscribeOn(scheduler).subscribe()`
5) `.flatMap(d -> just(d).doOnNext(..).subscribeOn(..))`

Let's determine expected behaviour, ensure there is test coverage for behaviuor and create issues as required for any gaps.

**publishOn**
- PublishOn should fail/terminate by bubbling exception up on rejectedExecution, no onError signal means this can't be handled or re-tried. onOperatorError is invoked with failed signal & bubbled exception.  **[TO BE REVIEWED]**
- If the above scenario occurs in an inner stream of, for example a flatMap, should flatMap simply propagate bubbled exception up parent flux? The flatMap onNext call shouldn't call onOperatorError in this scenario really as this would result in duplicate error notification for a given data signal. **[TO BE REVIEWED]**

**parrelel**
- TODO

**subscribeOn**
- TODO

@smaldini Can we use GitHub Wiki to document and work through these scenarios or use and continually update this issue desciption? WDYT?

**Comment by smaldini** [comment]
@dfeist @rajinisivaram 

# All errors : 
- Scheduler Rejected Exception stack will not be swallowed anymore 
- Operators.onNextDropped will be called if no hooks for Operators.onOperatorError has been defined.

# PublishOn/RunOn (parallel)
- We might introduce downstream onError signal *in the current thread* for publishOn and parallelOn. This would exceptionally (ha) break the publishOn contract for the case of rejected schedule but reactor is designed to handled work stealing case well. It's also the least surprising behavior vs timeout because nothing happens downstream.
- Cancel is expected upstream on rejection

# SubscribeOn , CancelOn, Delay/Interval
- We are still investigating the scenario
