### ISSUE TITLE
Flux onSubsribe() operator

### ISSUE THREAD

**Issue by GeorgePap-719** [reactor/reactor-core#3567]
## Motivation

Coming from `kotlinx.coroutines`, after searching flux operators, I think there is no equivalent
operator of [onSubscription](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/on-subscription.html) operator.

This operator is pretty handy for general server-side applications where there is a need to call an
"action" first but with all emissions to the upstream stream that happen **inside** or **immediately after**
this "action" will be collected by this subscription.

For example, in my case, I use the `onSubscription` operator for **first** streaming all elements 
from the database, and **then** continue streaming from "source" directly. 

## Desired solution

Add `onSubscription` flux operator or an equivalent solution.

## Considered alternatives

I think an alternative solution is to combine "some" existing operators to achieve the desired
result.

**Comment by OlegDokuka** [comment]
probably what you are looking for is `doOnSubscribe` (https://projectreactor.io/docs/core/release/reference/#which.peeking)

**Comment by GeorgePap-719** [comment]
Hey oleg,

Thanks for the answer!

Im paying around with `doOnsubscribe`  but cannot achieve the desired result since it exposes only the `Subscription`.
Maybe do you happen to have any examples/links/javadocs for me to check?

**Comment by chemicL** [comment]
There is probably no such mechanism in Reactor which does exactly the same thing, but I believe you'd be able to use existing operators to achieve what you need. The situation you described:

> For example, in my case, I use the onSubscription operator for first streaming all elements
from the database, and then continue streaming from "source" directly.

would look like this potentially:

    Flux<Value> valuesFromDatabase;
    Flux<Value> sourceValues;
    return valuesFromDatabase.concat(sourceValues);

**Comment by GeorgePap-719** [comment]
Doesn't this operator has the same pitfalls of `startWith()` ? As i see the java docs:

>  Concatenation is achieved by sequentially subscribing to the first source then waiting for it to complete before subscribing to the next.

**Important note:** I forgot to mention that the `sourceValues` is a hot stream. Im trying to use an operator that 
 is similar to `onSubscribe()` to avoid losing (in the small gap) emitted items.

**Comment by chemicL** [comment]
As @OlegDokuka suggested, this question is more suited towards StackOverflow. I trust a proper use of operators will get you where you need, but the requirements need to be laid out properly. Consider using a `ConnectableFlux` and carefully pick the `doOn*` operator to hit connect to start the subscription process to the hot stream. Otherwise, perhaps a buffering strategy would get you where you need. The best choice is to spend some time playing around and getting to know the API, as it might be that there are different ways to achieve the same result, while what seems to be the case is trying to copy a habit from Kotlin's Flow to a different library. If after this exercise you still have a reproducible example where no combination of operators achieves what you need, we can consider an additional mechanism.

**Comment by GeorgePap-719** [comment]
ok, thanks for the pointers!

**Comment by OlegDokuka** [comment]
@GeorgePap-719 you may create your own operator using `Operators.lift` + `.transform` methods. You may find some examples in this blog post - https://spring.io/blog/2023/03/29/context-propagation-with-project-reactor-2-the-bumpy-road-of-spring-cloud
