### ISSUE TITLE
Spring Boot 3 webflux missing tracing information (e.g. traceId)

### ISSUE THREAD

**Issue by jhengy** [reactor/reactor-core#3691]
## Expected Behavior
After upgrading to Spring Boot 3, we had to switch our tracing library from spring cloud sleuth to micrometer tracing according to the migration guide https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide. It was mentioned that for reactor `Hooks.enableAutomaticContextPropagation()` needs to be called to enable automatic context propagation. We expect that doing so will help to propagate tracing information such as traceId in logs along the reactive chain.

## Actual Behavior
Despite already calling Hooks.enableAutomaticContextPropagation(), reactive chain involving reactive web client fails to preserve tracing information such as traceId in SLF4J logs when the chain is invoked using .subscribe.

## Reproductor
I have prepared a reproducer (spring boot test) to demonstrate the potential bug. Please refer to https://github.com/jhengy/my-simple-springboot-app/tree/demo-context-propagation

To solve the issue, it seems that we have to add .contextCapture() before .subscribe explicitly if reactive web client is used. However, for the same chain, using .block() instead of .subscribe() seems to preserve traceId out of the box without having to add .contextCapture. Is this an expected behaviour? Adding .contextCapture to all reactive chains ending with .subscribe seems a bit repetitive, is there a better and more convenient way (perhaps some kind of global setting) go about doing this? Thanks.

FYI, the original issue was raised in https://github.com/spring-projects/spring-framework/issues/31993

**Comment by chemicL** [comment]
Hey, @jhengy. Thanks for describing the issue and preparing a demo project. For most of the doubts, @bclozel [gave a very comprehensive response](https://github.com/spring-projects/spring-framework/issues/31993#issuecomment-1884552463). Especially the one about subscribe:

>Calling subscribe from within a reactive chain means that it decouples completely both reactive streams. In your sample's case, the WebClient will be performing its task completely independently of the controller method where it's been called.

From the above perspective:
- combined with the fact that the `ThreadLocal` state needs to reflect what is in the `Context`,
- and the fact that we're dealing with a **reactive** scenario, as opposed to an **imperative** one

-> If you decide to create disconnected reactive chains that don't share the `Context` with the pipeline that causes the new one's assembly, it's up to you to decide to capture the `ThreadLocal` values. In fact you don't need to use `contextCapture` - you're actually better off to populate the context directly, as the application would behave differently if you used the default (limited) propagation mode and [only logged in `handle`/`tap` operators](https://projectreactor.io/docs/core/release/reference/#_default_mode_operators_for_snapshot_restoration_handle_and_tap).

We had a lot of back-and-forth on this case so it's not unusual that you ask this question :) So the justification behind `.block()` performing automatic capture is that in most cases when `block` is called, it is within an imperative scenario, where the `ThreadLocal` values are the source of truth, instead of the Reactor `Context`. So to help users of, say, Spring MVC to use `WebClient` effectively capturing the tracing data, we decided to introduce the automatic capture to the blocking terminal operators.

And in pure reactive scenarios we just assume that one pipeline connects to another by implicitly subscribing to their results, just like `flatMap` consumes a newly created `Publisher` instead of expecting the user to directly call `subscribe` on it. In fact, [calling `subscribe` directly without getting a handle on its results](https://github.com/jhengy/my-simple-springboot-app/blob/demo-context-propagation/src/main/java/com/example/demo/ContextPropagationService.java#L48) creates an uncontrolled circumstance where you lose the ability of graceful cancelation or termination, so it's rather discouraged.

With the above, I'm closing the issue. However, let me just summon @marcingrzejszczak from the Micrometer team to highlight the fact that the Sleuth -> Micrometer Tracing migration document can be improved to mention the [Spring Boot's configuration for Reactor's context propagation mode (spring.reactor.context-propagation)](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.observability).

**Comment by marcingrzejszczak** [comment]
Updated the docs here https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide/_compare/9c2dce25be4b57d84b9914aab0384b04c2913f6f...00cf3017336384c2f6eb631bd989f1f6fa405320

**Comment by chemicL** [comment]
Thanks @marcingrzejszczak !

**Comment by stefan-g** [comment]
i'm facing the same problem that no micrometer tracing infos are propagated when i use subscribe. It's not quite clear to me if i have to add the tracing values manually or if it's done automatically? 

enableAutomaticContextPropagation() is called and the code looks like this:

```
      webClient.post()
               .uri(url)
               .contentType(MediaType.APPLICATION_JSON)
               .bodyValue(body)
               .retrieve()
               .toBodilessEntity()
               .doOnError(throwable -> log.error("Failed", throwable))
               .contextCapture() //add tracing infos
               .subscribe(voidResponseEntity -> {}, throwable -> log.error("Processing reactive stream failed", throwable));
```

**Comment by chemicL** [comment]
@stefan-g you responded to a close issue. For questions, please try StackOverflow, Gitter, or the Micrometer Slack, where such questions are raised and discussed. For your particular situation it is really difficult to say without additional calling context (where is this called). When you ask in one of the mentioned resources, make sure to describe the situation (e.g. this is called as part of a WebFlux request handling in the controller, etc.). Oftentimes, clarifying such things you'll notice what was incorrectly set up.
