### ISSUE TITLE
Mono#timeout not working (HTTP requests)

### ISSUE THREAD

**Issue by SimoneGiusso** [reactor/reactor-core#3837]
## Expected Behavior
I have this method:

```
    private Mono<MyDTO[]> doRequest(List<Request> requests) {
        return Flux.fromIterable(requests)
            .map(Request::getParams)
            .buffer(config.getBatchSize())
            .map(params -> new HttpEntity<>(params, httpHeaders))
            .flatMap(request ->
                Mono.fromCallable(() -> {
                        log.info("Calling the service with a batch of {} requests...", request.getBody().size());
                        return plain.postForObject(config.getUrl(), request, MyDTO[].class);
                    })
                    .name("External Service")
                    .timeout(config.getTimeout()) -- Setting timeout of 10 seconds
                    .retryWhen(retrySpec)
            )
            .reduce(new MyDTO[]{}, ArrayUtils::addAll)
            .onErrorMap(TimeoutException.class,
                e -> new IllegalStateException(getRootCauseMessage(e))
            )
            .subscribeOn(boundedElastic()); // by default 10x detected CPU cores
```

I would expect that, if `plain.postForObject` (plan is an instance of `RestTemplate`), takes more that 10s to respond, a `TimeoutException.class` is thrown and therefore mapped to `IllegalStateException.class`.

## Actual Behavior
Timeout setting seems not be taken in consideration and the RestTemplate goes into timeout due to the timeout set for the client (i.e. SocketTimeoutException is thrown when reaching the 60s threshold):

```
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://anurl": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:791)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:443)
	at com.myproject.MyClient.lambda$doRequest$10(MyClient.java:127)
	...
```

## Steps to Reproduce
I wrote this test but in fact I wasn't able to reproduce the issue, and the test passes:

```
        when(plain.postForObject(anyString(), any(), any())).thenAnswer(
            // simulate (infinite) blocking call
            new AnswersWithDelay(1_000_000, invoke -> new OpenFIGIDTO[]{})
        );

        StepVerifier.create(client.doRequest(requests)
            .verifyError(IllegalStateException.class);
```

* Reactor version(s) used: 3.4.34
* JVM version (`java -version`): 21-temurin

Is there something wrong with the code or may be an issue with reactor?

**Comment by chemicL** [comment]
Hi @SimoneGiusso :)

As far as I can tell, the problem lies in the fact that you are using reactor in combination with a blocking `RestTemplate` client. The `Callable` that you provide has no notion of cancellation or interruption, so the timeout that kicks in from a different `Thread` has no influence over that blocking call and ends up being ignored. Normally, this would not even be allowed, but as you use `subscribeOn(boundedElastic())` you effectively stall the processing until the `postForObject()` call returns. The only mechanisms that you can leverage in such a case are the timeouts that `RestTemplate` or the underlying engine provide.

Consider using `WebClient` or another non-blocking, reactive Http Client utility (e.g. vanilla Reactor Netty's `HttpClient`) and you will be able to take advantage of timeout and other operators.

As I consider this a non-issue, I'm closing the report. Please consider StackOverflow or Gitter for questions in the future as per [our guidelines](https://github.com/reactor/.github/blob/debbeab9db6a8742630fba3aec0cb4cda7156c38/CONTRIBUTING.md#question-do-you-have-a-question).
