### ISSUE TITLE
Add tests for  #425, WorkQueueProcessor async cancel fix

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#426]
#425 introduced a fix to the previous async cancel change in `WorkQueueProcessor` and it was mentioned that it needed more tests.

@dfeist you said you had 70 failing tests around that in your code, any chance you could derive a few tests suitable for reactor out of that?

**Comment by dfeist** [comment]
Actually I see have some failing tests :-( Not 70, but still not quite working as expected..

I have a processing flow created like this:
```
 Sink -> WorkQuueueProcessor.create(false).parallel().transform(processFlow()).retry().subscribe()
```

Where `processFlow` is basically something like this :
```
Function<Publisher<Event>,Publisher<Event>> processFlow() {
  for(Processor p: processors) {
    if(p.isBlocking()) {
      flux = flux.flatMap(event -> just(event).subscribeOn(IO).transform(p);
    }
    else {
      flux = flux.transform(p);
    }
  }
  return flux;
}
```

The issues I'm having IMO are related to the fact i'm combining `WorkQueueProcessor` with `retry()` with `PublishOn`.  If i modified what I have above to remove the async hand-off or remove the parallel() i still get issues. I only get expected behaviour when i remove both and it's all sync.

I tried to create some tests that i think reproduce the issues i'm having here:  https://github.com/reactor/reactor-core/pull/427

Please reach out to me explanation of scenario or test cases are not clear.

**Comment by smaldini** [comment]
Unless i miss something this is fixed @dfeist ?
