### ISSUE TITLE
Reduce number of cancel in mono flows

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#442]
Mono.subscribe(lambdas...) for instance does cancel onNext which is unnecessary waste of cpu given the nature of Mono but also leads some cancel sensitive operator to react.

**Comment by smaldini** [comment]
LambdaFirstSubscriber currently cancels onNext, should not as its source is only ever a Mono.
Needs to review if other Mono operator only taking a Mono is behaving the same as some log() output showed a few times both cancel()/onComplete()

**Comment by simonbasle** [comment]
Find operators used only by Mono, and look for `cancel()` in `onNext`. Identified:

- [ ] `block` (might need to be duplicated for `Mono` specifically in order to remove the `cancel`)
- [ ] `BlockFirstSubscriber` (inside `dispose()`)
- [ ] `MonoProcessor` could be guarded, but only if the `Publisher` is a `Mono`... ensure that the public API can only input a `Mono`, and if so cancel if publisher != null.
- [ ] ...
