### ISSUE TITLE
Fluxes combined with Flux#combineLatest do not publish at the same pace

### ISSUE THREAD

**Issue by evacchi** [reactor/reactor-core#45]
Example snippet:

```java
    static class Iter implements Iterator<Long> {
        long count = 0;
        @Override public boolean hasNext() { return true; }
        @Override public Long next() {
            try {
                Thread.sleep(10);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            return count++; }

    };


        final Flux<Long> s1 = Flux.fromIterable(Iter::new).publishOn(SchedulerGroup.single());
        final Flux<Long> s2 = Flux.fromIterable(Iter::new).publishOn(SchedulerGroup.single());


        Flux.combineLatest(
                v-> Tuple.of((long)v[0],(long)v[1]), 1,
                s1, s2 //, (l,r) -> Tuple.of(l,r)
        ).consume(t -> System.out.printf("(%d,%d)\n", t.getT1(),t.getT2()));
```

Using e5a23a210351f46542c7832083298db84004c64c ; I would expect to see a pair of approx the same values on the two sides, instead there are sometimes large gaps between the values, e.g.:

```

(1438,5)
(1439,5)
(1440,5)
(1441,5)
(1442,5)
(1443,5)
(1444,5)
(1445,5)
(1446,5)
(1447,5)
(1448,5)
(1449,5)
(1450,5)
(1451,5)
(1452,5)
(1453,5)
(1454,5)
(1455,5)

```

I'm not sure if I'm doing something wrong here

**Comment by akarnokd** [comment]
Strange. Due to the backpressure and prefetch inside the operator, it is possible one thread or the other cannibalizes the emission, especially if they are instant sources such as yours. If I run your code with Rsc and plain ExecutorService, I get a fairly advancing pairs, sometimes one or the other gets stuck for a few hundred milliseconds, but I still get like `69215, 122898` after a few seconds. 

The code of `Flux.combineLatest` and `Rsc.combineLatest` are identical so I guess there is something non-fair in `SchedulerGroup.single()` perhaps?

**Comment by smaldini** [comment]
I look into it after reactor-netty refactor and sync with Scheduler contract from RSC

**Comment by smaldini** [comment]
You can now use RSC based schedulers via Schedulers.fromExecutorXxx or single/parallel, the SchedulerGroup generated Schedulers are now provided under Schedulers.computations and are encouraged for non blocking stuff.
