### ISSUE TITLE
Add Mono.untilOther (would behave like a conceptual Mono.and(Publisher<Void> other)) 

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#465]

**Comment by simonbasle** [comment]
Add `Mono<T> and(Publisher<Void> other)` that triggers subscription on both (like `and` does) and uses simply the left-hand side as the return value in zipper function.

Possibly add `Mono<U> and(Publisher<Void> other, Function<T, U> mapperFunction)` as well.

**Comment by dfeist** [comment]
@simonbasle I don't know really see why that other signature is needed, what would you want to map if the other Mono is of type `Void`?

In think in general some of these and/when methods do need reviewing to see if they can't use `Publisher` rather than require `Mono`

**Comment by simonbasle** [comment]
The second signature mirrors the one with a `BiFunction<T, T2, O>`: `public final <T2, O> Mono<O> and(Mono<? extends T2> other, BiFunction<? super T, ? super T2, ? extends O> combinator`

The idea is that instead of a combinator, when doing an `and` with a `Publisher<Void>` it becomes simply a transformation function of the left-hand side.

**Comment by simonbasle** [comment]
After discussing this with @smaldini, we came to the conclusion that this use case needs a new underlying operator. We also agreed on the name `untilOther` rather than making it part of the `and` family. The added benefit is that it works with any `Publisher` as the "other", triggering the emission of the `Mono` source as soon as the other publisher either emits something or completes.
