### ISSUE TITLE
Consider applying work-stealing to TopicProcessor/WorkQueueProcessor

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#472]
@smaldini you'll probably need to elaborate :)

**Comment by jbrisbin** [comment]
Please don't do this. We've already had problems with this in other places and with high volumes and multiple pipelines, in practice, the stealing converges all work onto a single thread once one thread starts to drain. This happens when you chain processors together and use sinks to publish between them.

**Comment by smaldini** [comment]
Yes it was a consideration from some discussion with @dfeist but its clearly not priority and without explicit alternatives for fairness not yet there.
EmitterProcessor does that somehow anyway.
