### ISSUE TITLE
Need an error handler method on Flux when processing a stream of elements

### ISSUE THREAD

**Issue by victor-ferrer** [reactor/reactor-core#49]
HI, perhaps this is already available in the Flux API but I couldn´t find and I think that could be interesting. I´d like to have a way to handle discrete errors while processing a stream of elements.

For instance, see this code:

```
Flux<StockQuotation> processingFlux = Flux.fromIterable(tickers)
// Get each set of quotes in a separate thread
.flatMap(s -> Mono.fromCallable(() -> feeder.getCSVQuotes(s)))
// Convert each list of raw quotes string in a new Flux<String>
.flatMap(list -> Flux.fromIterable(list))
// Convert the string to POJOs
.flatMap(x -> {
		try {
			return Flux.just(converter.convertHistoricalCSVToStockQuotation(x));	
		}
		catch (IllegalArgumentException ex){
			System.out.println("Error decoding stock quotation: " + x);
			return Flux.empty();
		}
});
```

I need to write this bulky try {} catch{} block to handle single errors and continue processing the rest of the flux. The methods I have seen so far allow me to return a specific value or to restart processing the flux from the beginning.

See this Stackoverflow question:
http://stackoverflow.com/questions/36237230/how-to-handle-error-while-executing-flux-map

As "akarnokd" comments, errors are terminal signals but perhaps this new method would help people developing with Reactor.

Thanks!
Victor

**Comment by smaldini** [comment]
Hey Victor, I just read your blog post it was a very informative one, well done !

Let's speak about patterns. As you highlighted, error is a terminal event but there are a few ways to deal with that and it goes down to subscription lifecycle.

First , `fromIterable` is what we consider a source, there's no parent, and its content is actually replayable  since mapped from memory (Iterable) so we call it "cold" source.

The `Publisher` chain created by calling various operators is immutable and refer back to that `fromIterable` Source. When `subscribe()` is eventually called, it navigates back to that source to create operator instance that serves as `event receiver/emitter Subscriber` and `Subscription` request tracker. When there's no more parent, these Subscriber are being called via `onSubscribe` from `fromIterable` to the right. Their unique state is created, that state can be terminated only once.

The role of the operators like retry() is to use the immutable parent reference and a given condition to 're-subscribe' to the parent (or a given fallback sequence if we look at onErrorReturn etc).
So in your example we will restart from the beginning, 1, 2 and error again. 

An alternative to the flatMap solution is to disable that "restarting" behavior and make the sequence definitive and not replayable. The operators `publish` and `multicast` or even `subscribe` turn any `Flux` or `Mono` into a unique sequence that will be the new point of reference for late subscribers.

```java
 Flux.fromIterable(tickers)
     .publish()  // Turn source into hot Publisher
     .autoConnect() // Instructs the hot Publisher to start when at least one `Subscriber` subscribes
     .flatMap() //Business logic that might fail
     .retry(3) //retry on any error up to 3 times
     .consume(System.out::println)
```

**Comment by smaldini** [comment]
Consider also frequently failing (and latency impacting) business logic to be wrapped as `Mono.fromCallable` as you don't have to catch the exception, the `Callable` throws. Then a simple `flatMap`/`then` can do the trick of protecting these individual timelines.

Basically creating new `Publisher` for failing or impacting logic is advised as you will get to isolate by design the sequences, which map well with a sequence diagram btw.

**Comment by victor-ferrer** [comment]
Hi @smaldini,

Thanks for your answer. I´m still struggling to understand the whole model involved here but I supposed that the _Mono.fromCallable + flatmap_ is enough for the moment.
The idea I had when I opened this ticket, was not only about encapsulating that _Mono.fromCallable + flatmap_ in a method, but perhaps also allowing the user to specify a[ Dead Letter Flux](https://en.wikipedia.org/wiki/Dead_letter_queue) where the errors could be sent to be processed.
Could that be useful?

**Comment by smaldini** [comment]
Related to #73

**Comment by smaldini** [comment]
related to #80

**Comment by dfeist** [comment]
I think this is more related to #89 than #80.  The proposal in #80 is not to handle the errors but just to hide the try/catch in a utility function. 

What both me and @victor-ferrer are trying to do is handle an exception thrown within an operator before it calls `next.onError()`.  I want to wrap the exception in #89 where as victor wants to be able to drop the current event, (which is actually almost identical to my use case in #74).

Using a `flatMap()` as we both are currently is definitely a valid approach to tackling these use cases, i'm just not convinced it's the best long-term approach, especially given the complexity/overhead this adds to the constructed chain if this needs to be done many times for different components/operators.

**Comment by smaldini** [comment]
Considering close since Flux#handle and extra Hooks features
