### ISSUE TITLE
MonoCreate disposes existing Disposable

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-core#522]
When diagnosing an issue in `reactor-netty` @smaldini identified what he believed was a bug.  When a `MonoCreate` already has a `SinkDisposable` it is [disposed when it is replaced](https://github.com/reactor/reactor-core/blob/f8786d7112b14ee23b5aa348e153081dc1634d46/src/main/java/reactor/core/publisher/MonoCreate.java#L185-L200).  He seemed to believe that this was both unnecessary and incorrect.

**Comment by smaldini** [comment]
It might be a behavior we agree on at this level and prefer to fix in reactor-netty as well directly.

**Comment by akarnokd** [comment]
FYI, in the original Reactor 3 `create()` function and the current RxJava 2 `create()` behavior is intentional: in case people set more than one resource, the old resource is not leaked but disposed. You can always set a container and work with that, for example, to support multiple resources, you can set a `CompositeDisposable` and then add/remove/delete items as you see fit.

**Comment by smaldini** [comment]
Yes I was thinking about that, I wanted to introduce such facility especially to make it easier to use OpenHashSet, so i'm thinking that for now its a reactor-netty issue to deal with that in the retry logic which causes this in `PooledClientContextHandler`
