### ISSUE TITLE
MonoSink.error() may bubble an exception while docs say it shouldn't

### ISSUE THREAD

**Issue by oleg-alexeyev** [reactor/reactor-core#560]
With reactor-core 3.0.6 I've got some strange exception with the following stack frames on the top:
```
               at reactor.core.Exceptions.bubble(Exceptions.java:98)
               at reactor.core.publisher.Operators.onErrorDropped(Operators.java:292)
               at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:152)
```
While it must be something tricky in our code, the JavaDoc for `MonoSink.error()` say `Calling this method multiple times or after the other terminating methods has no effect.`. And according to sources `Operators.onErrorDropped(e);` is called when `state` is already set to `HAS_REQUEST_HAS_VALUE`.

Shouldn't it ignore the error or should the docs be changed?

**Comment by smaldini** [comment]
Doc should be amended because this is a fatal exception for us and we cannot silently drop/ignore errors. Flux.create/Mono.create simplify almost all component of publishing in a backpressured way but we cannot prevent API wise a double call to error or a next + an error. Especially this often highlight a possible race condition issue with user code flow. We could eventually add MonoSink#isDisposed like FluxSink to help users mitigate this scenario tho.
