### ISSUE TITLE
UnicastProcessor + materialize and then dematerialize omit first item 

### ISSUE THREAD

**Issue by OlegDokuka** [reactor/reactor-core#585]
## Issue
Combination of `UnicastProcessor` in a source role + combination of sequence of materialization and dematerialization operators omit first passed item by unicast processor 

## Steps to reproduce 
To reproduce issue just run following example:

```java
        UnicastProcessor<Integer> processor = UnicastProcessor.create();

        StepVerifier.create(processor
                .materialize()
                .dematerialize()
                .flatMap(Flux::just))
                .expectSubscription()
                .then(() -> processor.onNext(1))
                .expectNext(1)
                .then(() -> processor.onNext(2))
                .expectNext(2)
                .then(processor::onComplete)
                .expectComplete()
                .verify();
```  

mentioned test leads to infinity waiting since there will be no passed element to expectation.

## Actual result
the following test will be passed and totally confusing all expectation:

```java
        UnicastProcessor<Integer> processor = UnicastProcessor.create();

        StepVerifier.create(processor
                .materialize()
                .dematerialize()
                .flatMap(Flux::just))
                .expectSubscription()
                .then(() -> processor.onNext(1))
                .then(() -> processor.onNext(2))
                .expectNext(1)
                .then(processor::onComplete)
                .expectComplete()
                .verify();
```

## P.S
Issue is reproducing with all kind of processors.

## P.S.S
Issue is not reproducing with the follow example 
```java
        UnicastProcessor<Long> processor = UnicastProcessor.create();

        StepVerifier.create(Flux.interval(Duration.ofMillis(1))
                .subscribeWith(processor)
                .take(10)
                .materialize()
                .dematerialize()
                .flatMap(Flux::just))
                .expectSubscription()
                .expectNext(0L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L)
                .expectComplete()
                .verify();
``` 

## P.S.S.S
Also issue is not reproducing with the follow operators rearrange:
 
```java
        UnicastProcessor<Integer> processor = UnicastProcessor.create();

        StepVerifier.create(processor
                .materialize()
                .dematerialize()
                .flatMap(Flux::just))
                .expectSubscription()
                .then(() -> processor.onNext(1))
                .then(() -> processor.onNext(2))
                .expectNext(1)
                .then(processor::onComplete)
                .expectNext(2)
                .expectComplete()
                .verify();
```

**Comment by simonbasle** [comment]
Looks like your second test doesn't hang but doesn't pass either (it receives onNext(2) and fails because the expectation is onComplete)...

The way `dematerialize` is implemented, it apparently emits the previously dematerialized value only upon receiving the next event. Since you hold off the emission from the `Processor` rather than honoring the materialize request, it hangs waiting for a next event that will never come (because the `StepVerifier` is itself waiting for an onNext).

I'm not sure about the rationale behind this implementation, perhaps @smaldini can comment on that?

**Comment by simonbasle** [comment]
Note that RxJava2 has a slightly different approach, with its own drawback: 
 - our version tries to peek for the next signal in order to eagerly complete/error if we just received the last onNext. in terms of backpressure on a 2 elements sequence, this means that requesting 2 will effectively give you 2 onNext *and* an onComplete. Drawback is you have to be aware of that "prefetch", and if you produce items one by one you can get stuck, like in your test.
 - in RxJava, the operator doesn't try to peek and just propagates the request as is. Drawback is that for the same case, you have to perform an additional request(1) to get the completion signal.

There was an issue around removing the need for that extra request in RxJava 1 but it was abandoned, see ReactiveX/RxJava#3136

**Comment by simonbasle** [comment]
Couldn't find an easy fix for this and it boils down to the processor usage pattern, causing a stepverifier lock. Closing as `wontfix` for now.

Please open a separate issue linking to this if you strongly feel the RxJava way is better, despite its requirement of an additional `request(1)` to get to the terminal event.
