### ISSUE TITLE
StepVerifier recording doesn't work with ParallelFlux

### ISSUE THREAD

**Issue by asarkar** [reactor/reactor-core#598]
```
StepVerifier.create(Flux.range(1, 5)
    .parallel(10)
    .runOn(Schedulers.parallel())
    .map(i -> "https://www.google.com")
    .flatMap(uri -> Mono.fromCallable(new HttpHeadTask(httpClient, uri))))
    // .recordWith(ArrayList::new)
    // Fails with Expected size:<5> but was:<1>
    // .consumeRecordedWith(results -> assertThat(results).hasSize(5))
    .consumeNextWith(verifier)
    .consumeNextWith(verifier)
    .consumeNextWith(verifier)
    .consumeNextWith(verifier)
    .consumeNextWith(verifier)
    .verifyComplete();
```

`HttpHeadTask` is a `Callable` whose actual implementation is irrelevant in this case, it makes a HTTP HEAD call to the given URI and returns the hostname if successful.

verifier:
```
private final Consumer<String> verifier = uri -> assertThat(uri).isEqualTo("www.google.com");
```

**Comment by simonbasle** [comment]
@asarkar sorry for the late reply. Are you saying that the `consumeRecordedWith` doesn't work but the `consumeNextWith`s do?

If so, this is just a misunderstanding on how `consumeRecordedWith` works. It won't necessarily let the sequence finish before doing the assertion. Rather, the expected usage is continue using `expectXxx` methods in order to populate the record, then do a last swipe on the collection of items that passed these intermediate expectations.

Typically:
```
// start recording each item passing / pulled by further expectations
.recordWith(ArrayList::new)
// assert 5 elements pass, all populating the record
.expectNextCount(5)
// once we've got 5 elements, one-swipe assert the record
.consumeRecordedWith(results -> assertThat(results)
		            .hasSize(5)
		            .allSatisfy(verifier))
//that's it! no more data is expected
.verifyComplete();
```

**Comment by asarkar** [comment]
Verified works as described above, although the behavior is not very intuitive. Thanks @simonbasle.
