### ISSUE TITLE
FluxStream does not close Stream

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#622]
`FluxStream` should close the `java.util.stream.Stream` when it has consumed all of the items

**Comment by smaldini** [comment]
I think we won't fix that I prefer to amend doc if required, but in general if your Stream has side effect or is basically stateful that iterator() is not enough to use it, its maybe a [dodgy] IO stream and you are one doOnTerminate away from cleaning it up.
The usual answer would be to try|catch since they are closeable, but in our case, we iterate eventually in another thread. Let me know if that makes sense

**Comment by osi** [comment]
my case is a stream that's wrapping IO. makes sense, currently i'm using try-with-resources to close the stream. 

additional documentation might be good, since some JDK provided streams do require closing (such as `java.nio.file.Files#lines(Path)`
