### ISSUE TITLE
Improve support for timeout in StepVerifier

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#651]
_From @rstoyanchev on May 5, 2017 13:36_

For the vast majority of our tests (100%) we don't want to hang indefinitely. We can specify `Duration` but that's a case of a good practice made harder and for what it's worth we have 216 usages of `.verify()` vs 29 of `verify(Duration)` where ideally all should have a timeout.

The problem is made worse by the various `verifyComplete` and `verifyError` shortcuts which we also use and for which there is on way to specify a timeout.

I can fix the tests but this feels wrong. It's making me do extra work and continue to do that over time but I can't think of a use case where StepVerifier should wait indefinitely, is there one? 

I'd like to suggest for `StepVerifier` to have a default timeout so that tests are not required to type in a `Duration` by default. I don't see any details for #646 but it seems to be along these lines. Rather than detecting hanging let's eliminate the possibility that it could occur unless you explicitly waive the timeout.

This would make it possible to use any of the verify shortcuts, guilt free. In addition we could also consider an option to customize the default timeout independent of calls to verify possibly even eliminating `.verify(Duration)` altogether.

_Copied from original issue: reactor/reactor-addons#108_

**Comment by simonbasle** [comment]
@rstoyanchev I think having a default timeout on `verify()` (and thus all shortcuts) is very feasible. How about 30 seconds default timeout?

(Having a way of tuning the timeout separately is a bit more difficult due to how the interfaces of the builder chain together)

**Comment by rstoyanchev** [comment]
A default timeout would be a big improvement in itself. 30 seconds for a test to hang is too much though. It is better than hanging indefinitely but imagine an integration test suite where similar tests fail each hanging 30 seconds, it adds up.

If a test legitimately needs more than 5 seconds to run that would be a good case for using a timeout value. So the default timeout value in my opinion should be optimized to be more minimal rather than more generous so that tests can complete and you can see all failures. Longer tests should be arguably be documented so through the use of `.verify(Duration)`.

**Comment by nebhale** [comment]
I get the difficulty here (heck we apparently do this [at least 109 times in our code](https://github.com/cloudfoundry/cf-java-client/search?utf8=✓&q=.verify%28Duration.of&type=)), but I don't think this should be changed.  I think that `verify()` should behave the same way that `Mono.block()` does since they have similar blocking semantics.  If no `Duration` is specified, there is no duration; if a `Duration` is specified, there is a duration.

**Comment by smaldini** [comment]
On the other hand we could think about it with verifyComplete/verifyError, which have specific deterministic purpose (and could do with Duration arg aliases too).

**Comment by osi** [comment]
I agree with @nebhale about keeping the status quo. If someone wants a global timeout, they can do that with Junit (https://github.com/junit-team/junit4/wiki/timeout-for-tests)

**Comment by rstoyanchev** [comment]
> I think that verify() should behave the same way that Mono.block() does since they have similar blocking semantics.

I don't think the comparison stands. I see that conceptually they're the same but it's in the context that matters. `Mono.block()` is the exception (an anti-pattern if you will) while `verify()` is the norm in testing. It's the primary way of using this API and having to specify a Duration every time is making the right thing difficult. Would you ever not want a test to time out?

The second difference is that unlike `Mono.block()` with `StepVerifier` there are quite a few verify shortcut methods and all those do not provide a way to specify a timeout value.

**Comment by rstoyanchev** [comment]
> If someone wants a global timeout, they can do that with Junit

Interesting suggestion although I suspect that may not play well with integration tests that use network resources.

**Comment by osi** [comment]
my experience using StepVerifier so far has been that the current modes of operation are fine. hanging-vs-timeout are the "same" for me. if i'm running tests manually in my IDE, i'll see that they're hanging and can inspect. my CI server is setup with a build timeout that fails the build if it takes too long.

the failure mode currently is that a test might hang.

the failure mode with a "default" timeout is that you might get a timeout because you're test is bad, _or_ because the default timeout is too low. that makes analyzing the failure more work, imo.

**Comment by rstoyanchev** [comment]
> because you're test is bad, or because the default timeout is too low

I suspect in the typical case you'll know the difference but I do recognize that what makes a good default value could vary a lot from application to application.

What I would like is a way to specify a default timeout value that works for me and not be forced to express it every time. The end result I'm looking for is that I don't have to kill my build on the first hanging test but let it run in the background and tell me all that's failing.

**Comment by nebhale** [comment]
@rstoyanchev

> The second difference is that unlike Mono.block() with StepVerifier there are quite a few verify shortcut methods and all those do not provide a way to specify a timeout value.

Agreed, and I've chewed @smaldini's ear on that resulting in [this](https://github.com/reactor/reactor-core/issues/651#issuecomment-305863471).

> What I would like is a way to specify a default timeout value that works for me and not be forced to express it on very single verify call and also to be able to use the shortcut methods.

This is more interesting to me.  Some sort of property/configuration would meet this requirement while keeping the current semantics of `verify()` for those that don't override the default configuration.

**Comment by smaldini** [comment]
We can easily affect a default static value for StepVerifier as we do with global stuff in Schedulers or Hooks. This is not a critical change and unless a tester is trying hard to defeat StepVerifier, or is using parallel testing with testNG that would touch this config with different values.
