### ISSUE TITLE
Intercepting thread switch

### ISSUE THREAD

**Issue by Kindrat** [reactor/reactor-core#707]
Hi. I'm trying to mimic spring session behaviour with reactor, but it's difficult to use old good thread-locals in multithreaded pipeline. Maybe there are some built-in utilities aka hooks to catch the moment context is switched in publishOn/subscribeOn ?
Or the only way is to use custom schedulers and handle everything manually?

**Comment by simonbasle** [comment]
`ThreadLocal` mecanism is not adapted to reactive programming libraries like Reactor, because several `Flux` can actually be processed partially or totally on a same `Thread`. You can enforce isolation _to some degree_ by having each "session" `Flux` run on a dedicated `Scheduler`, but that's negating one of the main benefits of reactive programming (that is: limiting the amount of threads created).

Rather than trying to shoehorn the threadlocal approach into Reactor, we are currently working on providing a per-`Flux`/`Mono` `Context`. `contextXXX` APIs should be part of `3.1.0.M3`, but for now this is low level and there is no reference documentation yet.

**Comment by smaldini** [comment]
Could you elaborate on your use case btw to see how it fits in our context story ?

**Comment by Kindrat** [comment]
Just trying to reuse existing spring-session flow with reactive app. For now we are passing our custom ThreadFactory to parallel stream that is copiing threadlocal with session id on thread creation and intercepting thread switch - aka publishOn/subscribeOn. To copy on existing pool threads we are using extended parallel stream where default ScheduledExecutorServices are changed to our custom with overriden ThreadPoolExecutor#beforeExecute/ThreadPoolExecutor#afterExecute to pass threadlocal through whole chain.

Doing so we are able to utilize spring-session without writing it from scratch for reactor while waiting for spring 5 with native support of reactive pipelines.

**Comment by simonbasle** [comment]
This sounds like an interesting approach, as a workaround until our own context mechanism can come into play 👍
