### ISSUE TITLE
Emitter processor does not satisfy ringbuffer description claimed in class docs

### ISSUE THREAD

**Issue by Kindrat** [reactor/reactor-core#763]
### Expected behavior
Elements are overriding oldest entries in queue if queue is full

### Actual behavior
Processor blocks thread in a infinite loop waiting for a free space in queue

### Steps to reproduce

```	
        @Test(timeout = 5000)
	public void testRingbufferOverflow() throws Exception {
		int bufferSize = 10;
		EmitterProcessor<Integer> processor = EmitterProcessor.create(bufferSize);
		for (int i = 0; i < bufferSize * 10; i++) {
			processor.onNext(i);
		}
                processor.onComplete();

		List<Integer> block = processor.collectList().block();
		assertThat(block).hasSize(bufferSize);
	}
```

### Reactor Core version
3.1.0.BUILD-SNAPSHOT (current master revision)

### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### OS version (e.g. `uname -a`)
Linux 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by smaldini** [comment]
It indeed changed in M2 or M3, It's now using the same code as in Flux.publish for alignement. That means it doesn't leak anymore old data by keeping them forever (which was a reported issue with the old EmitterProcessor which was RingBuffer based). TopicProcessor and WorkQueueProcessor still use RingBuffer with the intended thread boundary (one thread per subscriber) ring buffer works best with. It's costly since it books these resources, but if you think singleton Topic/WorkQueue processor its just fine.

All that said, it seems there's an issue in behavior that can be solved as well with the current code, a regression dare I say. We should be draining the queue if no subscriber is attached as before and  that's a reasonable behavior to question. Would you like us to implement a pr to evaluate ?

**Comment by Kindrat** [comment]
Could be very useful for situations when subscriber is closed leaving producer thread blocked

**Comment by simonbasle** [comment]
@Kindrat There is a problem with your initial assertion: the RingBuffer usage didn't imply that old values would be dropped, on the contrary. The RingBuffer, when full, blocks until a slot becomes available. In fact, your test times out with 3.0.x versions where `EmitterProcessor` is still backed by a `RingBuffer`.

I think I have an improvement, nonetheless. Here is what I propose:
**sending data while there are subscribers**
 - if these subscribers never request the processor (do not consume enqueued data), once the processor has enqueued to capacity it will block (looping on `parkNanos`) as before.
 - two possibilities to unlock this situation:
    - if the subscriber starts consuming concurrently to the bufferSize-th`onNext`, it will free up a slot and resume the onNext (potentially ultimately consuming it). Loop back to first step.
    - if the subscriber is cancelled and auto-cancel is **false** it will **recycle/drop oldest element** then enqueue the onNext. See no-subscriber case below for the following steps.
    - if the subscriber is cancelled and auto-cancel is **true** it will **clear the queue** and enqueue the onNext. See no-subscriber case below for the following steps.

**sending data while there are NO subscribers**
 - if the queue contains less than `bufferSize` elements, the onNext is enqueued
 - if the queue contains `bufferSize` elements, the **oldest element is dropped** and the onNext is enqueued.

Once a subscriber comes in, it will drain the processor and receive the last `bufferSize` elements.
This means that a second subscriber coming in after that will receive nothing (independently of auto-cancel).

wdyt @smaldini ? I have updated PR #814 accordingly (and created issue #823 for the separate change to `Operators.onNextDropped()`, which is kind of orthogonal).

**Comment by simonbasle** [comment]
@Kindrat after discussing it with @smaldini we won't go ahead with my suggested change above. We instead advise you to use the `sink()` rather than directly the `onNext`. Namely, to use the `onRequest` callback inside the `sink()` to perform **exactly as many `sink.next(...)` as there are requests**.

We might even protect the `processor.onNext()` against usage without subscribers in the future (eg. by throwing an exception that gives the same advice as above, use the sink Luke). Especially for the processors that have backpressure (`EmitterProcessor`, `TopicProcessor`, `WorkQueueProcessor`).

We might also add a `BLOCK` strategy to be more explicit.

**Comment by Kindrat** [comment]
@simonbasle throwing exception just to catch it where onNext is called is a bit expensive. Could we have just a result of operation - e.g. enum {SUCCESS, FAILED, OVERFLOW}, etc. So that client code could decide what to do with current element that can't be published.

When using sink - each .sink() method call is creating extra wrapper object that is not convenient so it requires caching single sink wrapper when already holding link to a processor - just not the most obvious API behaviour as for me.

**Comment by simonbasle** [comment]
No, `onNext` is part of the `Subscriber` interface and its return type cannot be changed. It would be a RuntimeException used as a deterrent for misuse of the processor.

Direct processor use is good for inner mechanism of operators, when you absolutely know what you're doing (eg. in terms of backpressure, etc...). Having the `sink()` on top gives you a facade that is easier to use, has a smaller API, brings less concerns.

Sure the price to pay for that is that you have to keep a reference to the sink, but you would keep a reference to the processor anyway.

**Comment by Kindrat** [comment]
Maybe, just a bit messy with all these API interface methods.
