### ISSUE TITLE
Revisit Mono.when/and(Mono...) to zip/zipWith 

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#789]

**Comment by simonbasle** [comment]
I would vote in favor of
 - keeping the `and` as an alias for the time being
 - deprecating `when`s and removing at `RELEASE` time per #323 rather than big bang renaming

One behavior that we had a doubt about is `Mono.when(Mono.just("foo"), Mono.empty())`. This produces an empty `Mono` of type `Mono<Tuple2<String, Void>>`.

**Comment by osi** [comment]
another vote for `Mono.and`

is zipper with only one tooth on each side really a zipper?

**Comment by simonbasle** [comment]
closed by d794c93

**Comment by simonbasle** [comment]
The `when`s and associated Kotlin extensions have actually been removed by commit 52f7f04 just before RC1.

**Comment by smaldini** [comment]
Fully improved via #850
