### ISSUE TITLE
Common interface for Flux/Mono that defines common operators

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#85]
This would help to ensure/enforce consistency between common operators on Flux/Mono, but before considering this need to:

1. Determine if there is a performance impact in doing this over final methods in Flux/Mono as used currently.

2. Decide what the best/preferred approach for treating streams (Mono/Flux) generically is.  Is a common interface that extends Publisher preferred, or in fact is the best way to treat stream generically to wrap them in a Flux using Flux.from().  Flux is after all a less specialized version of Mono anyway, given it's a 0..n stream.

1) will determine if this issue is even considered.  2) will help determine is a common interface should/shouldn't extend Publisher.

**Comment by akarnokd** [comment]
1) If you have Common b = a.map(v -> v), JIT has harder time to figure out what the actual type will be and if a call-site switches implementation, you may end up with megamorphic dispatches. A concrete type will yield concrete binding.

2) Doesn't really work in Java because we can't define higher order generic types such as `U<T>` where U can also change. Otherwise, the moment there is a change in the type argument, you need an `? extends Common<T>`:

```java
interface Common<T> {
   <R extends Common<T>> R filter(Predicate<T> predicate);
   <R extends Common<U>> U map(Function<T, U> mapper);
}
```

Returning variant types is discouraged and forces one to have target typing steps, otherwise one looses specifics:

```java
   Common<Integer> c = Flux.range(1, 10);

   c.map(v -> v).filter(v -> true).elementAt(1);

   Flux<Integer> f = c.map(v -> v).filter(v -> true);
   Flux<Integer> g =f.elementAt(1);
```

Interestingly, those who want to split Publisher into subtypes based on numbers later want to "abstract" them back into one single type.

**Comment by smaldini** [comment]
Closing for now, @akarnokd point is valid, we can revisit the issue post 2.5 eventually after some more wave of feedbacks :)
