### ISSUE TITLE
Silent failure on StackOverflowException

### ISSUE THREAD

**Issue by devrandom** [reactor/reactor-core#916]
### Expected behavior

Error logged.

### Actual behavior

Silent failure and pipeline does not complete.

### Steps to reproduce

```
    @Test
    void testErrorInScheduler() {
        Scheduler scheduler = Schedulers.fromExecutor(Executors.newSingleThreadExecutor(new ThreadFactoryBuilder()
                .setUncaughtExceptionHandler((t, ex) -> System.err.print(ex.toString()))
                .build()));

        Flux<String> source = Flux.just("hi");

        StepVerifier.create(source.flatMap(item -> Mono.<String>fromCallable(() -> {
            throw new StackOverflowError("hi");
        }).log().subscribeOn(scheduler)))
                .expectError()
                .verify();
    }
```

### Reactor Core version
3.0.4-RELEASE

### JVM version (e.g. `java -version`)

1.8

### OS version (e.g. `uname -a`)

Ubuntu 16.04

**Comment by smaldini** [comment]
We should maybe remove throwIfFatal check in Schedulers.handleError, worst case is that a fatal termination will rethrow anyway (OoM etc).

**Comment by dfeist** [comment]
@smaldini Rethrowing here would make sense if `WorkerTask` used `UncaughtExceptionHandler` but it doesn't so this needs to be done here, and I see no reason at all why any specific, JVM or other error types, should result in `UncaughtExceptionHandler` not being used, especially given these errors are not propagated via `onErrror`.

I also am not sure why `onHandleErrorHook` should not be notified of these fatal exceptions.  Given these errors will not be propagated up, there is no way for the user to handle these errors and perform any logging/cleanup otherwise.

**Comment by devrandom** [comment]
Thank you.
