### ISSUE TITLE
Provide a dedicated method on Mono which is similar to Optional.orElseThrow()

### ISSUE THREAD

**Issue by akiraly** [reactor/reactor-core#917]
Sorry if this exists already but I couldn't find it.

### Expected behavior

An easy way to specify exceptions (lazily) in case the Mono is empty. Something that would allow to do this:

`Mono.empty().errorIfEmpty(() -> new RuntimeException())`

Currently we can do:

`Mono.empty().switchIfEmpty(Mono.error(new RuntimeException()))`
which is not lazy (the exception is always created)

`Mono.empty().switchIfEmpty(Mono.defer(() -> Mono.error(new RuntimeException())))`
which is lazy but verbose.

Alternatively it would be enough (and more general) if we had a "defer" variant for `switchIfEmpty` which would take a `Supplier<Mono>` similar to `defer()`. Then we could do:

`Mono.empty().deferSwitchIfEmpty(() -> Mono.error(new RuntimeException()))`

It is more verbose than a dedicated `errorIfEmpty` however.

### Reactor Core version
3.1.0.RELEASE

**Comment by simonbasle** [comment]
I'm not sure we want to add a dedicated operator for that, especially since there is an obvious (albeit verbose) workaround, as you have found.

It is a normal and desirable thing to rely on operator composition in a library like Reactor.

What I'd suggest instead, to remove some of the verbosity, is to put the switch/defer/error boilerplate into a method to use with `transform`:

```java
public <T> Mono<T> errorIfEmpty(Mono<T> source) {
  return source.switchIfEmpty(Mono.defer(() -> Mono.error(new RuntimeException())));
}

Mono<String> foo = Mono.empty().transform(this::errorIfEmpty);
```

**Comment by akiraly** [comment]
That is understandable. I thought this a common enough use case to get a method but yes, definitely not a must have in the reactor library itself.

**Comment by simonbasle** [comment]
All righty, I'll close this issue for now then @akiraly, we'll consider it if it comes up again ;)

**Comment by akiraly** [comment]
Just for completeness this is the variant I came up with:

```java
  public <R> Mono<R> errorIfEmpty(Mono<R> mono, Supplier<Throwable> throwableSupplier) {
    requireNonNull(mono, "mono");
    requireNonNull(throwableSupplier, "throwableSupplier");
    return mono.switchIfEmpty(Mono.defer(() -> Mono.error(throwableSupplier.get())));
  }
```

and the usage:

`myMono.transform(m -> errorIfEmpty(m, () -> new RuntimeException()))`

or just

`errorIfEmpty(myMono, () -> new RuntimeException())`

**Comment by berry120** [comment]
Noticing this hasn't had any activity in a while, but I'd throw my +1 in the mix for this to be in the core library. Wanting a `Mono` to return *exactly* one (rather than at least one) element is a common enough scenario that I'd say this deserves its own top level operator (or is it just me that does this often?!)

`transform(this::errorIfEmpty)` and similar workarounds are of course fine functionally, but at a quick glance it's much less readable than a dedicated "orElseThrow()` or similar method, which makes it instantly clear what's going on.

**Comment by simonbasle** [comment]
@berry120 notice that there are kinda two issues here: making the empty case an error and lazily choosing said error. This issue is about the later, since there is the `single()` operator that propagates `NoSuchElementException` in case the source is empty.

Btw this makes me think that the error-of-ones-choosing-on-empty full capability can be achieved with:

```java
Mono.empty()
    .single()
    .onErrorMap(NoSuchElementException.class, e -> new MyOwnException("message", e))
```

**Comment by berry120** [comment]
> This issue is about the later, since there is the single() operator that propagates NoSuchElementException in case the source is empty.

Oh dear... how that operator could have passed me by I don't know. That's exactly what I was looking for. I'll retreat to my corner again :-)

**Comment by lanmingle** [comment]
``` java

@Slf4j
@Component
public class TestWebFilter implements WebFilter, Ordered {

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
        log.info("测试过滤器 - TestWebFilter");
        return this.getDemo()
                .switchIfEmpty(Mono.defer(() -> Mono.error(this::errorNull)))
                .map(d -> setAttr(d, exchange))
                .then(chain.filter(exchange))
                ;

    }

    public Demo setAttr(Demo demo, ServerWebExchange exchange) {
        log.info("测试过滤器 - setAttr - demo={}", demo);
        exchange.getAttributes().put(Demo.class.getName(), demo);
        return demo;
    }

    public Mono<Demo> getDemo() {
        log.info("测试过滤器 - getDemo");
        Demo demo = new Demo();
        demo.setName("getDemo");
        demo.setNumber(888);
//        return Mono.empty();
        return Mono.just(demo);
    }

    public Mono<Demo> emptyDemo() {
        log.info("测试过滤器 - emptyDemo");
        Demo demo = new Demo();
        demo.setName("emptyDemo");
        demo.setNumber(999);
        return Mono.just(demo);
    }

    public Throwable errorNull() {
        log.info("测试过滤器 - errorNull");
        return Nex.common().message("error null").build();
    }

    public <T> Mono<T> errorIfEmpty(Mono<T> source, Throwable throwable) {
        log.info("测试过滤器 - errorIfEmpty");
        return source.switchIfEmpty(Mono.defer(() -> Mono.error(throwable)));
    }

    @Override
    public int getOrder() {
        return 2048;
    }

}

```

使用 errorIfEmpty 始终被执行，测试使用

``` java

.switchIfEmpty(Mono.defer(() -> Mono.error(this::errorNull)))

```

没有问题。

**Comment by simonbasle** [comment]
`Optional` has a far tighter scope than `Mono`, and you can't pretend that transposing APIs from one to the other is obviously "the way to go"... Methods names that make perfect sense in the context of an `Optional` can be less adapted in other contexts. We also have an `#or` operator, so any new operator with the `or` prefix could create some confusion with it.

@szigya Your opinion of what's readable and what doesn't require googling is just that, your opinion. Instead of showing you read and understood the whole issue and offering constructive ways to improve the situation, you decided to condescendingly imply that you would have done a better job and that we don't have the community in mind when evolving Reactor... I'll stop the discussion here, because I've devoted way too much of my time to this answer already. Stop venting on the Internet.

**Comment by szigya** [comment]
Readability is not an opinion here, objectively more complicated thhings are less readable. But I get it, you time is prescious and people either agree with you or venting. ;)

**Comment by simonbasle** [comment]
please note that I'm not against different opinions, as long as they are expressed in a constructive way. the last comments from @szigya have been far from constructive, and passive-aggressive. removing these and locking this conversation.
