### ISSUE TITLE
Kotlin Extensions for Java 9 Flow API

### ISSUE THREAD

**Issue by JoeHegarty** [reactor/reactor-core#948]
It would be great if there were Kotlin extensions for the Java 9 flow API. As far as I can tell they don't yet exist.
It's really useful to just be able to `toFlowPublisher` at API boundaries etc rather than wrap with the current JdkFlowAdapter static methods.

```kotlin
fun <T> Flux<T>.toFlowPublisher() = JdkFlowAdapter.publisherToFlowPublisher(this)
fun <T> Mono<T>.toFlowPublisher() = JdkFlowAdapter.publisherToFlowPublisher(this)
fun <T> Flow.Publisher<T>.toFlux() = JdkFlowAdapter.flowPublisherToFlux(this)
```
This seems like it would cover most cases. 

I'm happy to submit a PR but it's a tiny change and it's not clear to me if this is necessarily the best implementation, where it should live (own file like the current adapters or split up in the FluxExtensions etc) or if I've overlooked any considerations for Java 8 compatibility.

**Comment by simonbasle** [comment]
It would definitely need to be in a separate kotlin file. I'm not sure either how it will impact the Java 8 artifacts, since the adapter already feels kinda hacky (use of optional JSR166-backport dependency).

As a consequence, and since it's only three extension methods, I'm a bit torn on this issue and I think maybe this should be deferred to the user codebase rather than Reactor's.

Any insight @sdeleuze ?

**Comment by sdeleuze** [comment]
Does Reactor build on Java 9 already or just Java 8 + JSR166-backport dependency? If yes is there any CI job?

**Comment by simonbasle** [comment]
Travis CI is configured to add a job that builds on Java 9 (with a few less build steps, like no asciidoctor-to-pdf) in complement of each Java 8 build, but I must admit I haven't closely looked at the backport with regard to said job.

**Comment by simonbasle** [comment]
I'm closing this as I believe this is a better fit for the user codebase rather than Reactor's for now.
