### ISSUE TITLE
Right way to use Reactor as a task executor

### ISSUE THREAD

**Issue by mageddo** [reactor/reactor-core#953]
I've asked in [stackoverflow](https://stackoverflow.com/questions/47353526/right-way-to-use-reactor-as-a-task-executor) best way of how use reactor as a task executor but looks like anyone is looking at reactor questions:

I was looking at [documentation][1] a way to use Reactor as a task executor. I want to submit some tasks, parallelize it then wait for it termination like the ThreadService, sample bellow:

	final ExecutorService pool = Executors.newFixedThreadPool(10);
	pool.submit(() -> {sleep(200);System.out.println(1);});
	pool.submit(() -> System.out.println(2));
	pool.submit(() -> System.out.println(3));
	pool.submit(() -> System.out.println(4));
	pool.submit(() -> System.out.println(5));
	pool.submit(() -> System.out.println(6));
	pool.submit(() -> System.out.println(7));
	pool.submit(() -> System.out.println(8));
	pool.submit(() -> System.out.println(9));
	pool.submit(() -> System.out.println(10));

	pool.awaitTermination(5, TimeUnit.SECONDS);
	pool.shutdown();

I only got that when collecting the results to a list

	final List<Integer> result = Flux.range(1, 15)
		.parallel()
		.runOn(Schedulers.elastic())
		.map(n -> {
			// simulating heavy task
			sleep((long) (Math.random() * 100));
			return n;
		})
		.sequential()
		.collectList().block();
	System.out.println(result);

Is there a better way to do that?

  [1]: http://projectreactor.io/docs/core/release/reference

**Comment by simonbasle** [comment]
@mageddo first please keep in mind that your blocking `map` is fine **only** because you are running it in an elastic `Scheduler` (could have been `parallel()` too).

if you don't care about the result and want to block on the termination, you can use `.blockLast()` (it will return the last `n` computed, but you can ignore that. 

if you want to compose further on the chain, like starting another process, you can use chain flavor of `then`, which will return a `Mono` that represents the task termination (dropping the data events).

**Comment by simonbasle** [comment]
(regarding your "doesn't look like anyone is looking at SO question" comment: I try to look at them 😄 sometimes it takes more than 5hrs for me to notice them - especially on a Friday afternoon and subsequent week-end 😱😜)

**Comment by mageddo** [comment]
Thanks a lot, it was really clarifying.
