### ISSUE TITLE
ParallelFlux#composeGroup should conserve parallelism and prefetch

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#968]
Currently, it reverts back to default due to its use of `ParallelFlux.from()`

Should also check if there are any other ParallelFlux operators that this applies to

**Comment by simonbasle** [comment]
the `from` can be called with `parallelism()` to maintain the same parallelism (which should otherwise be propagated correctly by other parallel operators).
It should be possible to maintain the prefetch as well IF `getPrefetch()` doesn't return `-1` (in which case the fallback would be to use `from(parallelism)` overload).
